### ISSUE TITLE
Add protocol option for server

### ISSUE THREAD

**Issue by piotrpekala7** [GNS3/gns3-web-ui#1007]
We need to add protocol option for server with the default being the same as how the web-ui is accessed

**Comment by piotrpekala7** [comment]
should be fixed in https://github.com/GNS3/gns3-web-ui/commit/288879ccb2cecd254c2af2579d2ffbfc6c3f3a5b

**Comment by grossmj** [comment]
I checked and it worked.

**Comment by julazcano** [comment]
> I checked and it worked.

Hi gang,
I just retested, and I'm noticing that although the API calls are properly using HTTPS/SSL, for some reason the /projects and /version is hardcoding port 80 to the call.

For Reference:
Screenshot 1 shows the hardcoded SSL call on port 80 for /projects.

![Screenshot 1](https://user-images.githubusercontent.com/32578400/98858328-47a76d00-2415-11eb-808a-bcdf2660a87a.png)

Screenshot 2 shows the hardcoded SSL call on port 80 for /version after I click on the "servers" icon in the top left.

![Screeshot 2](https://user-images.githubusercontent.com/32578400/98858366-568e1f80-2415-11eb-8a6b-aea717eb15a7.png)

**Comment by piotrpekala7** [comment]
@julazcano 
Server Discovery Component search for running server with http protocol so it should check version.

**Comment by piotrpekala7** [comment]
As for the projects page, I can't find the source of the error. The project site does not use hardcoded queries 
https://github.com/GNS3/gns3-web-ui/blob/master/src/app/services/project.service.ts#L34
