### ISSUE TITLE
Error when going to servers page

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#1008]
I always get the following error when navigating to the servers page. Doesn't seem to have any consequences though...

![Screenshot from 2020-11-05 15-31-25](https://user-images.githubusercontent.com/4752614/98199893-39bc9c80-1f7c-11eb-8f6a-45490bd25579.png)

**Comment by grossmj** [comment]
David reported something similar: [chrome_error.zip](https://github.com/GNS3/gns3-web-ui/files/5599926/chrome_error.zip)

**Comment by grossmj** [comment]
Same issue if I open a project in Chrome then copy the project URL (http://192.168.41.128/static/web-ui/server/1/project/a4d9309e-e24a-4a37-a3c8-8647963a66da) to Firefox (with cleared data cache).

![Uploading Screenshot from 2020-11-29 15-58-43.png…]()

**Comment by piotrpekala7** [comment]
@grossmj 
I can confirm issue in production mode however it's not visible in development mode, very strange

**Comment by piotrpekala7** [comment]
I'm checking it, definitely it should be fixed before next release

**Comment by piotrpekala7** [comment]
I committed solution for this issue https://github.com/GNS3/gns3-web-ui/commit/73ef1f0f807453aae80cd319d9854293aa2b392f, checked in development and production mode, 
@grossmj it seems to me that now it should work properly in every environment, but please check

**Comment by grossmj** [comment]
Thanks, looks like it is fixed.
