### ISSUE TITLE
Users shound't be able to create an appliances with missing files.

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#1016]
In the example, the wrong image file is upload but user still able to create an appliance.

Video: 
[arista issues.zip](https://github.com/GNS3/gns3-web-ui/files/5599960/arista.issues.zip)

**Comment by piotrpekala7** [comment]
fixed in https://github.com/GNS3/gns3-web-ui/commit/383c628f2fd2f1e1e7e74d2cbb01a6bda5374922
