### ISSUE TITLE
"Failed to decode downloaded font: NotoSans-Bold"

### ISSUE THREAD

**Issue by candlerb** [GNS3/gns3-web-ui#1026]
Using the web interface supplied with `2.2.17~bionic1`: it works, but I noticed that the developer console reports this error:

![image](https://user-images.githubusercontent.com/44789/104728181-6cc69d80-572e-11eb-89b9-2e7875612ea2.png)

This is with Chrome 87.0.4280.141 under macOS 10.14.6.

Just thought it was worth mentioning.

**Comment by piotrpekala7** [comment]
node-sass has been removed recently https://github.com/GNS3/gns3-web-ui/commit/2c5683917b550d1b2ffa6f7d1a9a0c460101515a, it should disappear in future version
