### ISSUE TITLE
dark theme not working

### ISSUE THREAD

**Issue by kusky3** [GNS3/gns3-web-ui#1028]
selecting dark theme in the settings loads "http://localhost/static/web-ui/theme-default-dark.css" which gives "error 404 not found" and the dark themes doesn't apply
gns3 vm 2.2.17

**Comment by piotrpekala7** [comment]
![darkTheme](https://user-images.githubusercontent.com/31202938/105403799-82a1fa00-5c29-11eb-8009-cb7a4858299e.PNG)

Hi,

could you please give us more detailed information? I tested dark theme in Chrome 87.0.4280.88 && latest FF and all works as expected.

Regards

**Comment by kusky3** [comment]
i've tried with virtualbox, proxmox, firefox and chromium all at the latest version. fresh install, i go to the web page and the "switch to dark theme" button, no matter how many times i click it, is unresponsive. looking at the network requests, it keeps getting /*dark.css but the webserver returns a 404.
