### ISSUE TITLE
Template Configuration Category

### ISSUE THREAD

**Issue by Desposyni** [GNS3/gns3-web-ui#1032]
Built-In and IOU templates are able to have their category changed, but VPCS, Docker, VMware, Virtualbox, and QEMU templates are only able to use the "Default" category.

This is a sample of the error: 

> JSON schema error with API request ... 'routers' is not of type 'integer'

In the configuration-service.ts files within the src/app/services/ folder, there are two ways they define 'categories'.
The files that work have the following:
```
let categories = [["Default", "guest"],
            ["Routers", "router"],
            ["Switches", "switch"],
            ["End devices", "end_device"],
```

The files that do not work have the following:
```
 let categories = [["Default", "guest"],
            ["Routers", "routers"],
            ["Switches", "switches"],
            ["End devices", "end_devices"],
```

**Comment by Desposyni** [comment]
End devices and Security devices also return the same '... is not of type integer' error.

Valid categories according to gns3-server/gns3server/schemas/template.py
```
"category": {
        "description": "Template category",
        "anyOf": [
            {"type": "integer"},  # old category support
            {"enum": ["router", "switch", "guest", "firewall"]}
```

Valid categories according to gns3-registry/schemas/appliance_v6.json
```
"category": {
      "enum": [
          "router",
          "multilayer_switch",
          "firewall",
          "guest"
      ],
      "title": "Category of the appliance"
```

**Comment by piotrpekala7** [comment]
@Desposyni I'm testing your changes on pr https://github.com/GNS3/gns3-web-ui/pull/1033

**Comment by piotrpekala7** [comment]
@Desposyni Thank you very for creating issue! Should be released with next version
