### ISSUE TITLE
Help menu should include a link to https://docs.gns3.com/docs/

### ISSUE THREAD

**Issue by eantowne** [GNS3/gns3-web-ui#1042]
Enhancement Request

Version 2.2.18 / 2020.4.0-beta.1

Help menu entry should also include a link to: https://docs.gns3.com/docs/ as a reference.

**Comment by piotrpekala7** [comment]
added in https://github.com/GNS3/gns3-web-ui/commit/e1b0e739161d99d68a72e00d8a59a07e0dba66eb
