### ISSUE TITLE
Cannot connect to the server: Error Server is unreachable

### ISSUE THREAD

**Issue by sada45** [GNS3/gns3-web-ui#1045]
Hey:
I encountered some errors when connecting to the remote server in gns3-web-ui. I deploy the gns3-server and gns3-web-ui on a same virtual machine using Unbuntu2004 and VMware16. I have mapped the VM's 4200 and 3080 port to 33650 and 33651 port on host machine. The firewall has allow the TCP connection on these two ports.

It is fine to add a remote server in the VM(login at port 4200 and server at port 3080) but it failed in the host (login at port 33650 and server at port 33651) with an error "Cannot connect to the server: Error Server is unreachable" 
<img width=50% src=https://user-images.githubusercontent.com/49777976/112744275-2795d600-8fd1-11eb-88c6-1383cb811732.png>

However, the server's log shows it did receive the HTTP GET request from host. The 192.168.35.1 is the gateway of VM, and each time I click "add" it shows up a log.
<img width=80% alt="server log" src="https://user-images.githubusercontent.com/49777976/112744376-287b3780-8fd2-11eb-9861-e2e87c2ff0d7.png">

I don't think it is firewall problem, because I can access to the web page both on 33650 and 33651. It seems that the gns3-server itself has provided a web-ui at port 3080 (mapped to port 33651 at host). And at gns3-server's web-ui, it has a "bundled" server. So, what is the different between these two web-ui? Can I just use the web-ui provided by gns3-server?
<img width=50% src=https://user-images.githubusercontent.com/49777976/112744568-cb808100-8fd3-11eb-9740-34b83861e4d4.png>

By the way, It seems that the web-ui not adaptated to 4K display yet. Both the two problem shows blow didn't show up on another 1080P PC. First, there is a blank space pops up and down when I have opened a Web console and move my mouse.
![20210325-222217_李烨明_李烨明发起的视频会议_video (1) (1)](https://user-images.githubusercontent.com/49777976/112564777-d5a95080-8e16-11eb-986d-9ebe534f9a79.gif)

Also, the last line in the console may only show half of it
<img width=50% src=https://user-images.githubusercontent.com/49777976/112744642-8b6dce00-8fd4-11eb-8552-406439096465.png>

Thanks!

**Comment by piotrpekala7** [comment]
and yes, you can use web ui provided by gns3 server, open localhost:3080/static/web-ui/bundled

**Comment by piotrpekala7** [comment]
2. when it comes to second one, it' definitely a bug, I'm working on this, I will report under this issues when this will be fixed

**Comment by piotrpekala7** [comment]
issue with 4k resolution should be fixed in https://github.com/GNS3/gns3-web-ui/commit/da5eb7a4b6f2c75cca982534755cbcd4854c98ed, please check for updates
