### ISSUE TITLE
Fill node width and height with correct values

### ISSUE THREAD

**Issue by piotrpekala7** [GNS3/gns3-web-ui#1047]
When we use custom symbol for particular node, its width and height is set to zero, that could cause problems with correct rendering

**Comment by piotrpekala7** [comment]
I tried to fix this on web UI side by reading dimension from raw svg file but this doesn't make sense
```
getImageFromURL(url: string) {
    return Observable.create((observer: Observer<string>) => {
      let img = new Image();
      img.crossOrigin = 'Anonymous';
      img.src = url;
      if (!img.complete) {
        img.onload = () => {
          observer.next(this.getBase64Image(img));
          observer.complete();
        };
        img.onerror = (err) => {
          observer.error(err);
        };
      } else {
        observer.next(this.getBase64Image(img));
        observer.complete();
      }
    });
  }
```

**Comment by piotrpekala7** [comment]
so what we can do:
- add endpoint with symbol size to render it correctly (in symbols_handler /symbols/{symbol_id:.+} which returns symbol info - width+height -> then use it to fill node values)
- save node width and height after changing symbol by server side

**Comment by piotrpekala7** [comment]
@grossmj 
please let me know what will be better

**Comment by grossmj** [comment]
I have noticed that we resize the SVG symbols if above 80 in height: https://github.com/GNS3/gns3-gui/blob/master/gns3/items/node_item.py#L145L148

Using this method in the GUI: https://github.com/GNS3/gns3-gui/blob/master/gns3/qt/qimage_svg_renderer.py#L98L133

![Selection_011](https://user-images.githubusercontent.com/4752614/113884046-d4582a80-97fd-11eb-92f6-b523c74aad5c.png)

**Comment by piotrpekala7** [comment]
I think we can do that and we can add such an option then we need an endpoint to get the dimensions of the symbol

**Comment by grossmj** [comment]
I think an endpoint to get the dimensions would be a great addition.

**Comment by piotrpekala7** [comment]
blocked by https://github.com/GNS3/gns3-server/issues/1884

**Comment by piotrpekala7** [comment]
closed with https://github.com/GNS3/gns3-web-ui/pull/1055
