### ISSUE TITLE
Affinity Circle Cloud Icon

### ISSUE THREAD

**Issue by keithstowe** [GNS3/gns3-web-ui#1056]
![Screenshot from 2021-04-10 14-50-43](https://user-images.githubusercontent.com/66480474/114272081-7baaac80-9a0c-11eb-9732-ac9351dac1b0.png)

When attaching a link to the Affinity Circle Cloud icon it is not centred. It connects to the left.

**Comment by piotrpekala7** [comment]
![Capture](https://user-images.githubusercontent.com/31202938/114284603-52603f80-9a51-11eb-8525-9d5cb4a0d9c9.PNG)

@keithstowe this problem will be solved with 2.2.21 version, please wait for next release or download the web UI repository, thanks for reporting!

**Comment by grossmj** [comment]
Fixed :+1:
