### ISSUE TITLE
Update styling for web console

### ISSUE THREAD

**Issue by piotrpekala7** [GNS3/gns3-web-ui#1057]
We should update styling of web console after changes in topology summary widget and left toolbar

**Comment by piotrpekala7** [comment]
updated in in https://github.com/GNS3/gns3-web-ui/commit/1dc488707157e255aff3005929646b09f2cd1a30

**Comment by piotrpekala7** [comment]
@grossmj should we change position of web console (after opening widget) after changes in design of project page? the left toolbar now is longer and thinner

**Comment by grossmj** [comment]
> @grossmj should we change position of web console (after opening widget) after changes in design of project page? the left toolbar now is longer and thinner

Let me check that soon.

@piotrpekala7 there is another issue with the web console: https://github.com/GNS3/gns3-gui/issues/3165

**Comment by grossmj** [comment]
Indeed, the default web console position isn't ideal. Let's move it a bit on the left for now. 

![Screenshot from 2021-04-13 14-00-21](https://user-images.githubusercontent.com/4752614/114497211-c290e000-9c60-11eb-9ed5-68e451f89abd.png)

**Comment by piotrpekala7** [comment]
ok, done in https://github.com/GNS3/gns3-web-ui/commit/2350f88c59e9742c44391c0660c326184e575bb8
