### ISSUE TITLE
Improve overall performance

### ISSUE THREAD

**Issue by piotrpekala7** [GNS3/gns3-web-ui#1058]
![lighthouse](https://user-images.githubusercontent.com/31202938/114383509-eb947080-9b8d-11eb-979f-b3324e198867.PNG)
results from testing by lighthouse

**Comment by piotrpekala7** [comment]
pull request prepared here https://github.com/GNS3/gns3-web-ui/pull/1059

**Comment by grossmj** [comment]
Is there anything specific I should verify?

**Comment by piotrpekala7** [comment]
in fact, these changes are visible on the pull request, it's hard to verify them

**Comment by grossmj** [comment]
Everything seems to run well when using the Ui. I think you can close this and we can re-open if we notice issues later.
