### ISSUE TITLE
API changes for 3.0

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#1117]
@piotrpekala7 

I am making good progress on version 3.0 of the GNS3 server: https://github.com/GNS3/gns3-server/tree/3.0

I think it is time to start having the web-ui implement changes as we progress towards a final version. First, please make sure all previous web-ui commits have been merged in the 3.0 branch.

Here are the few changes on the API side for now:

- All API endpoints must use “v3” instead of “v2”
- API endpoint `/{link_id}/start_capture` has been replaced by `/{link_id}/capture/start`
- API endpoint `/{link_id}/stop_capture` has been replaced by `/{link_id}/capture/stop`
- API endpoint `/{link_id}/pcap` has been replaced by `/{link_id}/capture/stream`
- API endpoint ​`/computes​/{compute_id}​/ports` has been removed. I don't think it is used in the web-ui.
- All Traceng code has been removed (including endpoints).

Expect more changes until we hit beta stage.

**Comment by piotrpekala7** [comment]
migration to v3 https://github.com/GNS3/gns3-web-ui/commit/64b814acd7a49802e6e35aebf3680efccaa579e2

**Comment by piotrpekala7** [comment]
endpoints updated in https://github.com/GNS3/gns3-web-ui/commit/a9aa64c7f581dae37aacdca4cb1035a5bf106af4

**Comment by piotrpekala7** [comment]
traceng related code removed in https://github.com/GNS3/gns3-web-ui/commit/84f7fabdc8e202b85a571fa36d0578a70fa19d92

**Comment by piotrpekala7** [comment]
this task don't need verification

**Comment by grossmj** [comment]
@piotrpekala7 have you tested if you can connect to the gns3server 3.0?

I always get the following error when trying to add a server. I am sure my GNS3 server is running and I don't see any incoming connection in the logs.

![Screenshot from 2021-04-28 21-00-10](https://user-images.githubusercontent.com/4752614/116396651-c9287580-a864-11eb-8d1e-9ac99b87eff4.png)

**Comment by piotrpekala7** [comment]
problems solved by server side, anyway I updated version to 3.0 in https://github.com/GNS3/gns3-web-ui/commit/ab6c43c1674c4137df53be178b8eafde578f8d7b so now adding server should work

**Comment by grossmj** [comment]
Thanks,working on my side too :+1:
