### ISSUE TITLE
Login page

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#1118]
GNS3 server on branch 3.0 now supports user management (permissions management will follow).

![Screenshot from 2021-04-20 16-12-07](https://user-images.githubusercontent.com/4752614/115349858-8676f580-a1f3-11eb-9a81-c1d0e27e8b07.png)

What we need is a login page that is shown before the projects list is displayed or if an user tries to access any other page (excepting the servers one) without being authenticated.

The login page should include our logo and the server version as well as the default username/password if an user fails to authenticate. 

Here are examples with CML and EVE-NG:

![Screenshot from 2021-04-20 15-56-42](https://user-images.githubusercontent.com/4752614/115347854-12d3e900-a1f1-11eb-8d6d-189e51288640.png)

![Screenshot from 2021-04-20 12-58-15](https://user-images.githubusercontent.com/4752614/115347839-0cde0800-a1f1-11eb-9c48-2023fe06254a.png)

By default, the server has a super admin account with username/password = admin/admin which should be enough for your tests.

The API documentation is provided by the server with the `docs` endpoint, for instance `http://localhost:3080/docs`. You can test the authentication by clicking on `Authorize`. The API endpoints with a lock are the secured ones.

![Screenshot from 2021-04-20 16-12-41](https://user-images.githubusercontent.com/4752614/115349925-97276b80-a1f3-11eb-84cb-4ac2f0441353.png)

The endpoint to authenticate users is `/v3/users/login`, you must use form data (`x-www-form-urlencoded`) to send the username/password.

Example with CURL: 

```
curl http://localhost:3080/v3/users/login -H "Content-Type: application/x-www-form-urlencoded" -d "username=admin&password=admin"
{"access_token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTYxODk4ODA1N30.z5a079nbixurKWplNveLVHa_bnY_dWBzsxu-IITzLDM","token_type":"bearer"}
```

Then you must use the access token for requests to all secured endpoints by adding an HTTP header `"Authorization": "Bearer <access_token>"`

Example with CURL: 

```
curl -H 'Accept: application/json' -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTYxODk4ODA1N30.z5a079nbixurKWplNveLVHa_bnY_dWBzsxu-IITzLDM" http://localhost:3080/v3/statistics
```

**Comment by piotrpekala7** [comment]
login component added in https://github.com/GNS3/gns3-web-ui/commit/71077413b7735170aec0e05700bbe8e0b09131ef

**Comment by piotrpekala7** [comment]
login guard added in https://github.com/GNS3/gns3-web-ui/commit/9835c106d8e4129dc5d96c4fac1765832f1c757e

**Comment by grossmj** [comment]
Some improvements:

![Screenshot from 2021-05-06 15-57-52](https://user-images.githubusercontent.com/4752614/117252416-13bd7980-ae85-11eb-9408-e95a6777cfb0.png)

**Comment by grossmj** [comment]
Bug: if I open a project and then go to the projects page and logout. I see the back to project button in the menu.

![Selection_015](https://user-images.githubusercontent.com/4752614/117252526-3fd8fa80-ae85-11eb-8e34-4cf35cfe1d0e.png)

Another problem, I get a blank page if I logout and try to directly access a project:

![Screenshot from 2021-05-06 16-06-19](https://user-images.githubusercontent.com/4752614/117252642-6a2ab800-ae85-11eb-8a38-adea99a36d9a.png)

![Screenshot from 2021-05-06 16-06-34](https://user-images.githubusercontent.com/4752614/117252657-6f880280-ae85-11eb-87ab-a5299af5fa37.png)

**Comment by piotrpekala7** [comment]
fix for login page https://github.com/GNS3/gns3-web-ui/commit/06ad9c2f07c30b566fb0a744813f618a4ab3ea0e

**Comment by piotrpekala7** [comment]
fix for redirection to login page https://github.com/GNS3/gns3-web-ui/commit/a5b4a128492a9afe43c7358aea0c1ed91c92af80

**Comment by piotrpekala7** [comment]
@grossmj You didn't mention it in description but I added functionality to remember the original url that was passed from the LoginGuard as a route parameter and stores it in the local returnUrl property. If the original url is empty, user is redirected to the servers page

**Comment by grossmj** [comment]
Working well :+1:
