### ISSUE TITLE
Remove basic authorization

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#1119]
We won't need basic authorization support once we implement this: https://github.com/GNS3/gns3-web-ui/issues/1118

![Selection_014](https://user-images.githubusercontent.com/4752614/115385275-1b3f1a80-a217-11eb-91ab-a93718cd86a0.png)

**Comment by piotrpekala7** [comment]
removed in https://github.com/GNS3/gns3-web-ui/commit/5cfda3500a9baf831c9cb59f397c5947af4a59fc
