### ISSUE TITLE
Loading symbols after migrating to v3

### ISSUE THREAD

**Issue by piotrpekala7** [GNS3/gns3-web-ui#1123]
Symbols endpoint is now secured so we need to change the way we render symbols on map

`.attr('xnode:href', (n: MapNode) => n.symbolUrl)`

**Comment by piotrpekala7** [comment]
I tried to add http interceptor https://github.com/GNS3/gns3-web-ui/commit/17acd161d8195f46b705290e408da6f3ff2c585e but it only works for requests from http client, 
at the moment I don't know a solution how to do it for svg

**Comment by grossmj** [comment]
Maybe we can consider making that symbol endpoint unsecure? Do we need to secure this?

**Comment by piotrpekala7** [comment]
@grossmj I think this is the simplest solution

**Comment by grossmj** [comment]
I have given more thoughts about it. I don't understand why you can't send tokens in symbol requests but I think not having `GET /v3/symbols/{symbol_id}/raw` secured could be a problem on the long term, for instance what if an user upload custom symbols using `POST /v3/symbols/{symbol_id}/raw`? the symbols would be stored in a dedicated directory, now do we know which directory to look into when an user retrieves a custom symbol?

**Comment by piotrpekala7** [comment]
I don't know a workaround for this problem, I think we can talk to someone how to do it in a good way

**Comment by grossmj** [comment]
Working, I just noticed that loading the symbols were a bit slower (like 1-2 seconds, not a problem) :+1:

**Comment by grossmj** [comment]
It seems we have many issues since we have implemented this (i.e. https://github.com/GNS3/gns3-web-ui/issues/1160).

Let me see if we can make the GET symbol endpoint unsecured as originally suggested.

**Comment by piotrpekala7** [comment]
in the meantime, I'll check why changing symbols doesn't work as it should in current implementation

**Comment by piotrpekala7** [comment]
@grossmj 

> Let me see if we can make the GET symbol endpoint unsecured as originally suggested.

did you have the opportunity to check it?

**Comment by grossmj** [comment]
> Let me see if we can make the GET symbol endpoint unsecured as originally suggested.

I made the change.

**Comment by piotrpekala7** [comment]
I created pull request for this https://github.com/GNS3/gns3-web-ui/pull/1172

**Comment by piotrpekala7** [comment]
pr merged, I didn't notice any problems after this changes

**Comment by grossmj** [comment]
Confirmed, I haven't noticed any problems
