### ISSUE TITLE
Logout support

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#1124]
We should allow an user to logout (which would bring him/her back to the login page).

![Screenshot from 2021-05-05 19-55-46](https://user-images.githubusercontent.com/4752614/117128075-187a2300-addc-11eb-9ea0-61b519064244.png)

**Comment by piotrpekala7** [comment]
added in https://github.com/GNS3/gns3-web-ui/commit/f7a3df27b8bc42b8320620476415ed5bd694c8b8

**Comment by grossmj** [comment]
When I click on 'Logout', I go back to the login page but still can access the settings. I click 'Logout' again and get this error:

![Screenshot from 2021-05-06 10-22-04](https://user-images.githubusercontent.com/4752614/117226966-f670b700-ae54-11eb-9d9b-5fae5a8216ec.png)

**Comment by piotrpekala7** [comment]
@grossmj 

as for the following pages, access to them is not dependent on the server because no actions related to it are performed on them

```
      { path: 'help', component: HelpComponent },
      { path: 'help/reportissue', component: ReportIssueComponent },
      { path: 'settings', component: SettingsComponent },
      { path: 'settings/console', component: ConsoleComponent },
      { path: 'installed-software', component: InstalledSoftwareComponent },
```

**Comment by piotrpekala7** [comment]
so the question is if we want to keep logout button in this menu and change its visibility or maybe it should not be in this menu, I don't know what's better

**Comment by grossmj** [comment]
Working now. Have you changed something?

**Comment by grossmj** [comment]
We cannot access the settings menu when not logged in: https://github.com/GNS3/gns3-web-ui/issues/1118 This fixed the problem reported above I guess.
