### ISSUE TITLE
Ctrl-C to interrupt a running process should work in web console

### ISSUE THREAD

**Issue by candlerb** [GNS3/gns3-web-ui#1125]
This is with the web UI bundled with `gns3-server 2.2.20~bionic1`.  My web browser is Chrome 90.0.4430.93 under macOS 10.14.6, but I see the same with Firefox 88.0.

The problem: when I run an Ubuntu 18.04 VM under gns3, and connect to its (serial) console using the web console via the GNS3 web UI, then `ctrl-C` does not work - nothing happens. e.g.

```
ping -c100 8.8.8.8
(hit ctrl-C to try to abort - ping carries on running)
```

However other control sequences like `ctrl-Z` (suspend) and `ctrl-\\` (abort) do work.

Here is what stty inside the webUI console shows:

```
sysadm@noc:~$ stty -a
speed 9600 baud; rows 24; columns 80; line = 0;
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>;
eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R;
werase = ^W; lnext = ^V; discard = ^O; min = 1; time = 0;
-parenb -parodd -cmspar cs8 hupcl -cstopb cread -clocal -crtscts
-ignbrk brkint ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl ixon -ixoff
-iuclc -ixany imaxbel iutf8
opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
isig icanon -iexten echo echoe echok -echonl -noflsh -xcase -tostop -echoprt
echoctl echoke -flusho -extproc
sysadm@noc:~$ 
```

I'm not sure if it was an issue with earlier versions of the gns3 web UI or not.  That is, I don't remember Ctrl-C *not* working, but I can't say for sure that I definitely did use Ctrl-C.

**Comment by piotrpekala7** [comment]
Hi @candlerb 
Thanks for reporting! we use xtermjs console in web UI, I'm not sure if we are able to provide such a functionality

**Comment by piotrpekala7** [comment]
maybe I don't understand you correctly but ctrl+c and ctrl+v work fine in current version of xtermjs

**Comment by candlerb** [comment]
This isn't copy/paste: this is Ctrl-C to interrupt a running process in a Linux shell.  Within a console, copy-paste works using clover-C/clover-V as usual (I am on macOS)

Now, I have tested an entirely separate installation of xterm.js and ctrl-C *does* work.  Where it doesn't work is the xterm.js which is bundled with the web-ui which is bundled with gns3-server 2.2.20.

Therefore, I will dig around to see if I can find a difference in the versions and/or the way they're configured.

**Comment by candlerb** [comment]
For the standalone version of xterm.js, where ctrl-C works:
* [This](https://github.com/nsrc-org/nsrc-web/blob/main/cgi-bin/console#L136-L167) is the HTML which invokes it (a CGI inserts the appropriate websocket address)
* [This](https://github.com/nsrc-org/nsrc-web/tree/main/static/js) is the Javascript used.  The original source URLs are:
    * https://unpkg.com/xterm@4.8.1/css/xterm.css
    * https://unpkg.com/xterm@4.8.1/lib/xterm.js
    * https://unpkg.com/xterm-addon-fit@0.4.0/lib/xterm-addon-fit.js
    * https://unpkg.com/xterm-addon-attach@0.6.0/lib/xterm-addon-attach.js

The [versions](https://github.com/GNS3/gns3-web-ui/blob/v2.2.20/pack) used in gns3-web-ui v2.2.0 are newer.  So now I need to see if something has broken in newer xterm.js, or if it's something to do with the way xterm.js is bound to the terminal session.

**Comment by candlerb** [comment]
After updating my local xterm.js with the latest versions, ctrl-C still works(*).  This means there's something about the way GNS3 binds to xterm.js which is causing the problem for me.  I don't really know where to start looking for that.

Perhaps the most helpful thing would be if I can help you reproduce it.  I have created a project with just an Ubuntu VM and NAT, and published in these gists:
* [portable project file](https://gist.github.com/candlerb/033cead31000c8064f9430ce12f60abe) (base64-encoded)
* [project.gns3](https://gist.github.com/candlerb/24f41066e853dbd680752f206c36e674) by itself

The image it uses is:
```
          "hda_disk_image": "ubuntu-18.04-server-cloudimg-amd64-20210415.img",
          "hda_disk_image_md5sum": "7b3e1978e6d73c64f6faca56bbb97369",
```
which you can download from [here](https://cloud-images.ubuntu.com/releases/bionic/release-20210415/ubuntu-18.04-server-cloudimg-amd64.img) - after downwloading you'll need to rename it from `ubuntu-18.04-server-cloudimg-amd64.img` to `ubuntu-18.04-server-cloudimg-amd64-20210415.img`

Start it up, access the web console either inline or in its own tab(**), login as `ubuntu` and `ubuntu`, then do `ping 8.8.8.8`, then try to stop it with Ctrl-C.

For me: Ctrl-C is ignored.  I have to use a workaround, e.g. suspend with Ctrl-Z and then `kill %1`

![image](https://user-images.githubusercontent.com/44789/117266243-f4a2f580-ae4c-11eb-80a3-009a3e64b11e.png)

Do you see the same problem, or does Ctrl-C work for you?

Do you mind if I change the subject of this issue back again, since it's not related to copy-paste?

------
(*) This is assuming shift-reload is enough to pick it up, but I did try it in two different browsers
(**) if I choose a separate tab, this opens `http://x.x.x.x:3080/static/web-ui/server/1/project/1052ec96-de04-45fc-9fc2-dff8584cf303/nodes/aef754e1-ca9a-4d65-8c6a-0d14d15bd93f`

**Comment by piotrpekala7** [comment]
@candlerb 
Ok, now I understand. Thank you very much for your investigation. 

At the moment, we also don't understand why ctrl+c works in both xterm and demo, but doesn't work when embedded in an Angular component.

**Comment by candlerb** [comment]
Thanks to [this clue](https://stackoverflow.com/a/58999210/14241561) from Stackoverflow, I grepped for `attachCustomKeyEventHandler` in the gns3-web-ui source and I found these two snippets:

* [src/app/components/project-map/web-console/web-console.component.ts](https://github.com/GNS3/gns3-web-ui/blob/master/src/app/components/project-map/web-console/web-console.component.ts#L72-L79)
* [src/app/components/web-console-full-window/web-console-full-window.component.ts](https://github.com/GNS3/gns3-web-ui/blob/master/src/app/components/web-console-full-window/web-console-full-window.component.ts#L92-L99)

Both say:

```
    this.term.attachCustomKeyEventHandler((key: KeyboardEvent) => {
      if (key.code === 'KeyC' || key.code === 'KeyV') {
        if (key.ctrlKey) {
          return false;
        }
      }
      return true;
    });
```

They do appear to be specifically disabling ctrl-C and ctrl-V.  I'm guessing this was because of some unintended or unexpected interaction with copy-paste on some platforms?

**Comment by piotrpekala7** [comment]
Yes, exactly. So the user should be able to use Ctrl+C to copy and we don't want to disable this functionality, on the other hand we'd like to provide solution for your request. That's why we have problem with implementation in this area

**Comment by candlerb** [comment]
I found the xterm.js issue here: https://github.com/xtermjs/xterm.js/issues/2478

According to that issue, different platforms have ways of doing this, e.g. apparently ctrl-Insert and shift-Insert can be used on Linux.  

I note that when I use vanilla xterm.js, in addition to my platform-specific keys, Chrome gives me a context menu on right-click that lets me copy-paste:

![image](https://user-images.githubusercontent.com/44789/117300351-5ffebe80-ae71-11eb-9d89-91a2385c47ac.png)

However in GNS3's console, I don't get any menu when right-clicking.

Therefore I can think of a few ways to deal with this:

1. Don't intercept Ctrl-C/V, and let the user find their platform-specific keystrokes for copy/paste
2. Don't intercept Ctrl-C/V, and let the user activate their brower's context menu for copy/paste
3. Don't intercept Ctrl-C/V. but intercept some rarely-used key combinations (say Ctrl-Shift-C and Ctrl-Shift-V) and map them to Copy and Paste events.  This gives users a consistent way to do copy-paste regardless of the browser and OS type they are using

Or combine them all: intercept Ctrl-Shift-C/V, and don't block the context menu.  Of course, any platform-specific copy/paste will still work as well.

**Comment by piotrpekala7** [comment]
thanks for your propositions, we should discuss it, @grossmj could your share opinion about it? in the past we had a task to implement copy/paste with ctrl+c/ctrl+v

**Comment by piotrpekala7** [comment]
do you try with ctrl+break instead of ctrl+c?

**Comment by candlerb** [comment]
I've just tried it, and it does nothing.

However even if it did, I'd still want ctrl+c back.  This is for training labs; we want to train people to use the real keystrokes at the terminal.

**Comment by piotrpekala7** [comment]
Ok, understand, if @grossmj will agree with this change, I will apply it

**Comment by piotrpekala7** [comment]
what we can also do is to add additional option in settings to change this behavior, it will solve your problem and won't break any functionalities from last version

**Comment by grossmj** [comment]
> Or combine them all: intercept Ctrl-Shift-C/V, and don't block the context menu. Of course, any platform-specific copy/paste will still work as well.

Let's try to do this.

> what we can also do is to add additional option in settings to change this behavior, it will solve your problem and won't break any functionalities from last version

I am reluctant to add options in settings because then we end up with a bloated settings page. Let's consider it nonetheless if we can't properly implement the above solution.

**Comment by piotrpekala7** [comment]
fixed in https://github.com/GNS3/gns3-web-ui/commit/62c1f8b003e0e81c3ad0adecb97755f29c224fc6, I checked this changes in Chrome & FF on Windows platform

**Comment by candlerb** [comment]
Thank you!

I think there's another place where it needs changing: https://github.com/GNS3/gns3-web-ui/blob/master/src/app/components/web-console-full-window/web-console-full-window.component.ts#L94

I'm not sure whether Ctrl-Shift-C / Ctrl-Shift-V will actually perform a copy or paste on most OSes, but from my point of view I don't actually mind. As long as the context menu is there, students can always copy-paste using that.

**Comment by candlerb** [comment]
On an installed system I patched /usr/share/gns3/gns3-server/lib/python3.6/site-packages/gns3server/static/web-ui/index.html

I can confirm that the context menu now works inside a console, whilst GNS3 still takes it over for right-clicking on a node.  Cool!

**Comment by piotrpekala7** [comment]
applied also for console in full window https://github.com/GNS3/gns3-web-ui/commit/b51159513ff25b7651b33c4157d2eebf3eb3d43c

**Comment by piotrpekala7** [comment]
@candlerb thanks for confirmation!

**Comment by candlerb** [comment]
I found a minor issue with the context menu.

If select some text, right-click on a console window, and select Copy from the context menu, then the window becomes "stuck" to the mouse - that is, moving the mouse around also moves the console around, until I click again.

BUT:
* this is only in Chrome - Firefox is not affected
* it only applies to consoles embedded in the main GNS3 web UI, not when opened in a separate tab

I can certainly live with it :-)

**Comment by grossmj** [comment]
> If select some text, right-click on a console window, and select Copy from the context menu, then the window becomes "stuck" to the mouse - that is, moving the mouse around also moves the console around, until I click again.

@piotrpekala7 please can you check if we can do something about this. Thanks :+1:

**Comment by candlerb** [comment]
Regarding the change in commit 62c1f8b0 to [src/index.html](https://github.com/GNS3/gns3-web-ui/blob/master/src/index.html#L38) to avoid blocking the context menu:

1.  I see this change was reverted a few days later in abdd739f.  Was that intentional, or a merge problem?
2. I don't know the purpose of the commented-out `<!-- <body ... > -->` on the previous line, but I wonder if it also needs `oncontextmenu="return false;"` removing, for consistency?

**Comment by piotrpekala7** [comment]
@candlerb Yes, it was intentional because after previous change our context menu after selecting more than one node was unavailable
