### ISSUE TITLE
Missing console types for cloud nodes

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#1134]
The cloud node in the web-ui can only be configured with `telnet` and `none` console types:

![Screenshot from 2021-05-13 14-43-45](https://user-images.githubusercontent.com/4752614/118081085-d5323c80-b3f9-11eb-84b3-1d9354d584f7.png)

The following console types should be supported:

![Screenshot from 2021-05-13 14-43-17](https://user-images.githubusercontent.com/4752614/118081097-dbc0b400-b3f9-11eb-94a5-b5560fef26df.png)

**Comment by piotrpekala7** [comment]
fixed in https://github.com/GNS3/gns3-web-ui/commit/d290daed11b08b331b36c1c796331372002433ae

![cloudBug](https://user-images.githubusercontent.com/31202938/118110920-4c100b00-b3e3-11eb-9ea7-b5fee9848389.PNG)
