### ISSUE TITLE
 Improving the efficiency of calculating the position of the nodes when changing the scale for the project

### ISSUE THREAD

**Issue by SairusCZ** [GNS3/gns3-web-ui#1137]
I've noticed that when I try to drag&drop any object in the topology, the object does not follow the mouse cursor accurately when the topology is zoomed-in or zoomed-out. 

Steps to reproduce:
1)Zoom-out the topology by two clicks
2)Drag any object from left side of the screen to the right side of the screen. You should see that the object did not follow the mouse cursor.
3)When release the mouse button, the object is placed correctly under the mouse cursor. 

![dragging issue](https://user-images.githubusercontent.com/24818591/118401972-1039a780-b668-11eb-941c-c8712f51ac45.gif)

**Comment by piotrpekala7** [comment]
I checked that. Updating the node positions to those calculated on the basis of mouse movement events does not work efficiently enough to prevent this delay from occurring

**Comment by piotrpekala7** [comment]
@SairusCZ @grossmj 

Do you have any suggestions for improving efficiency in this field? The most important thing is the processing of events on the browser side, but maybe we are able to do something?

**Comment by piotrpekala7** [comment]
@SairusCZ 

Could you describe in what situations there is a decrease in efficiency in the calculation of the node position? Unfortunately, during zooming, we have to additionally process data about the position, maybe you have some idea how to reduce the impact of this negative effect? I suppose it is impossible to eliminate it completely

**Comment by piotrpekala7** [comment]
@SairusCZ 

?

**Comment by MichaelRadke** [comment]
@SairusCZ 
How do you want to skip this calculation?

@piotrpekala7 
IMO there is no option to reduce this effect in current implementation, you have to filter it https://github.com/GNS3/gns3-web-ui/blob/master/src/app/cartography/tools/moving-tool.ts#L51

**Comment by piotrpekala7** [comment]
@MichaelRadke 

maybe you have any propositions in this area?

**Comment by MichaelRadke** [comment]
I think in this implementation it can't be fixed

**Comment by piotrpekala7** [comment]
Ok, thanks
