### ISSUE TITLE
[2.2.21] Context menu offset with custom scene size

### ISSUE THREAD

**Issue by SairusCZ** [GNS3/gns3-web-ui#1138]
The context menu (right-click menu) shows at the edge of the browser when project has custom scene width and height.

Steps to reproduce:
1)Increase the scene width and height to 5000px under Menu>Project Settings>Edit Project.
2)Then right-click on any item in the topology and see that context menu does not appear next to the mouse cursor. (in some cases  page refresh is needed).

![context-menu-offset](https://user-images.githubusercontent.com/24818591/118402851-087c0200-b66c-11eb-82d5-6bf271fc650a.gif)

**Comment by piotrpekala7** [comment]
fixed in https://github.com/GNS3/gns3-web-ui/commit/2a96a6b60151d50d9e047f9dc4fdfd5af141565a

**Comment by piotrpekala7** [comment]
![projectWidth5000px](https://user-images.githubusercontent.com/31202938/118648309-8e21be00-b7e2-11eb-8e6b-73f106db77ac.PNG)
tested on Chrome 90.0.4430.93 and Firefox 88.0.1 for windows platform, all works as expected
