### ISSUE TITLE
[2.2.21] Add prompt before deletion object from map

### ISSUE THREAD

**Issue by SairusCZ** [GNS3/gns3-web-ui#1140]
I've just accidentally deleted my entire 60-node topology as I thought I was in different project. Luckily I have a backup, but the web-ui should really ask for confirmation before node deletion. 

Steps to reproduce:
1)Open any topology (not important one)
2)Press CTRL+A to select all nodes
3)Press Delete key and the entire topology will be gone without any prompt/warning. 

I would expect the same behavior as in the QT client where user is asked for confirmation (example bellow).
![ksnip_20210516-175200](https://user-images.githubusercontent.com/24818591/118403761-35caaf00-b670-11eb-8531-c00c0a423c87.png)

**Comment by piotrpekala7** [comment]
added in https://github.com/GNS3/gns3-web-ui/commit/1d5bbb58f9a781774c33cdcbee50b8168546a6e1

**Comment by grossmj** [comment]
I tested and could still delete the nodes without any question with the delete key.

**Comment by piotrpekala7** [comment]
![screenshot](https://user-images.githubusercontent.com/31202938/118648089-57e43e80-b7e2-11eb-9176-1d58f4e13bf2.PNG)
Sorry, I added dialog only after deletion from context menu, fixed in https://github.com/GNS3/gns3-web-ui/commit/2a96a6b60151d50d9e047f9dc4fdfd5af141565a
