### ISSUE TITLE
Add logged in as user information

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#1143]
In CML, we can copy the JWT token and see the "logged in as" information.

![Screenshot from 2021-05-17 10-20-35](https://user-images.githubusercontent.com/4752614/118419030-03fe2a80-b6fa-11eb-8693-83ede30a4bad.png).

Clicking on `Copy JWT` copies the token to the clipboard which is useful for manual requests outside the web Ui for debugging/experimenting.

Maybe we could push this further and have an `User info` entry in the top right menu which would show a page containing information about the current logged in user like the username, full name and the email address as well as a button to copy the JWT?

![Screenshot from 2021-05-17 10-27-58](https://user-images.githubusercontent.com/4752614/118419591-a1a62980-b6fb-11eb-93cf-3f886f6e7e6b.png)

**Comment by piotrpekala7** [comment]
added in https://github.com/GNS3/gns3-web-ui/commit/823e9a4b5904a540c7df71e5933d90eb814073e1

**Comment by grossmj** [comment]
Looks good, just the title should be "Logged in user info". Thanks :+1:

**Comment by piotrpekala7** [comment]
![loggedIn](https://user-images.githubusercontent.com/31202938/118672640-b2889500-b7f8-11eb-8727-e07473459225.PNG)
fixed
