### ISSUE TITLE
Change "No Thanks" text to "Cancel" on "Add Server"

### ISSUE THREAD

**Issue by eantowne** [GNS3/gns3-web-ui#1144]
Currently, when you:

- Click "Servers"
- Click "Add Server"

The two button options at the bottom of the "Add Server" dialog display "No Thanks" and "Add".

The text for "No Thanks" should be changed to "Cancel", as "No Thanks" does not fit the context of the dialog, and the action being performed.
![Add-Server-Window](https://user-images.githubusercontent.com/66289315/118831273-4142f380-b885-11eb-8af5-bf1f41f083ea.png)

**Comment by piotrpekala7** [comment]
@eantowne 
Do you have any suggestions to other dialogs?

**Comment by eantowne** [comment]
I am still working through all of the Web GUI. As I find things, I will submit an issue.

**Comment by piotrpekala7** [comment]
@eantowne  We'll be grateful! Here is information how to run web UI locally and create pull request to our repository https://docs.gns3.com/docs/contribute/how-to-debug-web-ui-guide.

**Comment by piotrpekala7** [comment]
This is link to server dialog -> https://github.com/GNS3/gns3-web-ui/blob/master/src/app/components/servers/add-server-dialog/add-server-dialog.component.html#L52 <- you should change this line when it comes to this issue

**Comment by eantowne** [comment]
So, don't submit issues, just create pull requests ;)

It will probably be a couple of days before I can get to the point where I am doing code modification and submitting pull requests, as this is not something I was planning on. However I will take a look and see if it is feasible with my schedule.

**Comment by piotrpekala7** [comment]
Not really ;-) create pull requests, create issues, ask about implementation, ask on community page - we'd like to have active users, we are happy when they propose what to do, also we really appreciate any pull request

**Comment by eantowne** [comment]
No worries, Like I said, give me a few days to sort some stuff out and get a dev environment setup. I am a moderator on the community page, so already WAY to involved on that side ;)

**Comment by ean-towne** [comment]
@piotrpekala7 
Need to be able to create a branch in order to create the pull request.

**Comment by piotrpekala7** [comment]
I found the same issue in snapshot dialog

**Comment by piotrpekala7** [comment]
fixed in https://github.com/GNS3/gns3-web-ui/commit/e37bdc616279f8fcaa7c53ef9876755e64d31e1f
