### ISSUE TITLE
Buttons on project page

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#1146]
I noticed that the button positions on the project page have changed recently.

This is with the latest release:

![Screenshot from 2021-05-20 12-38-36](https://user-images.githubusercontent.com/4752614/118913414-9441a700-b968-11eb-9cf7-0ee675e6471b.png)

This is the dev version (v2.2.22dev):

![Screenshot from 2021-05-20 12-39-26](https://user-images.githubusercontent.com/4752614/118913420-97d52e00-b968-11eb-939e-404835d5b96e.png)

This is with `node.js lts/fermium -> v14.17.0`.

**Comment by piotrpekala7** [comment]
Yes, after upgrading packages
I suppose styles in angular material changed

**Comment by piotrpekala7** [comment]
![projectsPage](https://user-images.githubusercontent.com/31202938/118961884-18922b00-b965-11eb-9129-46360b67c2cc.PNG)
fixed
