### ISSUE TITLE
HTTPS reverse proxy on default port 443: web-ui makes Ajax requests to HTTPS port 80

### ISSUE THREAD

**Issue by candlerb** [GNS3/gns3-web-ui#1153]
## How to reproduce

* gns3-server 2.2.21 running on Linux server
* Apache reverse proxy listening on default HTTPS port 443 (port 80 also open for http)
* Apache configured to proxy everything to gns3 on 127.0.0.1:3080
* Connect with browser to `https://gns3.example.com`

## What the user sees

The gns3 web UI comes up but the project list is empty.

Browser debug console shows that the API is trying to make a request to `https://gns3.example.com:80/v2/projects`.  That is, a **HTTPS** request to port **80** !!

![image](https://user-images.githubusercontent.com/44789/119814685-995fa280-bee2-11eb-8e64-a5180cefa4cd.png)
![image](https://user-images.githubusercontent.com/44789/119814857-cdd35e80-bee2-11eb-8b63-7dc02ed58cb6.png)

Tcpdump on the `lo` interface shows the proxy is adding these headers:

```
Host: gns3.example.com
...
X-Forwarded-For: <client-IP-address>
X-Forwarded-Proto: https
```

## Why this is required

My aim is to perform additional authentication on the reverse proxy.  I want to expose it on the standard HTTPS port because (a) this is the most user-friendly experience (no need to type a port number in the URL), and (b) ultimately this will run behind a kubernetes ingress on the standard HTTPS port.

## Experiment 1: non-standard port

It *does* work if I make the proxy listen on a non-standard port.  e.g. I configure Apache to listen on port 3443 for https, and the client points to `https://gns3.example.com:3443`.  In this case, the Ajax request is made to `https:/gns3.example.com:3443/v2/projects` and everything works fine; the project list comes up.

Tcpdump in this case shows the proxy adding these headers:

```
Host: gns3.example.com:3443
...
Forwarded-For: <client-IP-address>
X-Forwarded-Proto: https
```

## Experiment 2: additional headers

In an attempt to work around the problem, I modified the proxy to include explicit port numbers:

```
        RequestHeader set Host "gns3.example.com:443"
        RequestHeader set X-Forwarded-Port 443
        RequestHeader set X-Forwarded-Host "gns3.example.com:443"
```

Tcpdump shows that these are working:

```
Host: gns3.example.com:443
...
X-Forwarded-For: <client-IP-address>
X-Forwarded-Proto: https
X-Forwarded-Port: 443
X-Forwarded-Host: gns3.example.com:443
```

However the problem still exists: the Ajax call is being made to `https://gns3.example.com:80/v2/projects`

## Analysis

Somewhere in the Javascript, ":80" is being added as the port number explicitly.  I think it could be in [bundled-server-finder.component.ts](https://github.com/GNS3/gns3-web-ui/blob/master/src/app/components/bundled-server-finder/bundled-server-finder.component.ts#L24)

I tried patching this to 443 in the minified `main.2f0314a517dded67879c.js` ~~but it didn't fix the problem; maybe there's somewhere else as well?~~ and this fixes the problem if you start from a fresh server listing.

I can see that document.location.port is empty:

```
> document.location.port
< ""
```

Possible solutions:

* If the port is empty, the URLs generated by the web-ui should also omit the port (and colon)
* If that's not possible, then it could at least check for the `X-Forwarded-Port` header, which I can set on the proxy.
* Perhaps the best solution of all would be for the "local" server to generate URLs without any scheme or host at all, e.g. just `/v2/projects`.  That would involve some special treatment for the local server however.

**Comment by candlerb** [comment]
Update: the patch to set default port 443 worked, if I opened an incognito window and went back to the top level. I believe this forces it to re-add the local server.

I notice that [getLocalServer](https://github.com/GNS3/gns3-web-ui/blob/master/src/app/services/server.service.ts#L162) uses `location.protocol`, and that is being set correctly:

![image](https://user-images.githubusercontent.com/44789/119821840-ee9fb200-beea-11eb-978b-01e3218aa5d4.png)

So a very simple solution would be to default the port to 443 if `location.protocol == "https:"`

**Comment by piotrpekala7** [comment]
this should fix your issue https://github.com/GNS3/gns3-web-ui/commit/6faba7c4ecd50a4328bbcda7407a3831dc91cf30

**Comment by candlerb** [comment]
`location.protocol`: should this say `this.document.location.protocol` ?

**Comment by piotrpekala7** [comment]
yes, thanks, fixed in https://github.com/GNS3/gns3-web-ui/commit/092fe5991b96b65e3e05b61ee9145bc91960c04e
