### ISSUE TITLE
web-ui "servers" page tries to access API on localhost

### ISSUE THREAD

**Issue by candlerb** [GNS3/gns3-web-ui#1154]
This is a minor issue, but I thought I'd report it anyway.

I have the web UI running on https, and I have the developer console open.

When I hit the "servers" page, i.e. `https://xxxxx/static/web-ui/servers`, I see the server listed as name "local" with the correct hostname.  However the developer console also shows:

![image](https://user-images.githubusercontent.com/44789/119832049-bea9dc00-bef5-11eb-9f1d-3a5bb85370de.png)

It doesn't cause any problems as far as I can see: I can still click on the "local" server in the listing, and get to the projects page.

It just seems odd that the web UI is making requests to 127.0.0.1, since those are almost certain to fail (unless you happen to be running a Linux desktop with browser and gns3 server all together on the same machine)

**Comment by MichaelRadke** [comment]
@candlerb it tries to access localhost cause that's how their server discovery works... https://github.com/GNS3/gns3-web-ui/blob/master/src/app/components/servers/server-discovery/server-discovery.component.ts 
this is not a bug, take a look at the code xd

**Comment by candlerb** [comment]
OK, so it explicitly tries to probe `127.0.0.1:3080`.  This must be in addition to `<hostname>:<port>` from the `document.location`, i.e. where the GNS3 web UI was served from.

I hadn't considered that the GNS3 web UI might be run as a standalone Electron app (not via a web browser), and I guess that must be what the 127.0.0.1:3080 default is for.

Thanks for your response!
