### ISSUE TITLE
Hide password on login page

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#1158]
The password should be hidden with '*' when being typed on the login page.

![Screenshot from 2021-06-02 14-54-24](https://user-images.githubusercontent.com/4752614/120452984-c83db300-c3d1-11eb-8bd6-0efcfe20ffa2.png)

**Comment by piotrpekala7** [comment]
fixed in https://github.com/GNS3/gns3-web-ui/commit/bac604724711de641dd47476931f9f5728cbc645
