### ISSUE TITLE
Change link style

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#1163]
Support to change link styles has recently been added in the desktop Ui and server: https://github.com/GNS3/gns3-gui/issues/2461#issuecomment-855391763

We need to have the same in the web-ui. This is similar editing the style of drawings:

![Screenshot from 2021-06-07 14-37-09](https://user-images.githubusercontent.com/4752614/120961976-ff2f1280-c79d-11eb-8007-6fbb44f1270e.png)

Excepting that we have only 3 properties: `color`, `width` and `type`.

For example:

```
"link_style": {
   "color": "#75507b",
   "type": 1,
   "width": 4
}
```

**Comment by piotrpekala7** [comment]
I created pr with this option https://github.com/GNS3/gns3-web-ui/pull/1171, however I can't find why redrawing links after changing style doesn't work correctly - we're rendering old data

**Comment by piotrpekala7** [comment]
@grossmj 
I suppose this task won't be closed in this release, unfortunately I didn't find the way to render changed single link again

**Comment by piotrpekala7** [comment]
still I hadn't fix this issue on pull request https://github.com/GNS3/gns3-web-ui/pull/1171 so I have to change milestone until we'll find a way how to make it working

**Comment by grossmj** [comment]
We can change the link style however the full page must be reloaded. This is acceptable for now, maybe we will have a solution some day.
