### ISSUE TITLE
Contextual menu position

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#1164]
I noticed an issue in GNS3 Web UI © 2020 - v2.2.22 with both Chrome and Firefox.

The contextual menu seems far away when you right click on a node:

![Screenshot from 2021-06-07 14-43-06](https://user-images.githubusercontent.com/4752614/120962467-f2f78500-c79e-11eb-834f-ebbbc9c3a5c7.png)

Same with a link:

![Screenshot from 2021-06-07 14-43-25](https://user-images.githubusercontent.com/4752614/120962478-f7bc3900-c79e-11eb-9120-5b2bea07f72e.png)

**Comment by piotrpekala7** [comment]
potentially it's broken after this changes https://github.com/GNS3/gns3-web-ui/commit/2a96a6b60151d50d9e047f9dc4fdfd5af141565a

**Comment by piotrpekala7** [comment]
I'm checking it

**Comment by piotrpekala7** [comment]
![14 06](https://user-images.githubusercontent.com/31202938/121906637-96aadd00-cd2b-11eb-890e-3d9a01b3c971.PNG)

it seems that it works properly on Windows versions of Chrome and FF browsers, I'll try to find more info

**Comment by piotrpekala7** [comment]
I revert changes on this branch https://github.com/GNS3/gns3-web-ui/tree/Contextual-menu-position, let me know if you have issues

**Comment by piotrpekala7** [comment]
I checked in FF & Chrome, should be fine
merged in https://github.com/GNS3/gns3-web-ui/pull/1173
