### ISSUE TITLE
Error from server while connecting to PCAP stream: This link has no active packet capture

### ISSUE THREAD

**Issue by 25139581** [GNS3/gns3-web-ui#1174]
Hi guys,

I receive the following error message when starting a PCAP from the WebUI. 

"Error from server while connectining to PCAP stream: This link has no active packet capture"

Console Error:

Error while sending command 'bridge start_capture QEMU-215ec0b2-0f97-4c99-be93-00a20bce9a16-0 "/home/simon/GNS3/projects/42895c72-899d-471f-a69c-68f9c0c7484c/project-files/captures/CiscoIOSv15.6(2)T-1_Gi0/0_to_CiscoIOSv15.6(2)T-2_Gi0/0"': packet capture could not be started on bridge 'QEMU-215ec0b2-0f97-4c99-be93-00a20bce9a16-0': uBridge version 0.9.18 running with libpcap version 1.9.1 (with TPACKET_V3) Hypervisor TCP control server started (IP 192.168.2.199 port 37495). UDP tunnel connecting from local port 10003 to IPv4 address 127.0.0.1 on port 10002 UDP tunnel connecting from local port 10000 to IPv4 address 192.168.2.199 on port 10001 Source NIO listener thread for QEMU-215ec0b2-0f97-4c99-be93-00a20bce9a16-0 has started Destination NIO listener thread for QEMU-215ec0b2-0f97-4c99-be93-00a20bce9a16-0 has started pcap_dump_open failure (file /home/simon/GNS3/projects/42895c72-899d-471f-a69c-68f9c0c7484c/project-files/captures/CiscoIOSv15.6(2)T-1_Gi0/0_to_CiscoIOSv15.6(2)T-2_Gi0/0)

### Screenshot of Error ###
![PCAP error](https://user-images.githubusercontent.com/70966868/124349829-2801c680-dbe9-11eb-8bb7-99cdced12d2d.png)

If I initiate a packet capture in the GNS3 Client software first & close wireshark, then switch to the Web UI and start the process again it works fine.

I am running GNS3 Server / Client / WebUI v2.2.22 natively on Linux Mint 20.1 Cinammon but have experienced the same error on earlier versions of the software

Thanks for any help and all your hard work :)

**Comment by piotrpekala7** [comment]
@25139581 
we haven't find any solution yet, generally this dialog after clicking ok calls simple function in links service

```
startCaptureOnLink(server: Server, link: Link, settings: CapturingSettings) {
    return this.httpServer.post(server, `/projects/${link.project_id}/links/${link.link_id}/start_capture`, settings);
}
```

**Comment by 25139581** [comment]
Hi, just to confirm this is now working in latest version gns3 2.2.33
