### ISSUE TITLE
Option to disable usage tracking

### ISSUE THREAD

**Issue by bluecmd** [GNS3/gns3-web-ui#1184]
Hello,

As a user I find the use of user tracking invasive. Can you please offer a way to opt off it?
I see it was added in https://github.com/GNS3/gns3-web-ui/issues/634 and I doubt a lot of people realize that it was added and that their usage of GNS3 is being tracked by a third party.

Thanks for your consideration

**Comment by piotrpekala7** [comment]
Hi @bluecmd 
Thanks for request, we'll consider it. Actually we don't track many events https://github.com/GNS3/gns3-web-ui/blob/master/src/app/services/google-analytics.service.ts#L7

**Comment by grossmj** [comment]
We have this option in the desktop interface (send anonymous usage statistics), we should have the same for the web ui.

![Screenshot from 2021-08-06 11-00-51](https://user-images.githubusercontent.com/4752614/128442309-6af3e0fb-5bd8-4b3b-beaa-00b271d24059.png)

In the future we plan to have opt-in by default like most other software.

**Comment by piotrpekala7** [comment]
added in https://github.com/GNS3/gns3-web-ui/commit/1619c3ec05f435a63a379c644f17247feadfc21d

**Comment by piotrpekala7** [comment]
@bluecmd please check after our next release

**Comment by bluecmd** [comment]
Thanks! Much appreciated 🙏
