### ISSUE TITLE
Mouse hover on node quick menu.

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#1186]
CML has a quick menu for Start/Stop, Link, Console/VNC that appears as a small ring around the node when mouse hovering on the node. It would be nice to have something similar in the web-ui.

https://user-images.githubusercontent.com/4752614/128840723-cc86618a-83e3-47c0-aee6-0261db724180.mp4

**Comment by eantowne** [comment]
Junipers vLAB also has a similar functionality/presentation, so I think the "Where the idea came from" issue is not relevant. ;)

**Comment by grossmj** [comment]
> Junipers vLAB also has a similar.

I should take a screenshot ;)

**Comment by eantowne** [comment]
Done ;)
![Juniper-vLAB-Mouse-Hover](https://user-images.githubusercontent.com/66289315/131829593-9eb16dcc-9ae4-40f1-896c-c661ed9c1693.png)

**Comment by grossmj** [comment]
Also, we can see it in this video: https://youtu.be/_WcdcFjq7jQ?t=30
