### ISSUE TITLE
System stats should be accessible from the server page.

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#1192]
As discussed in https://github.com/GNS3/gns3-web-ui/issues/1191#issuecomment-911300413 system stats should be accessible from the server page.

**Comment by piotrpekala7** [comment]
added in https://github.com/GNS3/gns3-web-ui/commit/b1aba6041066817dbdcab7194eb6754461a20292

**Comment by piotrpekala7** [comment]
![Capture](https://user-images.githubusercontent.com/31202938/133167980-3df2d488-05eb-4126-8d1d-ca0671d247c1.PNG)

**Comment by piotrpekala7** [comment]
@grossmj please confirm if it's ok

**Comment by grossmj** [comment]
Looks good, thanks 👍
