### ISSUE TITLE
Bugs with themes

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#1195]
A few bugs around themes have been reported in https://gns3.com/community/blog/gns3-2-2-25-released

1. When we change the UI preference settings from DARK to LIGHT THEME - Node Description is invisible.
2. Until unless Cache is cleared Theme is not applied.

![Light Theme](https://user-images.githubusercontent.com/4752614/134478988-c1c34497-f360-4968-aa33-1e21f03d941a.JPG)

**Comment by piotrpekala7** [comment]
![themingFixed](https://user-images.githubusercontent.com/31202938/136188478-2978b4a6-80c1-4bfc-9e58-d783322c2cf5.PNG)

**Comment by piotrpekala7** [comment]
fixed in https://github.com/GNS3/gns3-web-ui/commit/357e478fb819e0149ce1ce29108b64c6660da31a,
