### ISSUE TITLE
Web UI not prompting for NXOS BIOS when importing NXOS 9000v

### ISSUE THREAD

**Issue by nicholas-heaton** [GNS3/gns3-web-ui#1196]
Issue: Web UI not prompting for NXOS BIOS when importing NXOS 9000v

Expectation: UI to prompt for BIOS

What happens: The menu only prompts for the NXOS qcow2 image, and allows you to successfully import the appliance but doing so without the BIOS results in no console output when booting as it's a required component.

The problem with screenshots has been documented at https://www.gns3.com/initiatives/nxos-9000v-esxi-gns3-vm-console-issue-solution

**Comment by piotrpekala7** [comment]
![biosUpdate](https://user-images.githubusercontent.com/31202938/145093577-e9cefd5f-336b-4976-afd4-d1b35e92d30d.PNG)
![biosUpdate2](https://user-images.githubusercontent.com/31202938/145093582-3bd74c9c-3bc9-43a4-b5df-4c40cd2f1d22.PNG)
fixed
