### ISSUE TITLE
Pass JWT token as query string to use websocket endpoints

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#1204]
I recently secured the websocket endpoints in the server: https://github.com/GNS3/gns3-server/pull/1992

The JWT token for the current user must now be passed as a query string (named `token`) when connecting to any websocket endpoint.

For example:

* `ws://localhost:3080/v3/notifications?token=XXXXXXX`
* `ws://localhost:3080/v3/projects/186e50d5-e861-4d44-a6bc-244bfd916a74/notifications?token=XXXXXXX`

A JSON message is returned in case of error, for example:

```
{"action": "log.error", "event": {"message": f"Could not authenticate while connecting to WebSocket: could not validate credentials"}}
```

Then the web socket is immediately closed by the server.

Please let me know if you have questions.

**Comment by piotrpekala7** [comment]
added in https://github.com/GNS3/gns3-web-ui/commit/60a9e45e4a49f6bd5b50a62c040c91a60bd91c0c

**Comment by grossmj** [comment]
Working, thanks 👍
