### ISSUE TITLE
Cannot move more than 1 node at once on workspace

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#1212]
I remember we used to be able to move more than one node at once on the workspace (like in the desktop Ui)

![Screenshot from 2021-11-12 16-47-03](https://user-images.githubusercontent.com/4752614/141419620-ce331ae1-c0e9-47c2-b2e1-fae375edd3b5.png)

It seems to be broken now.

**Comment by piotrpekala7** [comment]
verified on master branch 01.12.21

**Comment by grossmj** [comment]
Confirmed, thanks.

**Comment by grossmj** [comment]
I was testing with v2.2.28 and it does not seem to work anymore. I cannot select multiple nodes and more them with the mouse. It works if I do CTRL+A first.

**Comment by piotrpekala7** [comment]
https://user-images.githubusercontent.com/31202938/147769582-f99cf989-6ddd-41b0-9c1b-1b7b2735cc88.mp4

checked on latest Chrome, Firefox and Edge, I'm not able to reproduce this bug on my environment and have no idea what could be the reason

**Comment by grossmj** [comment]
Ok no worries, let me test again. Maybe I was on the wrong branch?

**Comment by piotrpekala7** [comment]
or we have an issue on particular browser on Linux platform...

**Comment by cristian-ciobanu** [comment]
I just did a quick test on both Chrome and Firefox running on Linux and indeed the issue can be reproduced.

I added several nodes on the topology. Then I have selected all of them using the mouse but when I try to move them, all other nodes lose the selection and I can move only the active node.

When using Ctrl + A as @grossmj mentioned dragging works fine.

Also as a side note the web-ui does not allow to create multiple instances of the same node when pressing Shift key as it works in the GNS3 GUI.
I do not know if this is a bug or it's not implemented yet.

**Comment by piotrpekala7** [comment]
> I just did a quick test on both Chrome and Firefox running on Linux and indeed the issue can be reproduced.
> 
> I added several nodes on the topology. Then I have selected all of them using the mouse but when I try to move them, all other nodes lose the selection and I can move only the active node.
> 
> When using Ctrl + A as @grossmj mentioned dragging works fine.

@cristian-ciobanu do you see any issues in implementation of SelectionManager that can cause issues between browser on different platforms?

**Comment by piotrpekala7** [comment]
> Also as a side note the web-ui does not allow to create multiple instances of the same node when pressing Shift key as it works in the GNS3 GUI. I do not know if this is a bug or it's not implemented yet.

no, we haven't added such functionality in web UI yet

**Comment by cristian-ciobanu** [comment]
> @cristian-ciobanu do you see any issues in implementation of SelectionManager https://github.com/GNS3/gns3-web-ui/blob/master/src/app/cartography/managers/selection-manager.ts that can cause issues between browser on different platforms?

Sorry I'm not very skilled in TypeScript. I have only some basic programming language knowledge and I cannot say if there are issues or not in that SelectionManager class.

**Comment by grossmj** [comment]
Tested on Chrome and Firefox. I was able to select nodes and move them. I think the problem is fixed (hopefully).
