### ISSUE TITLE
Contextual menu issues

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#1213]
When selecting multiple nodes and I do a right click on the workspace:

![Screenshot from 2021-11-12 17-05-52](https://user-images.githubusercontent.com/4752614/141422058-b16f0a58-660f-4fc3-9a45-b22e917c4b7e.png)

When zooming out or in and then right click on a node (PC4 in this example), the menu is far away from the node, sometimes even at the bottom of the workspace.

![Screenshot from 2021-11-12 17-06-23](https://user-images.githubusercontent.com/4752614/141422140-c81c77a5-d90a-42d6-9cc3-a5e0bce2be1d.png)

**Comment by piotrpekala7** [comment]
when it comes to context menu position it's sth similar to https://github.com/GNS3/gns3-web-ui/issues/1139, we don't calculate node & also contextual menu position after zoom in/out correctly

**Comment by piotrpekala7** [comment]
![01 12](https://user-images.githubusercontent.com/31202938/144323175-437a486a-63a6-4696-8a82-ca322df76258.PNG)
apart from zoom position, contextual menu for more than node works as expected, tested on main branch from 01.12

**Comment by grossmj** [comment]
It works now, thanks.
