### ISSUE TITLE
docker container - configure - start command: empty value results in "Fill all required fields"

### ISSUE THREAD

**Issue by jnatschev** [GNS3/gns3-web-ui#1214]
VMware Fusion: 12.2.0
GNS3 VM: 2.2.27

1. i've added a docker container to a topology via the gns3-web-ui.
2. i right click on the container object and select "Configure" and the "Configurator" window opens up.
3. i scroll down and select "Edit network configuration" where i make the necessary changes relative to my topology.
4. i click "Apply".
5. a message appears at the bottom of the gns3-web-ui window "Fill all required fields".
6. i scroll up to find the "Start command" field red.
7. i don't know what to do because the same topology accessed using the gns3-gui doesn't behave like the gns3-web-ui.
8. i have a think and arrive at a question: "What will adding a 'space' do?".
9. i add a "space" in the "Start command" field.
10. the red colour disappears.
11. i click "Apply".
12. a message appears at the bottom of the gns3-web-ui window: "Node <node_name> updated".
13. start the container.
14. all works.

is this, what i'm calling an issue, as intended?

**Comment by piotrpekala7** [comment]
Ok, so it looks like web UI doesn't accept empty start command field but it accepts string with one space... definetely should be changed. @jnatschev do you have any ideas for validation of input for start command? if so please add here, I would be grateful

**Comment by piotrpekala7** [comment]
@jnatschev ?

**Comment by jnatschev** [comment]
i'm not sure how to answer because i don't the purpose of the "Start command" field and the possible values associated with the field. so my question back to you is, how does the gns3-gui do it? the reason for the question is that the gns3-gui doesn't behave like the gns3-web-ui. the gns3-ui allows no value for the "Start command".

**Comment by grossmj** [comment]
Indeed, the start command can be empty and shouldn't be required.

![Screenshot from 2021-12-08 00-45-52](https://user-images.githubusercontent.com/4752614/145045389-bf0031ae-164b-4066-a7f8-e119fe927e97.png)

**Comment by piotrpekala7** [comment]
![dockerConf](https://user-images.githubusercontent.com/31202938/145051491-fece231e-1fde-4ae5-82cf-3ab7b7804db6.PNG)
fixed
@jnatschev please check next release
