### ISSUE TITLE
How can I enable https?

### ISSUE THREAD

**Issue by mortiz-code** [GNS3/gns3-web-ui#1215]
Hello guys.
How can I enable HTTPS server for GNS3 Web UI?

My gns3_server.conf:
```
; Option to enable SSL encryption
ssl = True
certfile=/home/gns3/ssl/gns3.cert
certkey=/home/gns3/ssl/gns3.key
```

I did a reboot but it is still on HTTP:
![image](https://user-images.githubusercontent.com/62490642/143587277-256c9a89-d3eb-4d35-be67-de8ddf9d9373.png)

Thanks,

**Comment by piotrpekala7** [comment]
When you're adding server on servers page there's protocol field, choose HTTPS instead of HTTP. 
Regards

**Comment by diniz2010** [comment]
E quanto ao GNS3 VM, como fazer para que a Web-ui seja executada no navegador via https?

**Comment by scls19fr** [comment]
I only see in doc 
https://docs.gns3.com/docs/using-gns3/administration/gns3-server-configuration-file
https://docs.gns3.com/docs/using-gns3/administration/client-server-ssl-encryption

    Caution
    It’s no longer supported and will be removed in GNS3 2.1. We recommend using a VPN in order to protect all communications.

**Comment by grossmj** [comment]
I remember we added it back so this https://docs.gns3.com/docs/using-gns3/administration/client-server-ssl-encryption/ should work. Need to confirm and remember that caution message.

**Comment by grossmj** [comment]
I've updated the doc.

Also, please note the SSL configuration will be easier in GNS3 v3 when using the GNS3 VM.

![Image](https://github.com/user-attachments/assets/36435cd7-0ea5-42f6-936a-f2aae0c32820)
