### ISSUE TITLE
Remember topology/servers window position

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#1218]
It would be nice if the position of the topology/servers window was remembered when clicking on the toggle button on top right corner.

![Screenshot from 2021-12-08 12-36-59](https://user-images.githubusercontent.com/4752614/145135730-2b0955d5-7bff-48d7-8ea2-9977194bce2e.png)

**Comment by piotrpekala7** [comment]
implementation on branch https://github.com/GNS3/gns3-web-ui/tree/Remember-topology/servers-window-position
