### ISSUE TITLE
Mouse pointer

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#1219]
It would be nice to have a mouse pointer similar to the one on the screenshot for the draw a line, ellipse, rectangle as well as add a note actions.

![pointer](https://user-images.githubusercontent.com/4752614/145148605-c60792d8-7891-4f2d-b228-f246f0d06f74.png)

**Comment by piotrpekala7** [comment]
@grossmj implementation on branch https://github.com/GNS3/gns3-web-ui/tree/Mouse-pointer-%231219
