### ISSUE TITLE
CTRL+A and delete doesn't have any effect on shape objects

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#1221]
Some object types are not deleted if I press on CTRL+A and then the DELETE key

![Screenshot from 2021-12-09 15-29-42](https://user-images.githubusercontent.com/4752614/145339030-8cd73e02-2801-4f9a-9c65-28ba25fe00c5.png)

![Screenshot from 2021-12-09 15-30-17](https://user-images.githubusercontent.com/4752614/145339044-b1f12b1f-6597-466e-a8b2-a31473cb06cd.png)

**Comment by piotrpekala7** [comment]
fixed in https://github.com/GNS3/gns3-web-ui/commit/56554f6d0c1d4a08acd7467b997fb590af548bc2, verified on main branch
