### ISSUE TITLE
Should not see "Back to project" if failed to open one

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#1222]
I tried to open a project (named TEST) but there was an error

![Screenshot from 2021-12-09 16-00-40](https://user-images.githubusercontent.com/4752614/145340117-cd4586c5-a0e2-423c-9a5c-dee0ee742fcc.png)

According to the web-ui, the project is opened with the button "Back to project" displayed. In the list, "TEST" project is correctly marked as not opened.

![Screenshot from 2021-12-09 16-00-58](https://user-images.githubusercontent.com/4752614/145340105-59b43d57-d274-4fbc-9a35-51293510a7e9.png)

**Comment by piotrpekala7** [comment]
fixed in https://github.com/GNS3/gns3-web-ui/commit/f8cc65453991b5e96a012407d5497423503b106f. tested on master branch
