### ISSUE TITLE
Handle expired JWT tokens

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#1226]
JWT tokens can expire. The web-ui should handle this and automatically try to get a new JWT token using the previously provided credentials.

To test, edit `~/.config/GNS3/3.0/gns3_server.conf` and add the following setting for tokens to expire after 1 minute

```
[Controller]
jwt_access_token_expire_minutes = 1
```

Authenticate, do some actions and after 1 minute you should see this error:

![Screenshot from 2021-12-28 11-47-17](https://user-images.githubusercontent.com/4752614/147518235-49f087d7-64a4-4edb-89a9-28fa36269e86.png)

**Comment by grossmj** [comment]
Similar to the above:

1. Add a new server in the web-ui
2. Do some work and the token expires (tokens expire every 24 hours by default but this will likely be lowered in the future)
3. Open the web-ui and try to use the previously added server
4. You get the `Could not validate credentials` error without being able to provide credentials again. You must delete and add the server again.

**Comment by piotrpekala7** [comment]
@grossmj we haven't ever created implementation for refreshing tokens so I added task for that https://github.com/GNS3/gns3-web-ui/issues/1228, I'm not able to improve anything in current implementation, it needs new mechanism for that
