### ISSUE TITLE
Refresh JWT token after expiration

### ISSUE THREAD

**Issue by piotrpekala7** [GNS3/gns3-web-ui#1228]
JWT token needs refresh after expiration

**Comment by piotrpekala7** [comment]
ref. https://github.com/GNS3/gns3-web-ui/issues/1226

**Comment by piotrpekala7** [comment]
@grossmj 
I tried to prepare implementation for this case in http error handler on branch https://github.com/GNS3/gns3-web-ui/tree/Refresh-JWT-token-after-expiration, unfortunately it causes circular dependencies in the project and I don't know how I can update server properties there

**Comment by piotrpekala7** [comment]
I changed approach to add this option & created pull request with solution https://github.com/GNS3/gns3-web-ui/pull/1246

**Comment by grossmj** [comment]
Does not seem to work properly, please see https://github.com/GNS3/gns3-web-ui/issues/1268

**Comment by grossmj** [comment]
@rajnikantsolarwinds here is how to test using the GNS3 VM

1. Start the GNS3 VM and select `OK`

![Screenshot from 2022-05-13 19-04-43](https://user-images.githubusercontent.com/4752614/168324932-c0d201d2-030c-4690-af5b-4f5096743d15.png)

2. Select `Channel`

![Screenshot from 2022-05-13 19-05-00](https://user-images.githubusercontent.com/4752614/168324971-e05a9cea-0b88-4abe-8dcc-b59320fd33c4.png)

3. Choose `Continue`

![Screenshot from 2022-05-13 19-05-19](https://user-images.githubusercontent.com/4752614/168325008-9126d122-c427-4503-8802-e8eb658c6697.png)

4. Choose `3.0dev`, the VM will upgrade and download the development version for 3.0 (this could take a while depending on your connection speed)

![Screenshot from 2022-05-13 19-05-26](https://user-images.githubusercontent.com/4752614/168325038-e8e6bdde-1886-4a5c-95ec-3cdc3ffbf83c.png)

5. Once the upgrade finished, the VM will reboot and you should see the GNS3 version is 3.0

![Screenshot from 2022-05-13 19-09-49](https://user-images.githubusercontent.com/4752614/168325083-ff040bdc-b493-492c-bac2-3ae7dcccd225.png)

6. Change the GNS3 server configuration by selecting `Configure`

![Screenshot from 2022-05-13 19-10-35](https://user-images.githubusercontent.com/4752614/168325146-3807dc51-12f9-4802-b772-1e25ba5a5ad8.png)

7. Enter the following config to update the JWT token expiration to 1 minute. Save with CTRL+O and exit with CTRL+X

```
[Controller]
jwt_access_token_expire_minutes = 1
```

![Screenshot from 2022-05-13 19-12-08](https://user-images.githubusercontent.com/4752614/168325271-974f61f9-3e23-45f2-bd1d-af1f90ce88e0.png)

8. Reboot the VM by selecting `Reboot`

![Screenshot from 2022-05-13 23-17-58](https://user-images.githubusercontent.com/4752614/168325291-811bc83c-5e3f-48ef-b95e-cddf68eec02b.png)

9. Once the VM has booted, use the IP and port info listed in step 1 to configure the web-ui to access the GNS3 server running inside the VM.

![Screenshot from 2022-05-13 23-07-54](https://user-images.githubusercontent.com/4752614/168325331-697574c2-4de7-4c25-a6c7-061e2cc212be.png)

You should notice that the web-ui will enter into a loop once the JWT token has expired after 1 minute. You can change back the expiration time by editing the config like in step 7 and rebooting the VM.

**Comment by rajnikantsolarwinds** [comment]
@grossmj Sure
