### ISSUE TITLE
Updating Angular to v13

### ISSUE THREAD

**Issue by piotrpekala7** [GNS3/gns3-web-ui#1248]
Update packages to resolve security issues

**Comment by piotrpekala7** [comment]
I created branch https://github.com/GNS3/gns3-web-ui/tree/Updating-packages to fix all security issues and update all packages we use in web UI. Developer build works fine but when I try to create production build and open web UI there is blank page and error message in web console: Error: JIT compiler unavailable. I tried to find solution for this issue (similar to https://stackoverflow.com/questions/68798086/jit-compiler-unavailable-after-angular-update) with no result

**Comment by grossmj** [comment]
Update to Angular v13 is ready. Will be completed once https://github.com/GNS3/gns3-web-ui/pull/1305 is merged.
