### ISSUE TITLE
GNS3 IOSv Appliance Borked

### ISSUE THREAD

**Issue by Vespergrain** [GNS3/gns3-web-ui#1275]
Hello, 

Good evening, I was told to report a bug regarding the IOSv appliance for GNS3. Here is the link reported to the GNS3 support forum who notified me to open a case here. https://gns3.com/community/support/cisco-iosv-appliance-borked . If there is anything else you need please let me know as I can replicate the issue and provide logs if necessary.

**Comment by grossmj** [comment]
You can update the local appliance files: open a project, click on "New Template"

![Screenshot from 2022-03-23 11-26-11](https://user-images.githubusercontent.com/4752614/159603717-c2d6f7ae-3f33-401b-9a55-a437cd3a1841.png)

and then click on "Update from online registry".

![Screenshot from 2022-03-23 11-25-56](https://user-images.githubusercontent.com/4752614/159603727-edbccc1e-0ba1-47d7-861d-01f1f6588bb7.png)
