### ISSUE TITLE
Suspending link or applying packet filter leads to error

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#1279]
The error happens when suspending a link or applying a packet filter, looks like the server didn't accept the request because of `'x': None, 'y': None`. Indeed, these shouldn't be included in the request.

![Screenshot from 2022-03-23 11-51-46](https://user-images.githubusercontent.com/4752614/159606245-f535f81a-2dc1-462c-a725-f6d4443c80d9.png)

**Comment by piotrpekala7** [comment]
dev notes: need to check updateLink method in LinkService https://github.com/GNS3/gns3-web-ui/blob/master/src/app/services/link.service.ts#L65

**Comment by grossmj** [comment]
Note: there is no issue in version 3.0
