### ISSUE TITLE
why "yarn ng serve" error?

### ISSUE THREAD

**Issue by PKXZ** [GNS3/gns3-web-ui#1289]
[](https://fanyi.baidu.com/translate?aldtype=16047&query=yarn+ng+serve&keyfrom=baidu&smartresult=dict&lang=auto2zh###)[](javascript:void(0);)I run the project normally, but the project always reports the following errors:
An unhandled exception occurred: readConfiguration is not a function
See "C:\Users\pc6\AppData\Local\Temp\ng-z2daWi\angular-errors.log" for further details.
error Command failed with exit code 127.

[](https://fanyi.baidu.com/translate?aldtype=16047&query=yarn+ng+serve&keyfrom=baidu&smartresult=dict&lang=auto2zh###)[](javascript:void(0);)How to solve it?

**Comment by piotrpekala7** [comment]
I checked on latest main branch, all works fine, please try to reinstall node modules

**Comment by PKXZ** [comment]
Yes, it should be the problem of my operating environment. After a long time of effort, the node was replaced by v14.15.0. 
Thank you very much for your reply.
