### ISSUE TITLE
Branded labs support

### ISSUE THREAD

**Issue by ziajka** [GNS3/gns3-web-ui#130]

**Comment by piotrpekala7** [comment]
@ziajka Please add more detailed description

**Comment by ziajka** [comment]
Example: https://gns3.com/marketplace/lab/appoptics-demo-lab

**Comment by piotrpekala7** [comment]
After opening I'm asked about ACCESS_TOKEN, could you provide more information?

**Comment by piotrpekala7** [comment]
@ziajka I'm still not able to open the project, could u help with that?

**Comment by piotrpekala7** [comment]
blocked as there's no response

**Comment by piotrpekala7** [comment]
Closed as there's no response
