### ISSUE TITLE
Improve progress bar when uploading files

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#1308]
There are multiple locations in the web-ui where there is not clear indication of the progress of a file being uploaded.

In the image manager:

![Screenshot from 2022-04-27 16-13-11](https://user-images.githubusercontent.com/4752614/165484860-d20e7f02-989b-4f14-a358-57b29818c918.png)

When adding a new template (from an appliance):

![Screenshot from 2022-04-27 15-58-38](https://user-images.githubusercontent.com/4752614/165484918-d73d126c-0d38-4e38-8164-7281c63fca07.png)

The progress need to be calculated similar to what is described there: https://nils-mehlhorn.de/posts/angular-file-upload-progress#calculate-upload-progress. Interestingly, it appears that this is already supported when uploading an image while manually creating a new Qemu template in the preferences. Maybe this could be reused? We should have a similar and consistent progress bar every time we upload a file

![Screenshot from 2022-04-27 15-54-58](https://user-images.githubusercontent.com/4752614/165483650-84af745a-5afa-4d00-be03-1ca45799212b.png)

Please use this ~500 MB image for your tests, it should be big enough for a progress bar: https://sourceforge.net/projects/gns-3/files/Qemu%20Appliances/openbsd-5.8.qcow2/download

We will eventually do something similar for downloads but I believe we need to do something on server side first.

**Comment by grossmj** [comment]
Is the new progress bar used in all locations shown above?

**Comment by rajnikantsolarwinds** [comment]
Yes, I have used same process bar in all location
