### ISSUE TITLE
GNS3 - Wizard with option to configure gns3vm (electron version)

### ISSUE THREAD

**Issue by ziajka** [GNS3/gns3-web-ui#131]

**Comment by piotrpekala7** [comment]
@ziajka I need mockups, how it should be implemented, what information should be included etc.

**Comment by ziajka** [comment]
Please compare to GNS-GUI first run.

**Comment by piotrpekala7** [comment]
Merged with Jira ticket PA-3854

**Comment by piotrpekala7** [comment]
Will be fixed with https://github.com/GNS3/gns3-web-ui/pull/631
