### ISSUE TITLE
GNS3 web-ui version 2.2.33 does not load

### ISSUE THREAD

**Issue by cristian-ciobanu** [GNS3/gns3-web-ui#1335]
I have tested the new GNS3 release 2.2.33 release and it appears the GNS3 web-ui does not load anymore.

The tests were done on two different systems with the server running on Ubuntu and ArchLinux.

I looked into the browser console on both systems and I see a syntax error which might be the cause for this problem.

![image](https://user-images.githubusercontent.com/7124193/174730221-5c416f3e-5e36-426a-878d-60ed3f2529ba.png)

**Comment by grossmj** [comment]
Thanks for reporting. A file was missing, I am releasing a new version: 2.2.33.1
