### ISSUE TITLE
Webui missing reset console options

### ISSUE THREAD

**Issue by spikefishjohn** [GNS3/gns3-web-ui#1341]
in the fat client

![image](https://user-images.githubusercontent.com/31658656/175346539-b018e33b-962e-43a7-9fd5-4bc5f8ee1e44.png)

I don't see a way to do this via webui.

**Comment by grossmj** [comment]
@rajnikantsolarwinds the API endpoint to reset all consoles is https://apiv3.gns3.net/#/Nodes/reset_console_all_nodes_v3_projects__project_id__nodes_console_reset_post
