### ISSUE TITLE
Webui missing prompt for mass state changes of project

### ISSUE THREAD

**Issue by spikefishjohn** [GNS3/gns3-web-ui#1342]
The Start/Resume, Pause, Stop and Reload 

Buttons should prompt the user if they're sure they want to do that. Start isn't so bad, but stop can ruin your day if you accidently hit it.

![image](https://user-images.githubusercontent.com/31658656/175346965-c0054561-30e4-4a2f-8d96-2067b4999d31.png)

**Comment by grossmj** [comment]
Indeed, you should ask just like we do in the desktop client.

![Screenshot from 2022-06-26 12-25-23](https://user-images.githubusercontent.com/4752614/175809901-4d183257-5394-4a1a-9569-f53f0d9c3bda.png)

![Screenshot from 2022-06-26 12-25-05](https://user-images.githubusercontent.com/4752614/175809903-85b6734b-c0fe-421c-82e1-ddb3dbf7310a.png)

![Screenshot from 2022-06-26 12-26-13](https://user-images.githubusercontent.com/4752614/175809916-e177c0a4-d3b5-4a50-b917-7c5ad1cecfb0.png)

![Screenshot from 2022-06-26 12-28-13](https://user-images.githubusercontent.com/4752614/175809964-938c7451-c5cc-420f-9a4a-2650a7e98659.png)
