### ISSUE TITLE
Additional computes not displayed in "Servers" page after being added via Desktop UI

### ISSUE THREAD

**Issue by eantowne** [GNS3/gns3-web-ui#1347]
After adding a compute server via the Desktop UI, the newly added server is not displayed. It is however displayed in servers widget and server status.

![Web-UI-Second-Compute-Not-Displayed](https://user-images.githubusercontent.com/66289315/177560848-f4c9ef92-7b51-4598-b350-628f98dd8373.png)
![Web-UI-Servers-Widget](https://user-images.githubusercontent.com/66289315/177560861-750082cd-9d45-4da5-a9a8-72b2fd9da80f.png)

**Comment by grossmj** [comment]
> After adding a compute server via the Desktop UI, the newly added server is not displayed. It is however displayed in servers widget and server status.

We have renamed this in v3.0, the servers page is actually the controllers page. The servers widget the actual computes.
