### ISSUE TITLE
Change servers page to controllers page

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#1353]
This page is more about managing controllers, not servers.

1. Rename the page to `Controllers` and change the button to `Add controller`
2. Remove the top right menu from the page
3. Remove the location info (and the possibility to configure it when adding a new controller)

![servers_page](https://user-images.githubusercontent.com/4752614/179426564-a12a7ae1-9e9f-47bb-b8d2-c07d273757c6.png)

**Comment by eantowne** [comment]
If this is only for controllers, will there be another page for adding computes? Perhaps adding computes as indented/subs under the controller they are tied to?

**Comment by rajnikantsolarwinds** [comment]
I have changed  all things in `enhancement/1353` branch

- [x]  Rename the page to Controllers and change the button to Add controller
- [x]  Remove the top right menu from the page
- [x] Remove the location info (and the possibility to configure it when adding a new controller)

![image](https://user-images.githubusercontent.com/101106471/179450288-ceb5f8f0-a402-4a2c-8b7a-7bd52ea45d1f.png)

**Comment by grossmj** [comment]
> If this is only for controllers, will there be another page for adding computes? Perhaps adding computes as indented/subs under the controller they are tied to?

Correct, this is only for controllers. We will be adding computes separately in another page under the controller they are ties to.
