### ISSUE TITLE
Preferences page improvements

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#1355]
There are a few things that could be improved on the preferences page.

1. Rename to 'Template preferences'
2. There is no way to go back to the previous page once you are on the preferences page
3. In Built-in preferences
     - Rename the page to "Built-in templates"
     - Rename "Ethernet hubs" to "Ethernet hub templates"
     - Rename "Ethernet switches" to "Ethernet switch templates"
     - Rename "Cloud nodes" to "Cloud node templates"

![Screenshot from 2022-07-18 00-29-39](https://user-images.githubusercontent.com/4752614/179427289-8d6e7573-8c3f-4d02-a159-15434b7c0661.png)

4. Redesign all sub-pages
     - Change back button (by a simple icon)
     - Change add template button (a simple + icon)
     - Hamburger (3 dot) menu for templates under a category does not have “Edit” option, Only “Delete” and “Copy”. Yes, you can click the name of the entry, but that is not visibly communicated to the user without moving the mouse over the name. The 3 dot menu, would be the default interaction method.

![Screenshot from 2022-07-18 00-31-29](https://user-images.githubusercontent.com/4752614/179427344-4fb3360b-8f62-4a15-a390-7c19fd7ab2d2.png)

**Comment by rajnikantsolarwinds** [comment]
@grossmj 
Complete improvements on preferences page.
1.  Rename to 'Template preferences'
2.  There is no way to go back to the previous page once you are on the preferences page.
3. In Built-in preferences
- [x] Rename the page to "Built-in templates".
- [x] Rename "Ethernet hubs" to "Ethernet hub templates"
- [x] Rename "Ethernet switches" to "Ethernet switch templates"
- [x]  Rename "Cloud nodes" to "Cloud node templates"
4. Redesign all sub-pages
- [x]    Change back button (by a simple icon)
- [x] Change add template button (a simple + icon)
- [x] Hamburger (3 dot) menu for templates under a category does not have “Edit” option, Only “Delete” and “Copy”. Yes, you 
can click the name of the entry, but that is not visibly communicated to the user without moving the mouse over the name. The 3 dot menu, would be the default interaction method.
