### ISSUE TITLE
Options to resize pop-up windows

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#1361]
Can we resize pop-up windows? The node configuration one for instance.

![Screenshot from 2022-07-20 17-09-50](https://user-images.githubusercontent.com/4752614/180017788-0514dc33-8bf6-4476-80e3-4338471406fa.png)

**Comment by rajnikantsolarwinds** [comment]
@grossmj 
Yes, We can  resize pop-up windows and remove pagination arrow buttons
