### ISSUE TITLE
Uploaded images with long names get truncated in the Web-UI

### ISSUE THREAD

**Issue by cristian-ciobanu** [GNS3/gns3-web-ui#1372]
**Describe the bug**
Uploaded images with long names get truncated in the Web-UI

**GNS3 version and operating system (please complete the following information):**
 - OS: ArchLinux
 - GNS3 version: 3.0.0 alpha 1
 - GNS3 server and GUI are running on same machine (bare metal)

**To Reproduce**
1. Open Web-UI, click on the GNS3 top left menu and select **Image Manager**.
2. Click on Add Image, click on Next and then click on Browse and select an image.
3. The upload process completes successfully but the file name gets truncated as shown in the screenshot below.
4. The complete file name it is: **c8000v-universalk9_16G_serial.17.06.03a_controller.qcow2**

**Screenshots or videos**

![image_manager_001](https://user-images.githubusercontent.com/7124193/182962087-b31435f8-bfc4-45aa-a9d9-52fbd2e804ab.png)

**Additional context**
None

**Comment by rajnikantsolarwinds** [comment]
Hi @grossmj,
I have resolve [Uploaded images with long names get truncated in the Web-UI](https://github.com/GNS3/gns3-web-ui/issues/1372#top) issue in bugfix/1372 branch
![image](https://user-images.githubusercontent.com/101106471/183337240-9ab6c508-483d-482f-bf1a-b8298985108d.png)
