### ISSUE TITLE
Lock or unlock all items button does not reflect the nodes status on the web-ui workspace GNS3 3.0.0 alpha 1

### ISSUE THREAD

**Issue by cristian-ciobanu** [GNS3/gns3-web-ui#1379]
**Describe the bug**
Lock or unlock all items button does not reflect the nodes status on the web-ui workspace GNS3 3.0.0 alpha 1

**GNS3 version and operating system (please complete the following information):**
 - OS: ArchLinux
 - GNS3 version: 3.0.0 alpha 1
 - GNS3 server and GUI are running on same machine (bare metal)

**To Reproduce**
1. Open Web-UI, open an existing project and click on the **Lock or unlock all items** button on the left toolbar to lock all nodes.
2.All nodes are locked successfully but when right clicking on a locked node the dropdown menu still shows **Lock item** instead of **Unlock item** altghough all nodes are locked globally.
3. When all nodes are locked using the toolbar button **(button is green)** there is no way to unlock an individual node. 

**Screenshots or videos**

![lock_all_items_001](https://user-images.githubusercontent.com/7124193/183443633-7fd10f73-2b97-4510-b522-43bf4bf9a03e.png)

**Additional context**
None

**Comment by rajnikantsolarwinds** [comment]
Hi @grossmj,
Single node lock and unlock working fine but global items lock or unlock (lock button) does not perform any type activity only lock value (true/false)
Subscribe by observable  in draggable.selection.componnet but does not perform any type action.
Another point is  Global lock icon color does not persist after reload (Hence Global lock icon functionality is missing).
For API perspective , For single node API is getting called to lock/unlock/save state and it persist the lock/unlock
but for Global lock/unlock no API is getting called and it does not  persist state.

**Comment by grossmj** [comment]
In the GUI we keep the state of the a node locally with a `locked` property.

Then when calling lock or unlock all, we check the `locked` property and set the value accordingly.

```
if self.uiLockAllAction.isChecked() and not item.locked():
    item.setLocked(True)
elif not self.uiLockAllAction.isChecked() and item.locked():
   item.setLocked(False)
```

**Comment by grossmj** [comment]
The GNS3 desktop UI updates the `locked` property of each node/item when locking/unlocking all items is clicked.

For example, taking this project:

![Screenshot from 2022-08-29 23-29-06](https://user-images.githubusercontent.com/4752614/187302757-b2a12713-b589-4ec0-9ea9-630253aec8ec.png)

The result is multiple API calls, one for each node/item.

```
UPDATE {'drawing_id': '26b597b8-0ca8-4531-9a2f-2013789681f9', 'x': -739, 'y': -66, 'z': 1, 'locked': True, 'rotation': 0, 'svg': '<svg width="200" height="100"><rect width="200" height="100" fill="#ffffff" fill-opacity="1.0" stroke-dasharray="5, 25, 25" stroke-width="2" stroke="#000000" /></svg>'}
UPDATE {'drawing_id': '4fb527e9-f39e-4e7a-a0ad-34e4bb1fc6f1', 'x': -501, 'y': -70, 'z': 1, 'locked': True, 'rotation': 0, 'svg': '<svg width="200" height="100"><rect width="200" height="100" fill="#ffffff" fill-opacity="1.0" stroke-dasharray="25, 25, 5, 25, 5" stroke-width="2" stroke="#000000" /></svg>'}
UPDATE {'drawing_id': '7da63e51-a5e8-4259-a5f6-2ccc968572ae', 'x': -337, 'y': -216, 'z': 1, 'locked': True, 'rotation': 0, 'svg': '<svg width="200" height="100"><rect width="200" height="100" fill="#ffffff" fill-opacity="1.0" /></svg>'}
UPDATE {'drawing_id': '5b0a21dc-e368-4e56-8788-2d436bbe5722', 'x': -590, 'y': -220, 'z': 1, 'locked': True, 'rotation': 0, 'svg': '<svg width="200" height="100"><rect width="200" height="100" fill="#ffffff" fill-opacity="1.0" stroke-dasharray="25, 25, 5, 25, 5" stroke-width="2" stroke="#000000" /></svg>'}
UPDATE {'drawing_id': 'cfc7da61-3056-4a30-8e7d-d19edd9f9fa7', 'x': -819, 'y': -215, 'z': 1, 'locked': True, 'rotation': 0, 'svg': '<svg width="200" height="100"><rect width="200" height="100" fill="#ffffff" fill-opacity="1.0" stroke-dasharray="5, 25, 25" stroke-width="2" stroke="#000000" /></svg>'}
UPDATE {'drawing_id': 'd731486c-18db-49da-b40b-951e419e184a', 'x': -344, 'y': -353, 'z': 1, 'locked': True, 'rotation': 0, 'svg': '<svg width="200" height="100"><rect width="200" height="100" fill="#ffffff" fill-opacity="1.0" stroke-dasharray="5, 25" stroke-width="2" stroke="#000000" /></svg>'}
UPDATE {'drawing_id': 'ded3e044-53cc-4402-9bd7-063b63579b3b', 'x': -590, 'y': -353, 'z': 1, 'locked': True, 'rotation': 0, 'svg': '<svg width="200" height="100"><rect width="200" height="100" fill="#ffffff" fill-opacity="1.0" stroke-dasharray="25, 25" stroke-width="2" stroke="#000000" /></svg>'}
UPDATE {'drawing_id': '2cd357b4-c02f-4a7e-b2a1-d102c6966e39', 'x': -819, 'y': -354, 'z': 1, 'locked': True, 'rotation': 0, 'svg': '<svg width="200" height="100"><rect width="200" height="100" fill="#ffffff" fill-opacity="1.0" stroke-dasharray="none" stroke-width="2" stroke="#000000" /></svg>'}
UPDATE {'drawing_id': '347b0efb-88c2-4925-b79f-d491fd046e28', 'x': -23, 'y': -248, 'z': 1, 'locked': True, 'rotation': 0, 'svg': '<svg></svg>'}
UPDATE {'drawing_id': 'b84f1fe9-0023-432a-8741-503ff5200263', 'x': -156, 'y': -182, 'z': 1, 'locked': True, 'rotation': 0, 'svg': '<svg></svg>'}
```

I am considering adding an API endpoint to lock all items at once if this makes things easier for you.
