### ISSUE TITLE
Simple user weird behavior arriving in image manager

### ISSUE THREAD

**Issue by llevier** [GNS3/gns3-web-ui#1394]
Hello,

Create a basic user in his own group, no privileges.
Logging with it, going to image manager directly:
Arriving, directly a question : Would you like to automatically install appliances for this image? (Y/N).
I did nothing yet ;-)

**Comment by llevier** [comment]
Also at bottom: i.error is undefined

**Comment by grossmj** [comment]
That should have been fixed in the next alpha 3.
