### ISSUE TITLE
GNS3v3 as simple user

### ISSUE THREAD

**Issue by llevier** [GNS3/gns3-web-ui#1395]
Simple user, no privileges, logging in, clicking to add a blank project.
At page bottom: You provided 'undefined' where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.

Roughly, it is very difficul to do anything in GNSv3a as a basic user :-(

**Comment by grossmj** [comment]
Waiting on the new RBAC interface to test more.

**Comment by grossmj** [comment]
Fixed
