### ISSUE TITLE
usage setting in template does not show in project

### ISSUE THREAD

**Issue by JohnHay** [GNS3/gns3-web-ui#1398]
If usage is configured in a template through the web ui and a node of that type is then inserted in a project, usage inside "Show node information" says "No usage information has been provided for this node.". Looking in the project .gns3 file, the usage is there.

This is on version 2.2.34, although the web ui says v2.2.33.

John

**Comment by grossmj** [comment]
This seems to work in v2.2.37. We must have fixed it somehow...
