### ISSUE TITLE
Ipv6-only issues

### ISSUE THREAD

**Issue by kruisdraad** [GNS3/gns3-web-ui#1400]
Hi,

i am not sure if this is the right repo, so bear with me:

**setup:** An IPv6-only network, no IPv4 at all. GNS3 is bound to IPv6 only.

**version:**
```
ii  gns3-gui                              2.2.34~jammy1                           amd64        GNS3 GUI
ii  gns3-iou                              0.0.3~jammy3                            amd64        GNS3 support for IOU
ii  gns3-server                           2.2.34~jammy3                           amd64        GNS3 server
```

**problem:** When using the WebGUI or GNS Application to connect to a console the : separator confuses the e.g. putty between IP and port, e.g. if the address is 2001:666:666:666:5001 it would connect on ip 2001 with port 666. It looks like on the IPv6 passing of the IP address the [ ] are missing, the correct way would be [2001:666:666:666]:5001

When trying to use the console inside webGUI you can see it flashing open and directly closes, no error is logged client side. On the Server it only logs a mere:
`2022-09-26 20:02:39 WARNING route.py:232 Client error`

Beyond the console issues, the webGUI seems to be working just fine.

**Workaround 1:** By using an hostname in gns_server.conf to bind (e.g. mygns3.domain.tld) and adding this into /etc/hosts with 2001:666:666:666 will make gns_server bind correctly. As the hostname is now passed as mygns3.domain.tld and fully mygns3.domain.tld:5001 the problem is resolved for using the GNS3 application. With the WebGUI it just refuses to open an console entirely.

**Workaround 2:** switch to IPv4, buuuuut, i so wanted a ipv6 only network this time.

Imho it defiantly an GNS issue, but where i do not know. If you need furter info, let me know.

**Comment by grossmj** [comment]
Everything should work in the next version (v2.2.42) excepting connecting to consoles using the GNS3 web client pack (connections using real terminal via protocol handlers). I will create a separate issue for this.

![Screenshot from 2023-08-02 15-09-15](https://github.com/GNS3/gns3-web-ui/assets/4752614/a2ab0c68-ad20-4db0-9933-63ca0bf451d6)
