### ISSUE TITLE
Web UI v2.2.35 shows a blank window in Vivaldi Browser

### ISSUE THREAD

**Issue by ghost** [GNS3/gns3-web-ui#1408]
**Describe the bug**
After installing GNS3 v2.2.35, starting the Web UI shows a blank window in Vivaldi Browser. With the previous version v2.2.34 it works fine. After the upgrade it initially also works fine with v2.2.25, but after clearing the cache only a blank window is shown.

After reverting the Web UI in GNS3 server v2.2.25 to the previous version with `git revert dfb48c884b0a0ca07a41fab957928ce47691f036` (Release web-ui v2.2.35), the Web UI starts working again.

**GNS3 version and operating system:**
 - OS: Linux, Debian 11.5 (Bullseye)
 - GNS3 version 2.2.35
 - No use of the GNS3 VM or remote server (ESXi, bare metal etc.)
 - Vivaldi Browser 5.5.2805.42, based on Chrome

**To Reproduce**
1. Start Vivaldi Browser and clear cache
2. Start Web UI from GNS3 GUI by Tools -> Web UI - beta
3. See empty window in Vivaldi Browser

**Additional context**
GNS3 GUI/server was installed by `cd <GNS3 git directory>` / `pip3 install .`

**Comment by grossmj** [comment]
Thanks for confirming this. I will release a v2.2.35.1 soon.
