### ISSUE TITLE
WebUI Interface Labels Not Persistant

### ISSUE THREAD

**Issue by ronarista** [GNS3/gns3-web-ui#1435]
GNS3 Version: GNS3 v2.2.37
Client Operating System: MacOS 13.2, Google Chrome Version 109.0.5414.119
Server Operating System: GNS3 Image v2.2.37

When using the web UI if you turn off interface labels from the options pane in the top right corner the labels will turn off.  However if you refresh the page the labels turn back on, therefore the setting does not persist through a page refresh.

Other options such as show grid or show layers seem to keep their settings through a page refresh this is only exhibited with interface labels from what I can see currently.

**Comment by cristian-ciobanu** [comment]
Tested this also on version 3.0 and the issue is happening there also. 
The issue is that the interface labels are not saved to localStorage. The diff file below fixes this issue.
```
diff --git a/src/app/services/mapsettings.service.ts b/src/app/services/mapsettings.service.ts
index a1b2c3d4..e5f6g7h8 100644
--- a/src/app/services/mapsettings.service.ts
+++ b/src/app/services/mapsettings.service.ts
@@ -37,6 +37,12 @@ export class MapSettingsService {
     } else {
       localStorage.setItem('openReadme', 'false');
     }
+
+    if (localStorage.getItem('showInterfaceLabels')) {
+      this.showInterfaceLabels = localStorage.getItem('showInterfaceLabels') === 'true' ? true : false;
+    } else {
+      localStorage.setItem('showInterfaceLabels', 'true');
+    }
   }
 
   public getSymbolScaling(): boolean {
@@ -77,6 +77,12 @@ export class MapSettingsService {
 
   toggleShowInterfaceLabels(value: boolean) {
     this.showInterfaceLabels = value;
+    localStorage.removeItem('showInterfaceLabels');
+    if (value) {
+      localStorage.setItem('showInterfaceLabels', 'true');
+    } else {
+      localStorage.setItem('showInterfaceLabels', 'false');
+    }
   }
 
   toggleIntegrateInterfaceLabels(value: boolean) {
```

**Comment by grossmj** [comment]
@cristian-ciobanu that's awesome, thanks for the fix! :+1:
