### ISSUE TITLE
QEMU VM template, Desktop App vs Web GUI

### ISSUE THREAD

**Issue by akielaries** [GNS3/gns3-web-ui#1449]
I am trying to create a VM in GNS3 but in the desktop application we are able to choose from 23 different adapter types
![Screen Shot 2023-06-22 at 12 58 55 PM](https://github.com/GNS3/gns3-web-ui/assets/56521583/bf0b93f6-1570-4bd3-a902-d0ecb5d8f33c) 

But in the web GUI version, when I go to add a new template and configure network adapters, a random name scheme is showing with 20+ adapter "types" most of which are duplicates. <img width="920" alt="Screen Shot 2023-06-22 at 1 01 03 PM" src="https://github.com/GNS3/gns3-web-ui/assets/56521583/6dc1551b-ddb2-456c-ac63-a72dbcead1db">

Is there any relevance behind this naming? Do these labels correspond to any of the actual adapter types? I have had drastic differences in results when using the desktop client vs the web GUI but of course the latter is more maintainable/scalable for large topologies. What are the actual differences between the two clients?

**Comment by grossmj** [comment]
Thanks, this should be fixed in the next release.
