### ISSUE TITLE
Use default IOU values for memories always checked - IOU device configuration

### ISSUE THREAD

**Issue by pduran5** [GNS3/gns3-web-ui#1453]
Using GNS3 Web UI v2.2.40.1 (it says 2.2.40)

Adding a Cisco IOU L3 Router (i86bi-linux-l3-adventerprisek9-15.4.1T.bin) works and it runs ok.
But when unchecking 'Use default IOU values for memories' locally (in the project) or globally (in the template in Preferences > IOS on UNIX) and changing the RAM size to 512MB instead of the default 256MB, doesn't save the changes. When trying to change the template or the router config, the 'Use default IOU values for memories' is always checked.

Also when changing in the project the Configuration of the router, it doesn't have that 'Use default IOU values for memories' checkbox and the number of ethernets is empty.

**Comment by grossmj** [comment]
Thanks, I fixed the issue. This will work in the next version.
