### ISSUE TITLE
UEFI and TPM options missing in QEMU VM templates

### ISSUE THREAD

**Issue by pduran5** [GNS3/gns3-web-ui#1456]
These Advanced options are missing in QEMU VM templates and when saving they are always false:
- Enable the Trusted Platform Module (TPM)
- Enable the UEFI boot mode

These options are available when configuring QEMU VMs in a project.

GNS3 WebUI v2.2.41

**Comment by grossmj** [comment]
Thanks, I have added the missing settings. They will be available in v2.2.42
