### ISSUE TITLE
GNS3  2.2.44.1 web client launcher not working

### ISSUE THREAD

**Issue by nalafod** [GNS3/gns3-web-ui#1484]
I have noticed that on my GNS3 setup which is a remote physical ubuntu server since we updated to  2.2.44.1 the right click open console stopped opening the integrated tight vnc although I have reinstalled the GNS3 webclient to my computer and checked also the configuration.

Previously it was working as i am using it to run my scenarios in the web GNS3 UI.

Available if you need any other information or log for this case

**Comment by nalafod** [comment]
Tried installing latest webclient pack v1.0.0b6 but still not working opening console either from Firefox or Edge

**Comment by grossmj** [comment]
There is something broken with 3.0 beta 1 and 2.2.44.1, we fixed it in https://github.com/GNS3/gns3-web-ui/commit/f8613647279fe25c98c83dc4df386ed6d6eeb672

We will release new versions in the next few days.
