### ISSUE TITLE
FRR-Routing docker container in the WEB UI

### ISSUE THREAD

**Issue by pmsobral** [GNS3/gns3-web-ui#1487]
Hi,

Anyone was able to work with FRR-Routing docker container through the WEB UI? The interface only allows to open the console interface but for this device we need access to the auxiliary port that is not shown in the UI.

Best Regards,

Pedro

**Comment by grossmj** [comment]
> Anyone was able to work with FRR-Routing docker container through the WEB UI?

Is this a Docker container or the Qemu VM? The only appliance I found is to run with Qemu. Thanks.

**Comment by pmsobral** [comment]
Hello,

I use the container provided by FRRouting project in my topologies as it is much faster to startup and much more memory efficient. Cannot used it in the WEB UI due to the problem stated above.

Best Regards,

Pedro.

**Comment by grossmj** [comment]
Have I added the option to console to the auxiliary port in the contextual menu.

**Comment by pmsobral** [comment]
Thanks!
