### ISSUE TITLE
3.0 API docs and redoc blank page with HTTPS

### ISSUE THREAD

**Issue by crytectobi** [GNS3/gns3-web-ui#1496]
Hi!
I only get a white blank page from
https://gns3.local/docs and https://gns3.local/redoc
Tested with 3.0b1 and 3.0b2, both behave the same.
Everything else is working with https, but the docs are only blank pages.

Is the documentation not yet implemented as described in the blog post, or does this relate to https since this is not the default?

**Comment by crytectobi** [comment]
Ok it is related to HTTPS. I activated the dev tools, these are the errors:

GET https://cdn.jsdelivr.net/npm/swagger-ui-dist@5.9.0/swagger-ui.css net::ERR_CERT_COMMON_NAME_INVALID
docs:12 
       
GET https://cdn.jsdelivr.net/npm/swagger-ui-dist@5.9.0/swagger-ui-bundle.js net::ERR_CERT_COMMON_NAME_INVALID
docs:15  Uncaught ReferenceError: SwaggerUIBundle is not defined
    at docs:15:16

HTTPS and certificate is working fine with the rest of the webpages of GNS3.

**Comment by grossmj** [comment]
This may be related to https://github.com/tiangolo/fastapi/discussions/11513

Do you still have the issue?

**Comment by crytectobi** [comment]
Both URLs are working now! Seems to be resolved!
