### ISSUE TITLE
Web-UI 3.0.0beta3 - Trying to move multiple nodes at once doesn't work

### ISSUE THREAD

**Issue by baka0taku2022** [GNS3/gns3-web-ui#1505]
Browser: Google Chrome 125.0.6422.113 (Official Build) (64-bit) Windows
Web-UI Version: 3.0.0beta3

Steps to reproduce:
1. Select multiple nodes
2. Attempt to drag a node within the selection.
3. See error. Cancels the selection.

Before Drag
![Before drag](https://github.com/GNS3/gns3-web-ui/assets/106114965/4edbe9ad-15ed-4751-a5c5-98bfef6b52d9)

After Drag
![After drag](https://github.com/GNS3/gns3-web-ui/assets/106114965/a098489b-ee1e-48ab-9389-3201d6ad4704)

**Comment by grossmj** [comment]
Thanks for the report. Does this work as expected in v2.2.x?

**Comment by baka0taku2022** [comment]
No, it undoes the multi-select as well and only moves a single item. Version 2.2.47.

Before drag.
![image](https://github.com/user-attachments/assets/a38817ca-54a6-4edc-a113-0d403c64a14e)

After drag.
![image](https://github.com/user-attachments/assets/ec5b955e-c40e-499a-8a26-efa91ea6e582)

**Comment by grossmj** [comment]
Has it ever worked in an earlier version of the web-ui?

I am trying to understand if this is a regression or it has never been supported.

Thanks 👍

**Comment by baka0taku2022** [comment]
To be honest, I have not really tested this beyond what I have mentioned. If you would like me to, please let me know how far back you would like me to test.

**Comment by cristian-ciobanu** [comment]
I tested multiple nodes movement in the Web UI on latest version 3.0 which was released recently and it works fine.
I'm able to select multiple nodes and drag them on another side on the topology.
Tests were done on a Firefox based browser and a Chromium based browser on Linux.
