### ISSUE TITLE
Unable to Configure Ethernet Switch nodes with web-ui

### ISSUE THREAD

**Issue by brgomeistr** [GNS3/gns3-web-ui#1530]
Editing the "Ethernet Switch" node configuration in the webui does not work.
Version 2.5.2

Steps to replicate:
- Add an "Ethernet Switch" node to your project
- Right-click on the switch and select "Configure"
- Delete port 2
- Create a new configuration for port 2 (i.e. VLAN 3101, dot1a, and click "Add". Note that even though "Add" works it this configuration does not show up in the ui.
- Click "Apply".
- The following error appears:
Bad request http://127.0.0.1:80/v2/compute/projects/186eb5dc-d26c-46b9-a210-f80f824cc701/ethernet_switch/nodes/b2b896e1-50e2-431f-8fdf-8210d0649c6c { "message": "JSON schema error with API request '/v2/compute/projects/186eb5dc-d26c-46b9-a210-f80f824cc701/ethernet_switch/nodes/b2b896e1-50e2-431f-8fdf-8210d0649c6c' and JSON data '{'ports_mapping': [{'ethertype': '', 'name': 'Ethernet0', 'port_number': 0, 'type': 'dot1q', 'vlan': 3101}, {'ethertype': '', 'name': 'Ethernet1', 'port_number': 1, 'type': 'access', 'vlan': 3101}, {'name': 'Ethernet3', 'port_number': 3, 'type': 'access', 'vlan': 1}, {'name': 'Ethernet4', 'port_number': 4, 'type': 'access', 'vlan': 1}, {'name': 'Ethernet5', 'port_number': 5, 'type': 'access', 'vlan': 1}, {'name': 'Ethernet6', 'port_number': 6, 'type': 'access', 'vlan': 1}, {'name': 'Ethernet7', 'port_number': 7, 'type': 'access', 'vlan': 1}, {'name': '', 'port_number': 2, 'vlan': 3101, 'type': 'dot1q'}], 'name': 'Switch2', 'console': 5017, 'console_type': 'none'}': '' should be non-empty", "method": "PUT", "path": "/v2/compute/projects/{project_id}/ethernet_switch/nodes/{node_id}", "request": { "console": 5017, "console_type": "none", "name": "Switch2", "ports_mapping": [ { "ethertype": "", "name": "Ethernet0", "port_number": 0, "type": "dot1q", "vlan": 3101 }, { "ethertype": "", "name": "Ethernet1", "port_number": 1, "type": "access", "vlan": 3101 }, { "name": "Ethernet3", "port_number": 3, "type": "access", "vlan": 1 }, { "name": "Ethernet4", "port_number": 4, "type": "access", "vlan": 1 }, { "name": "Ethernet5", "port_number": 5, "type": "access", "vlan": 1 }, { "name": "Ethernet6", "port_number": 6, "type": "access", "vlan": 1 }, { "name": "Ethernet7", "port_number": 7, "type": "access", "vlan": 1 }, { "name": "", "port_number": 2, "type": "dot1q", "vlan": 3101 } ] }, "status": 400 }

Changing switch configurations works fine using the Windows client.

**Comment by grossmj** [comment]
Fixed. Thanks.
