### ISSUE TITLE
System status

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#2]
We can take example at the VIRL web interface.

**Comment by piotrpekala7** [comment]
@grossmj Please add more information

**Comment by grossmj** [comment]
I think I was refering to a page listing some info about system usage etc. like on this picture:

https://markwardbopp.files.wordpress.com/2015/02/screenshot-2015-02-22-23-06-52.png

Maybe the system information should come from the GNS3 server itself via an API call.

**Comment by piotrpekala7** [comment]
@grossmj Thanks for info. Yes, this should be received from server

**Comment by grossmj** [comment]
For comparison, this is the one from EVE-NG:

![Screenshot from 2019-11-03 18-45-23](https://user-images.githubusercontent.com/4752614/68083960-3cb51680-fe6a-11e9-9eff-c7bf1ed45b36.png)

**Comment by grossmj** [comment]
System status has another style on EVE-NG when accessed from a lab:

![Screenshot from 2019-11-03 19-07-36](https://user-images.githubusercontent.com/4752614/68084229-e0ec8c80-fe6d-11e9-8cea-4aaeb71b26fd.png)

**Comment by piotrpekala7** [comment]
Blocked by https://github.com/GNS3/gns3-server/issues/1682

**Comment by grossmj** [comment]
Branch 2.3 on gns3-server supports system statistics. Please check out https://github.com/GNS3/gns3-server/pull/1713#issue-364039869 and https://github.com/GNS3/gns3-server/blob/2.3/gns3server/schemas/server_statistics.py#L18L82 for details of what is returned

**Comment by piotrpekala7** [comment]
Will be fixed with https://github.com/GNS3/gns3-web-ui/pull/669
