### ISSUE TITLE
Add icons in gns3-web-ui electron app

### ISSUE THREAD

**Issue by ziajka** [GNS3/gns3-web-ui#23]
- [x] Linux
- [ ] MacOS
- [x] Windows

**Comment by ziajka** [comment]
https://www.npmjs.com/package/electron-icon-maker

**Comment by ziajka** [comment]
https://github.com/electron-userland/electron-builder/issues/1682

**Comment by ziajka** [comment]
On Windows every icon is in place.

**Comment by ziajka** [comment]
Application should have icons when installed (electron).

**Comment by ziajka** [comment]
We need to walk-through installed gns3-web-ui and check if icons are displayed properly, if not we need to provide a fix.

**Comment by ziajka** [comment]
Pending check on @piotrpekala7 side.

**Comment by piotrpekala7** [comment]
Waiting for Linux machine, task is blocked as ticket is not resolved

**Comment by ziajka** [comment]
Should be unblocked because of the machine.

**Comment by piotrpekala7** [comment]
I didn't see any problems with electron version on linux & windows when it comes to displaying icons. We can ask somebody with Mac machine to check that for us

**Comment by piotrpekala7** [comment]
Can we?

**Comment by grossmj** [comment]
I test on Mac and didn't see any problem when it comes to displaying icons.
