### ISSUE TITLE
VM server support

### ISSUE THREAD

**Issue by ziajka** [GNS3/gns3-web-ui#256]

**Comment by ziajka** [comment]
+ During adding nodes it's necessary to pick up destination server

**Comment by ziajka** [comment]
Ref. https://github.com/GNS3/gns3-web-ui/issues/573 - applicable only when using electron.

**Comment by piotrpekala7** [comment]
![NodeConfig](https://user-images.githubusercontent.com/31202938/70246606-4a670000-1778-11ea-8f19-09e19190de6f.PNG)

**Comment by piotrpekala7** [comment]
Option to choose server type to run node is GUI is one of the step in creating templates. Should we exchange this to dialog while adding nodes ~ 

> During adding nodes it's necessary to pick up destination server

**Comment by ziajka** [comment]
Yes, user needs ability to change the server where node is located (we are able to support multiple servers).

**Comment by piotrpekala7** [comment]
Do you mean particular node or group of nodes based on one template?

**Comment by piotrpekala7** [comment]
In GUI user also can choose between multiple servers while creating templates, like on the screenshot above

**Comment by ziajka** [comment]
I think both.

**Comment by piotrpekala7** [comment]
As we create node from template /v2/projects/{project_id}/templates/{template_id}, temporary solution will be creating duplication of template and then node based on duplication

**Comment by piotrpekala7** [comment]
@ziajka Do you agree with the one above or do you want to create task for preparing separate endpoint?

**Comment by piotrpekala7** [comment]
any updates here?

**Comment by ziajka** [comment]
This task evolved into: during adding the node customer is able to change the server where node should be located at. This task should be closed.
