### ISSUE TITLE
Managing general preferences for GNS3 server

### ISSUE THREAD

**Issue by piotrpekala7** [GNS3/gns3-web-ui#287]
Data with preferences should be available via server side. 
We need additional endpoint to retrieve data with local settings.

**Comment by piotrpekala7** [comment]
@ziajka I marked this task as blocked as we still don't have possibility to do it by UI side

**Comment by ziajka** [comment]
depends on gns3-server

**Comment by piotrpekala7** [comment]
Fixed with https://github.com/GNS3/gns3-web-ui/pull/610
