### ISSUE TITLE
Ability to take screenshot of map

### ISSUE THREAD

**Issue by piotrpekala7** [GNS3/gns3-web-ui#334]

**Comment by piotrpekala7** [comment]
Basic implementation here: https://github.com/GNS3/gns3-web-ui/tree/Ability-to-take-screenshot-of-map,
there's problem with saving images inside svg

**Comment by piotrpekala7** [comment]
@ziajka Any suggestions here?

**Comment by ziajka** [comment]
@piotrpekala7 maybe nested conversion of SVG.
