### ISSUE TITLE
Expand canvas on zooming/dragging

### ISSUE THREAD

**Issue by ziajka** [GNS3/gns3-web-ui#354]

**Comment by ziajka** [comment]
Let's go with solution based on margins. Probably has lower priority.

**Comment by piotrpekala7** [comment]
@ziajka We cant't find proper approach for resolving that issue: unfortunately action after event is fired (when user drop node near the border of current area) won't be executed faster than end of dragging element. This is blocker for dynamically extending canvas. We'll provide support for changing canvas size through map menu.

**Comment by piotrpekala7** [comment]
Closed as won't fix
