### ISSUE TITLE
The SSL certificate bundle file '*/cacert.pem' could not be found

### ISSUE THREAD

**Issue by ziajka** [GNS3/gns3-web-ui#36]

**Comment by ziajka** [comment]
https://stackoverflow.com/questions/23354628/python-requests-and-cx-freeze

**Comment by piotrpekala7** [comment]
@ziajka Please add more information

**Comment by ziajka** [comment]
gns3-server is bundled in Electron Application. During the build & run it cannot find cacert.pem - cx freeze skips text files.

**Comment by grossmj** [comment]
I think it has to be manually included like this https://github.com/GNS3/gns3-build/blob/7cec8999ca2882c2b6b7f42ee200622a6fde5af2/OSX/build.py#L129

**Comment by piotrpekala7** [comment]
Will be fixed with https://github.com/GNS3/gns3-web-ui/pull/645
