### ISSUE TITLE
Symbols themes support

### ISSUE THREAD

**Issue by ziajka** [GNS3/gns3-web-ui#364]

**Comment by ziajka** [comment]
Best option is to look how it works in gns3-gui.

**Comment by grossmj** [comment]
Just a warning, symbols themes support in the gns3-gui is a bit work in progress.

**Comment by piotrpekala7** [comment]
Right I saw your comments here https://github.com/GNS3/gns3-server/issues/1466

**Comment by grossmj** [comment]
I don't think we are going to implement symbol themes in the GNS3 server.
