### ISSUE TITLE
Web Interface not showing devices

### ISSUE THREAD

**Issue by ziajka** [GNS3/gns3-web-ui#365]
Ref. https://community.gns3.com/community/discussion/web-interface-not-showing-device
Can be related to:
#256 or #364

**Comment by ziajka** [comment]
Custom icons have no impact on this issue.

**Comment by ziajka** [comment]
Win with VM setup works as well.

**Comment by piotrpekala7** [comment]
Relatates to https://github.com/GNS3/gns3-web-ui/issues/518

**Comment by piotrpekala7** [comment]
Should be fixed with https://github.com/GNS3/gns3-web-ui/pull/519
