### ISSUE TITLE
How to debug Web UI Guide

### ISSUE THREAD

**Issue by ziajka** [GNS3/gns3-web-ui#367]
Put it on docs.gns3.com.

**Comment by piotrpekala7** [comment]
@ziajka Do you think this should be similar to https://docs.gns3.com/1EYTxujuTGa9sT-d2S3Dhs57olk-MzWWB0PYoZkzSDl8/index.html?

**Comment by piotrpekala7** [comment]
Who can explain me how documentation is generated?

**Comment by piotrpekala7** [comment]
As I need more information marked as need to be refined

**Comment by ziajka** [comment]
Yes, goal is to have a basic guide for our customers how they report issues, what information they should look for, and how.

**Comment by piotrpekala7** [comment]
Description added here https://docs.google.com/document/d/112zOqKdSnVrtT7K37aHkiRqmpx8U4DCXajsSnH33k3Y/edit?folder=0B558b5_SCiAHTWtTRnJrdzlaZVU#
