### ISSUE TITLE
Optimize AppVeyor for not re-downloading external execs

### ISSUE THREAD

**Issue by ziajka** [GNS3/gns3-web-ui#370]

**Comment by ziajka** [comment]
Lock file generation from external resources

**Comment by ziajka** [comment]
It's about electron build process.

**Comment by piotrpekala7** [comment]
@ziajka I went through configuration file for appveyor and there'is no invocation to external source at the moment. We don't use Invoke-WebRequest cmdlet or WebClient class or any other class to download external artifact from appveyor documentation

**Comment by piotrpekala7** [comment]
Please mark it as 'need to be refined' if needed. Otherwise I will close this task

**Comment by ziajka** [comment]
During this execution: https://github.com/GNS3/gns3-web-ui/blob/master/.appveyor.yml#L27
Additionals files are being downloaded

**Comment by piotrpekala7** [comment]
We can't find any way to avoid downloading external artifacts

**Comment by piotrpekala7** [comment]
Closed as won't fix
