### ISSUE TITLE
Redundant action for showing interface labels

### ISSUE THREAD

**Issue by adosztal** [GNS3/gns3-web-ui#377]
To enable interface labels, first a click is needed on "Show interface labels", then the checkbox with similar caption has to be checked. I think simply clicking on the button should be enough - unless you were just experimenting with it and/or will add other elements later (in this case, disregard this issue :)).

![VirtualBox_gns3-testing-client_17_04_2019_20_14_03](https://user-images.githubusercontent.com/16632791/56311226-cb23ae00-614d-11e9-90b3-dd273e0b33f2.png)

**Comment by ziajka** [comment]
Thanks @adosztal . Intention is to have multiple options there :) They will come when we add extra features.
