### ISSUE TITLE
gns3server and ubridge discovery on linux

### ISSUE THREAD

**Issue by ziajka** [GNS3/gns3-web-ui#423]
When user is running in electronjs and commands are available. 
![Screenshot_2019-06-04_12-14-53](https://user-images.githubusercontent.com/29223277/58871491-618e3d80-86c2-11e9-970d-656248d57e36.png)

**Comment by ziajka** [comment]
Ref. https://github.com/GNS3/gns3-web-ui/issues/573

**Comment by ziajka** [comment]
Just make sure it works properly on linux & only in electron js.

**Comment by piotrpekala7** [comment]
Verified finding gns3server works correctly
