### ISSUE TITLE
Pressing return in the console shows "unknown syntax" message

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#512]
Very minor issue. Pressing return with an empty line shouldn't show anything or be blocked.

![Screenshot from 2019-09-30 12-10-08](https://user-images.githubusercontent.com/4752614/65852095-b0ee2d00-e387-11e9-9d90-cf5aa2852ca3.png)

**Comment by piotrpekala7** [comment]
As I remember it's not implemented, @grossmj only this command is missing?

**Comment by grossmj** [comment]
I tested most of the commands, only the ``console <node>`` appears the be missing.

**Comment by piotrpekala7** [comment]
Fixed with https://github.com/GNS3/gns3-web-ui/commit/dfa25d7b941a211ed0184eaa9156bf466ba1d81f
