### ISSUE TITLE
Screenshot seems to not work

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#513]
Taking a screenshot from the menu shows a box with what seems to be the content of a SVG image and then nothing.

Tested on Linux with Chrome version 77.0.3865.75

![Screenshot from 2019-09-30 12-03-31](https://user-images.githubusercontent.com/4752614/65852263-3245bf80-e388-11e9-942b-faacde482090.png)

**Comment by piotrpekala7** [comment]
Will be fixed with https://github.com/GNS3/gns3-web-ui/pull/521

**Comment by piotrpekala7** [comment]
Fixed with https://github.com/GNS3/gns3-web-ui/pull/521
