### ISSUE TITLE
Duplicating a node or any item shows an error message

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#514]
An error message is shown when duplicating a node: "Cannot duplicate node data for nodes:"

Also, this happens for items like rectangle, rectangles, notes etc.

![Screenshot from 2019-09-30 13-49-36](https://user-images.githubusercontent.com/4752614/65852647-5655d080-e389-11e9-8f2a-2c48f2904b8e.png)

**Comment by piotrpekala7** [comment]
Fixed with https://github.com/GNS3/gns3-web-ui/commit/4d5ac71f0b978bec74ad147e0b03686317538f24
