### ISSUE TITLE
Delete a link / start a new packet capture

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#515]
Maybe this is already on the roadmap but how to delete an existing link or start a new packet capture?

**Comment by piotrpekala7** [comment]
![515](https://user-images.githubusercontent.com/31202938/65853155-d879d100-e358-11e9-9a29-cd60204dff5f.JPG)

**Comment by piotrpekala7** [comment]
@grossmj Select link & then choose an option

**Comment by grossmj** [comment]
I see, I missed that the first time because you have to select the link first. Is there a way to show the menu with a simple right click on the link?

**Comment by piotrpekala7** [comment]
It' should work with right-click. If not please comment with browser & OS

**Comment by grossmj** [comment]
I found I have this problem on Linux with both Chrome and Firefox

**Comment by piotrpekala7** [comment]
Fixed with https://github.com/GNS3/gns3-web-ui/commit/45653036f9e48b2c063050950da06ff6796e48c9
