### ISSUE TITLE
Web UI: "n is undefined (evaluating 'n.host')"

### ISSUE THREAD

**Issue by candlerb** [GNS3/gns3-web-ui#532]
(Backend: gns3-server 2.2.0 running on Ubuntu 18.04; frontend macOS 10.14.6)

I have a topology which views correctly at `/static/web-ui/server/1/project/<uuid>` in Chrome (77.0.3865.90), but in Firefox (69.0.1) I get:

![image](https://user-images.githubusercontent.com/44789/66733270-e3ebf280-ee56-11e9-916f-29ee6c7add3b.png)

Safari (13.0.2) gives a slightly more useful message:

![image](https://user-images.githubusercontent.com/44789/66733490-a8055d00-ee57-11e9-89c5-7bc016798186.png)

In Firefox, the browser console doesn't give anything useful:

![image](https://user-images.githubusercontent.com/44789/66733439-7ab8af00-ee57-11e9-9ebb-7569721d81fb.png)

And in Safari developer tools, the console is completely blank.

Please let me know if there's anything I can do to get more useful debug info out of this.

**Comment by candlerb** [comment]
Update: a colleague tried accessing my gns3 server remotely using macOS + Chrome.  Initially he got the same error, but then it started working.  Odd!

**Comment by candlerb** [comment]
Problem has been found.

If I go *directly* to the target URL `/static/web-ui/server/1/project/<uuid>` in another browser, then the error occurs.  But If I first go to `/static/web-ui/bundled`, then navigate to the project from the list, it's fine.  Some sort of cookie issue perhaps?

It would still be nice to have the server behave more gracefully in this situation - I think that sharing a project URL is something you might reasonably want to do.

**Comment by candlerb** [comment]
Simple reproducer:

* Navigate to a project
* Copy the URL
* Open an "Incognito" window
* Paste the URL into that window

**Comment by piotrpekala7** [comment]
@candlerb We don't provide support for multi-tabs right now. If you try to open project in two separated tabs but then close the project in one tab, second tab will show an error.

**Comment by piotrpekala7** [comment]
@candlerb When it comes to link in incognito window, simply server id added in web app is cached by client side so it's expected behavior.

**Comment by piotrpekala7** [comment]
@candlerb Our next step is release electron version https://github.com/GNS3/gns3-web-ui/issues/573 so support for multi-tab using is not our goal.
