### ISSUE TITLE
topology/servers summary says console telnet to 0.0.0.0

### ISSUE THREAD

**Issue by candlerb** [GNS3/gns3-web-ui#558]
After "Show topology/servers summary", the web UI shows:

![image](https://user-images.githubusercontent.com/44789/67634333-62627e80-f8b2-11e9-87df-c02bc4592a37.png)

Clearly you can't telnet to 0.0.0.0.  However the equivalent page in GNS3 client (macOS) shows the correct hostname, matching the one set in `GNS3 > Preferences ... > Server > Remote Main Server > Host`

I think it's related to this code in `gns3server/controller/__init__.py`

```
        # clients will use the IP they use to connect to
        # the controller if console_host is 0.0.0.0
        console_host = host
        if host == "0.0.0.0":
            host = "127.0.0.1"
```

If I change it to:

```
        if host == "0.0.0.0":
            console_host = "127.0.0.1"
```

then both the web UI and the macOS GUI show 127.0.0.1.

But when the GNS3 server is remote from the client (as I am using it), 127.0.0.1 is the wrong answer for the console address.  Better to insert the hostname from the HTTP request - or at least `socket.getfqdn()`.

(I am guessing the macOS GUI has a rule that says 0.0.0.0 is replaced with the server address?)

------

A couple of other experiments after putting the code back how it was.  In `gns3_server.conf`:

(1) if I set `host = 192.168.122.1`: the web UI and the macOS GUI both correctly show `telnet 192.168.122.1:5001`

(2) if I set `host = ::`: the server only listens on its IPv6 address - but fortunately I have one of those.    The web UI shows `telnet :::5001`.  The macOS GUI shows `telnet x:x:x:x:x:x:x:x:5001`, which is almost correct, although I think it should either say `x.x.x.x.x.x.x.x 5001` (with a space) or `[x.x.x.x.x.x.x.x]:5001` (with square brackets)

This suggests to me that the web UI is showing whatever is in `console_host` - which is copied from `host` - whilst the macOS GUI is substituting the IP address given in the "servers" preference box.

**Comment by piotrpekala7** [comment]
Fixed with https://github.com/GNS3/gns3-web-ui/commit/a6ed6660cae3cb6ff240aa9bc692826576f55d88
