### ISSUE TITLE
Adbutler error

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#570]
I can see the following error after opening the web-ui on Linux with Chrome:

![Screenshot from 2019-11-03 18-20-14](https://user-images.githubusercontent.com/4752614/68083714-f01c0c00-fe66-11e9-8aff-5e68c5efb1ff.png)

Looks like this a problem with adbutler.

**Comment by piotrpekala7** [comment]
Fixed with https://github.com/GNS3/gns3-web-ui/pull/575
