### ISSUE TITLE
No indicators that a link is suspended

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#571]
Suspending a link in the web-ui doesn't show anything. The link is correctly suspended and this can be seen in the desktop Ui for the same opened project.

Suspended link in the desktop Ui:

![Screenshot from 2019-11-03 19-11-49](https://user-images.githubusercontent.com/4752614/68084243-172a0c00-fe6e-11e9-8b7d-7331afdec911.png)

Suspended link in the web Ui:

![Screenshot from 2019-11-03 19-11-59](https://user-images.githubusercontent.com/4752614/68084263-607a5b80-fe6e-11e9-9b3f-738b90c9a08c.png)

**Comment by piotrpekala7** [comment]
![suspended](https://user-images.githubusercontent.com/31202938/68123471-d956d300-fec1-11e9-934a-0dc913c55f60.PNG)

**Comment by piotrpekala7** [comment]
Fixed with https://github.com/GNS3/gns3-web-ui/pull/574
