### ISSUE TITLE
Some actions should be allowed when selecting multiple nodes

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#572]
Only a few actions are available in the contextual menu when selecting multiple nodes:

![Screenshot from 2019-11-03 19-18-12](https://user-images.githubusercontent.com/4752614/68084288-ccf55a80-fe6e-11e9-9856-063da50c9ad6.png)

More actions like start, stop, suspend, console etc. should be allowed like in the desktop ui. Here is what we have now.

![contextual_menu_gns3](https://user-images.githubusercontent.com/4752614/68084348-6e7cac00-fe6f-11e9-8b22-ba3e94f3c992.png)

**Comment by piotrpekala7** [comment]
Fixed with https://github.com/GNS3/gns3-web-ui/pull/577
Most of actions are currently available (apart from text edit, export config and node configurator - in my opinion it should work only for single node).
