### ISSUE TITLE
Release Electron Based WebUI

### ISSUE THREAD

**Issue by ziajka** [GNS3/gns3-web-ui#573]
Research what need to be accomplished in order to release electron based WebUI.

**Comment by piotrpekala7** [comment]
**Windows**
Creating msi installer for Windows: (https://github.com/GNS3/gns3-web-ui/tree/MSI_installer)
-> electron-packager . --platform=win32 --arch=x64 GNS3WebUI
-> node build_installer_windows.js

**Comment by ziajka** [comment]
We are using electron-builder https://github.com/GNS3/gns3-web-ui/blob/master/.appveyor.yml#L28 which produces builds here: https://github.com/GNS3/gns3-web-ui/releases

**Comment by piotrpekala7** [comment]
As I see we provide exe file, is it proper way?

**Comment by piotrpekala7** [comment]
Should we do anything else apart from linked tasks?

**Comment by piotrpekala7** [comment]
Blocked -> subtasks are not resolved

**Comment by piotrpekala7** [comment]
It should cover also option to start server & open file explorer -> we have it in Jira

**Comment by piotrpekala7** [comment]
Option to open in file explorer closed with https://github.com/GNS3/gns3-web-ui/commit/f49cc1960c44431b62c9cf8dc9236aa20635a7e1, another tasks - option to start server - will be moved to Jira
