### ISSUE TITLE
Missing import config in node contextual menu

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#578]
Looks like "Import config" is missing from the node contextual menu. This should be supported by VPCS, IOU, Dynamips and Docker nodes.

![Screenshot from 2019-11-05 21-01-46](https://user-images.githubusercontent.com/4752614/68210396-6740d400-0010-11ea-9050-9b647c1e1366.png)

**Comment by grossmj** [comment]
Also, careful because IOS and IOU nodes have 2 different configs: startup-config and private-config.

**Comment by piotrpekala7** [comment]
@grossmj @ziajka Will be fixed with https://github.com/GNS3/gns3-web-ui/pull/602
