### ISSUE TITLE
Close a project

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#579]
There should be a way to close a project.

From a project itself, just before "Delete project":

![Screenshot from 2019-11-05 21-28-51](https://user-images.githubusercontent.com/4752614/68211966-8db43e80-0013-11ea-87af-0c1778998bb6.png)

Or from the projects list:

![Screenshot from 2019-11-05 21-30-10](https://user-images.githubusercontent.com/4752614/68211965-8db43e80-0013-11ea-9fba-0df6165a9636.png)

The icon for "close a project" could look like this: 

![Screenshot from 2019-11-05 22-06-27](https://user-images.githubusercontent.com/4752614/68214544-9ce9bb00-0018-11ea-875f-f137cb46ec6c.png)

Also, a confirmation should be asked before closing or deleting project.

**Comment by piotrpekala7** [comment]
Fixed with https://github.com/GNS3/gns3-web-ui/commit/ffc3e028553f88d0a2e9ff8126315172e2e44acd
