### ISSUE TITLE
Improvements for adding nodes

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#580]
First, I think the "browse all devices" button should be renamed "Add a node" and move just before "Add a link".

![Screenshot from 2019-11-03 19-32-23](https://user-images.githubusercontent.com/4752614/68215456-3e254100-001a-11ea-9b65-a4d2b18c70bf.png)

Second, it is possible to add multiple nodes of the same type when dragging a node and pressing CTRL at the same time in the desktop Ui. I think adding an option to this dialog (with default to 1) should be enough. Also, adding an option to filter by node type would be great (Routers, switches, guests and firewalls).

![Screenshot from 2019-11-05 22-18-31](https://user-images.githubusercontent.com/4752614/68215453-3e254100-001a-11ea-9a11-75efd8c8c75b.png)

**Comment by grossmj** [comment]
For comparison, here is the what users see when adding a new node in EVE-NG

![Screenshot from 2019-11-03 19-29-10](https://user-images.githubusercontent.com/4752614/68313270-3edbd700-00ef-11ea-9e34-caec09af68f2.png)

**Comment by piotrpekala7** [comment]
@grossmj Will be fixed with https://github.com/GNS3/gns3-web-ui/pull/596
