### ISSUE TITLE
Large icons when using custom symbols

### ISSUE THREAD

**Issue by adosztal** [GNS3/gns3-web-ui#582]
From the [forum](https://gns3.com/community/discussion/issues-with-html5-webui):
> When using custom symbols, which are ok in the fat client, they show as rediculously large in the webui, as per the example below.

**Comment by b-ehlers** [comment]
Just an idea:
The icons seem to be about 300x300px in size, that's the size of the original affinity symbols <https://github.com/ecceman/affinity>. As they were in widespread use, GNS3 implemented a workaround to show them nicely: All big symbols are scaled down to a max. height of 80 pixel, see issue https://github.com/GNS3/gns3-gui/issues/2674 for details.

**Comment by grossmj** [comment]
Correct, we resize the icon size in the fat client (there in the code: https://github.com/GNS3/gns3-gui/blob/3e0f1affd0700f588fbf24537f99cd27ba149bcb/gns3/items/node_item.py#L145L148). This is an option activated by default and this can be changed in the preferences.

![Screenshot from 2019-11-06 11-32-20](https://user-images.githubusercontent.com/4752614/68266231-6d26cb80-0089-11ea-9a02-116a38ff2fbc.png)

**Comment by piotrpekala7** [comment]
![customSymbolIssue](https://user-images.githubusercontent.com/31202938/68286931-c1ed2680-0036-11ea-863f-2020bfa3fb65.PNG)

Changing icon to custom could cause changing width & height to 0 (like on the screen above). Should we introduce min & max value for width & height in web UI?

**Comment by grossmj** [comment]
> Changing icon to custom could cause changing width & height to 0 (like on the screen above)

How can this happen? We could set a min value just in case of course...

**Comment by piotrpekala7** [comment]
Fixed with https://github.com/GNS3/gns3-web-ui/blob/master/src/app/cartography/widgets/node.ts#L94, auto-scaling for svg should works on all browsers
