### ISSUE TITLE
Open ads in new window

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#583]
Small improvement, it would be better to open ads in a new window (when clicking on check it out).

![Screenshot from 2019-11-06 17-25-21](https://user-images.githubusercontent.com/4752614/68285603-8a27c280-00ba-11ea-9a44-ca38b9e71f19.png)

**Comment by piotrpekala7** [comment]
We receive HTML code from Adbutler service  so we can try to add target="_blank" directly in ad. There is no option to achieve that in Angular app.

**Comment by grossmj** [comment]
Ok, no worries then. Let's change this on Adbutler.
