### ISSUE TITLE
Strange message box appears on servers page

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#585]
This message box appears when opening the servers page (e.g. http://localhost:4200/servers):

![Screenshot from 2019-11-06 22-26-24](https://user-images.githubusercontent.com/4752614/68306451-8c9f1200-00e4-11ea-9836-9a408e734bf4.png)

**Comment by piotrpekala7** [comment]
@grossmj Fixed with https://github.com/GNS3/gns3-web-ui/commit/ed9ca9ed034681467594fb558ed133807e396f62
