### ISSUE TITLE
Some issues with projects that don't exist

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#586]
Clicking on the "open project" icon, the GNS3 server returns a 404 error for a project that does not exist anymore, however the web ui is stuck on its waiting icon:

![Screenshot from 2019-11-06 22-31-55](https://user-images.githubusercontent.com/4752614/68306876-4e562280-00e5-11ea-94e0-52c8c33e0899.png)

Clicking on the project itself opens the project page with the correct error information, nothing wrong here.

![Screenshot from 2019-11-06 22-25-28](https://user-images.githubusercontent.com/4752614/68306714-01724c00-00e5-11ea-8349-b31557e3bede.png)

However, clicking on the "Go to home" icon leads to that error:

![Screenshot from 2019-11-06 22-29-31](https://user-images.githubusercontent.com/4752614/68306713-01724c00-00e5-11ea-8125-fac7e42132c8.png)

**Comment by piotrpekala7** [comment]
@grossmj Will be fixed with https://github.com/GNS3/gns3-web-ui/pull/597
