### ISSUE TITLE
Icon not centered

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#587]
Very minor but the icon to go to back to 100% zoom is not centered

![Screenshot from 2019-11-06 22-43-33](https://user-images.githubusercontent.com/4752614/68308046-27005500-00e7-11ea-8eb6-c1b3523a3518.png)

**Comment by piotrpekala7** [comment]
@grossmj Will be fixed with https://github.com/GNS3/gns3-web-ui/pull/596
