### ISSUE TITLE
Screenshot SVG image issue

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#589]
The screenshot feature exports SVG images. The images can be opened fine in browsers however opening with a system viewer (Ubuntu in my case), I cannot see the nodes.

Original view:

![Screenshot from 2019-11-07 16-26-09](https://user-images.githubusercontent.com/4752614/68373046-fc60db80-017c-11ea-8877-ea369635221b.png)

Saved SVG image:

![Screenshot from 2019-11-07 16-26-04](https://user-images.githubusercontent.com/4752614/68373049-fc60db80-017c-11ea-951c-3111b0e5dd96.png)

Also, would it be complicated to export in other formats like PNG?

**Comment by piotrpekala7** [comment]
There is solution for exporting images as png, unfortunately it doesn't work on every platform so we've decided to implement exporting as svg as default (on Linux)

**Comment by piotrpekala7** [comment]
When it comes to opening in file viewer I'm afraid it would be hard to fix it. After quick research I find that some file viewers have problems with rendering images & text inside svg (support for older standards)

**Comment by grossmj** [comment]
> There is solution for exporting images as png, unfortunately it doesn't work on every platform so we've decided to implement exporting as svg as default (on Linux)

Maybe we can offer more formats on platforms like Windows?

**Comment by piotrpekala7** [comment]
@grossmj @ziajka I will try to fix it with:
- https://www.npmjs.com/package/save-pixels
- https://www.npmjs.com/package/save-svg-as-png
- https://www.npmjs.com/package/save-html-as-image

maybe sth from the list above will work on every platform & browser

**Comment by piotrpekala7** [comment]
I tested also 
https://www.npmjs.com/package/svg-saver-node
https://www.npmjs.com/package/svg-2-image
https://www.npmjs.com/package/d3-to-image

**Comment by piotrpekala7** [comment]
@ziajka I was trying with save-html-as-image

	let splittedSvg = document.getElementsByTagName("svg")[0].outerHTML.split('image');
	let i = 1;

	while (i < splittedSvg.length) {
		let splittedImage = splittedSvg[i].split("\"");
		let splittedUrl = splittedImage[1].split("/");

		let elem = await this.symbolService.raw(this.server, splittedUrl[7]).toPromise(); 
		let splittedElement = elem.split('-->');
		splittedSvg[i] = splittedElement[1].substring(2);
		i += 2;
	}
	let svgString = splittedSvg.join();

	let placeholder = document.createElement('div');
	placeholder.setAttribute('height', '1000px');
	placeholder.setAttribute('width', '2000px');

	placeholder.innerHTML = svgString;
	let element = placeholder.firstChild;

	svg.saveSvgAsPng(element);
	saveAsJpeg(element);

**Comment by piotrpekala7** [comment]
unfortunately it doesn't work on every browser & platform

**Comment by piotrpekala7** [comment]
@grossmj @ziajka please decide what we can do next with that

**Comment by grossmj** [comment]
Can we detect browser and platform and only allow conversion for the one that work?

**Comment by piotrpekala7** [comment]
yes, we can detect platform

**Comment by piotrpekala7** [comment]
Will be fixed with https://github.com/GNS3/gns3-web-ui/pull/599
