### ISSUE TITLE
Direct links to servers and projects

### ISSUE THREAD

**Issue by ziajka** [GNS3/gns3-web-ui#646]
User should be able to construct direct link for given server and project in web-ui. 

Example:
`http://your-gns3-lab:gns3-lab-port/server/ip/port/project_id`

One of the implementation option is to provide handler for such URL format, during execution create new server (with given ip & port, if not exist) and redirect user to project_id.

**Comment by piotrpekala7** [comment]
I went through servers component & servers finder, we have other problems connected to server id e.g. user can't copy url and paste in incognito window (I know it won't be common use case). Right now I think protocol handler would be good option. We should definitely analyze it and if we make decision this task will be moved to gns3-webclient-pack

**Comment by ziajka** [comment]
It may be about storage. We may consider fall backing to a different browser-based solution. Nevertheless, we can implement it without supporting incognito mode.

**Comment by piotrpekala7** [comment]
1) Implementation using ng route for direct links
2) Another task for incognito mode

**Comment by piotrpekala7** [comment]
Will be fixed with https://github.com/GNS3/gns3-web-ui/pull/653
