### ISSUE TITLE
During adding the node customer is able to change the server where node should be located at

### ISSUE THREAD

**Issue by piotrpekala7** [GNS3/gns3-web-ui#652]

**Comment by piotrpekala7** [comment]
@grossmj please, give me your opinion if we should add dialog before adding node to map

**Comment by ziajka** [comment]
Good question, we need to make decision if it's useful for our users.

**Comment by piotrpekala7** [comment]
I decided to include option to choose where to run node in add node dialog

**Comment by piotrpekala7** [comment]
Will be fixed with https://github.com/GNS3/gns3-web-ui/pull/668
