### ISSUE TITLE
New disk interface and NIC models for Qemu VMs

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#670]
I have added a new disk interface type for Qemu VMs named "nvme"

![Screenshot from 2020-01-25 18-23-55](https://user-images.githubusercontent.com/4752614/73119656-19e55a80-3fa0-11ea-934b-89e40293a54b.png)

Also, I have added the following NIC models: `e1000-82544gc`, `e1000-82545em`, `e1000e` and `rocker`.

**Comment by piotrpekala7** [comment]
Will be fixed with https://github.com/GNS3/gns3-web-ui/pull/703

**Comment by piotrpekala7** [comment]
Fixed with https://github.com/GNS3/gns3-web-ui/pull/703
