### ISSUE TITLE
Symbols are displayed differently in recent versions of the Web-UI

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#672]
I have noticed a difference of how symbols are displayed in the web-ui. I am not sure when it really changed but I think this is between GNS3 version 2.2.2 and 2.2.5. Here is what I see for a simple project:

v2019.2.0-alpha.11

![Screenshot from 2020-01-25 18-33-48](https://user-images.githubusercontent.com/4752614/73119741-5c5b6700-3fa1-11ea-9a3d-5d24eb155701.png)

v2019.2.0-alpha.8dev

![Screenshot from 2020-01-25 19-11-54](https://user-images.githubusercontent.com/4752614/73120243-9f6c0900-3fa6-11ea-89df-105ed1adbe8e.png)

The latter is preferred.

**Comment by piotrpekala7** [comment]
Fixed with https://github.com/GNS3/gns3-web-ui/commit/e11281ddf650ce84ed4f8c4b6c479b02318821c9
