### ISSUE TITLE
System status improvements

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#675]
![Screenshot from 2020-01-30 18-06-49](https://user-images.githubusercontent.com/4752614/73440014-8ccd4780-438b-11ea-94fa-523261ff2259.png)

One question: is it possible to get new usage values without refreshing the entire page? It can be annoying that you scroll down the page and then it goes back up at the next refresh.

Also, please remove "percent" from each usage description since it is obvious they are percentage values (i.e "CPU usage percent" becomes just "CPU usage")

Finally, just a small detail but the separation between different server usage could be better. Maybe by adding more space between them?

![Screenshot from 2020-01-30 18-24-11](https://user-images.githubusercontent.com/4752614/73441320-c30bc680-438d-11ea-8aab-4a96b923aa1c.png)

**Comment by grossmj** [comment]
Do you think getting the usage values via a Websocket could be a better design?

**Comment by ziajka** [comment]
Makes a lot of sense to use WS here.

**Comment by piotrpekala7** [comment]
Fixed here https://github.com/GNS3/gns3-web-ui/pull/710,

> One question: is it possible to get new usage values without refreshing the entire page?

No, it's not possible. I decided to use circle progress - https://www.npmjs.com/package/ng-circle-progress to achieve the look that we have on mocks here: GNS3 Web UI system status, if we choose option to show animation, we have diagrams which are drawn from scratch (from zero coordinate). On the other hand, if we decide to decrease animation time to 0, we don't have smooth transition. Btw you can try also with https://stackblitz.com/edit/pie-chart-chartjs?file=src%2Fapp%2Fapp.component.ts or here https://stackblitz.com/edit/chartjs-doughnut-chart. In both cases unexpected 'refreshing effect' appears. I'm not able to detect why the view is marked for check in current implementation.

The second thing: I'm sure we can redraw only the data change on the pie chart (and it could be animated as you mentioned before) - unfortunately they don't do it in chart libraries like here in chart.js https://github.com/chartjs/Chart.js/blob/master/src/controllers/controller.doughnut.js#L101 (correct angle is calculated every time).
