### ISSUE TITLE
Built-in nodes cannot be added

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#677]
Builtin nodes (Ethernet switch, cloud, VPCS etc.) cannot be added from the web-ui. It works in the desktop Ui.

![Screenshot from 2020-01-30 18-54-59](https://user-images.githubusercontent.com/4752614/73443656-14b65000-4392-11ea-9892-08cd52132132.png)

![Screenshot from 2020-01-30 18-55-49](https://user-images.githubusercontent.com/4752614/73443713-2ac41080-4392-11ea-8385-dd5e7d3c2720.png)

**Comment by piotrpekala7** [comment]
fixed with https://github.com/GNS3/gns3-web-ui/commit/f40b2c64c21e7bf165e46135f864b208226771d6
