### ISSUE TITLE
Added nodes renamed to "Node-X"

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#678]
Nodes are renamed after moving them or automatically. This doesn't happen with the desktop ui.

![Screenshot from 2020-01-30 18-59-07](https://user-images.githubusercontent.com/4752614/73444099-dec59b80-4392-11ea-80ff-a4f625487932.png)

![Screenshot from 2020-01-30 19-01-46](https://user-images.githubusercontent.com/4752614/73444169-fdc42d80-4392-11ea-8d42-5ffb13ece394.png)

![Screenshot from 2020-01-30 18-59-22](https://user-images.githubusercontent.com/4752614/73444098-de2d0500-4392-11ea-8688-63ff7b55c0a9.png)

**Comment by piotrpekala7** [comment]
As we don't have possibility to update node name in another way I will disable functionality to change node name taken from template
