### ISSUE TITLE
Console port type is always undefined

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#679]
In the node information dialog:

![Screenshot from 2020-01-30 19-05-52](https://user-images.githubusercontent.com/4752614/73444746-31538780-4394-11ea-9797-ec4305e38491.png)

![Screenshot from 2020-01-30 19-07-54](https://user-images.githubusercontent.com/4752614/73444622-ea659200-4393-11ea-9fdd-89c087476538.png)

**Comment by piotrpekala7** [comment]
Fixed with https://github.com/GNS3/gns3-web-ui/commit/f6f7ceb627caccb73267c651e6ea190ee1fd6b7a
