### ISSUE TITLE
Node information dialog improvements

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#680]
The node information can be too small sometimes, especially for Qemu nodes where there can be a lot of information. Maybe we could allow the dialog to be resized or a least some scrollbars should be added like in the desktop interface.

![Screenshot from 2020-01-30 19-14-39](https://user-images.githubusercontent.com/4752614/73445110-f6058880-4394-11ea-8306-7157d1ad53ed.png)

![Screenshot from 2020-01-30 19-14-21](https://user-images.githubusercontent.com/4752614/73445112-f6058880-4394-11ea-9827-282cdcb720c6.png)

Another improvement: we should be able to see the command line information if the node has been started at least once. This node doesn't need to be started to see this.

![Screenshot from 2020-01-30 19-15-21](https://user-images.githubusercontent.com/4752614/73445109-f56cf200-4394-11ea-820a-1089219bfd2f.png)

**Comment by piotrpekala7** [comment]
Fixed with https://github.com/GNS3/gns3-web-ui/pull/709
