### ISSUE TITLE
Idea: save dialog positions/state

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#681]
Let's say an user moves the different dialogs around like this:

![Screenshot from 2020-01-30 19-20-39](https://user-images.githubusercontent.com/4752614/73445493-c4d98800-4395-11ea-9256-369618dc101d.png)

Then goes to the projects page and back, now the dialogs are back the their default positions.

![Screenshot from 2020-01-30 19-21-06](https://user-images.githubusercontent.com/4752614/73445492-c440f180-4395-11ea-9dc3-6a672c752d7a.png)

Should we implement a way to save and restore the dialog positions?

**Comment by piotrpekala7** [comment]
As we decided to locate console with tabs at the bottom and topology summary will be rewritten task is outdated
