### ISSUE TITLE
Create templates from appliances

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#682]
I may have missed something because I thought I already added this issue before.

The goal is to add new templates from appliances (local .gns3a files or from appliances list returned by the controller). Here is an example in the desktop GUI.

![Screenshot from 2020-01-30 19-32-25](https://user-images.githubusercontent.com/4752614/73446196-4b429980-4397-11ea-8e18-1819fd739a4e.png)

![Screenshot from 2020-01-30 19-26-45](https://user-images.githubusercontent.com/4752614/73446007-ef781080-4396-11ea-954a-f90906ccb712.png)

![Screenshot from 2020-01-30 19-27-04](https://user-images.githubusercontent.com/4752614/73446013-f43cc480-4396-11ea-976f-7a56c5eb4633.png)

![Screenshot from 2020-01-30 19-27-22](https://user-images.githubusercontent.com/4752614/73446060-0a4a8500-4397-11ea-85a4-785e4c7b9a9b.png)

![Screenshot from 2020-01-30 19-27-34](https://user-images.githubusercontent.com/4752614/73446066-0fa7cf80-4397-11ea-8f46-c03d1c777d76.png)

![Screenshot from 2020-01-30 19-27-44](https://user-images.githubusercontent.com/4752614/73446079-16364700-4397-11ea-8930-217678185e4a.png)

**Comment by piotrpekala7** [comment]
I think we have option to import .gns3a file

**Comment by grossmj** [comment]
> I think we have option to import .gns3a file

This doesn't seem to work properly. I only see an "Appliance successfully imported" message for every .gns3a I import. No questions about the location of disk images etc.

![Screenshot from 2020-01-31 14-22-03](https://user-images.githubusercontent.com/4752614/73517019-3ddbec80-4435-11ea-8f82-2478c5d880be.png)

Then I get the following error if I try to add the node based on this appliance:

![Screenshot from 2020-01-31 14-22-37](https://user-images.githubusercontent.com/4752614/73517018-3d435600-4435-11ea-8fb5-0f508b547af2.png)

More generally, I feel more should be done server side. Do you agree?

**Comment by piotrpekala7** [comment]
Will this require server-side changes?

**Comment by grossmj** [comment]
Yes I think we could make things easier by implementing something on server
side.

**Comment by piotrpekala7** [comment]
Ok, understand

**Comment by grossmj** [comment]
This is the current process to create a new template from an appliance.

**Step 1 - choose what appliance to install**

An appliance can be installed in two ways:

1. User provides the appliance file (.gns3a extension, downloaded from gns3.com or the GitHub registry)
2. User select an appliance from a list of appliances returned by the controller.

![Screenshot from 2020-01-30 19-26-45](https://user-images.githubusercontent.com/4752614/73446007-ef781080-4396-11ea-954a-f90906ccb712.png)

For option 1, we can go straight to step 2 below. For option 2 we need to display an appliance list so the user can select one.

Example: `http://localhost:3080/v2/appliances` returns all appliances known by the controller. Alternatively, the following request ask the controller to download all the appliances from our GitHub repository before returning the list: `http://localhost:3080/v2/appliances?update=yes` ("update from online repository" button in the desktop Ui).

Node that the JSON fields for each appliance are the same as in a .gns3a file.

To display a simple list of appliance: for each appliance in the list, retrieve the name and the symbol from corresponding fields.

The SVG symbol itself need to be downloaded using `http://localhost:3080/v2/symbols/<symbol_name>/raw`, for example `http://localhost:3080/v2/symbols/linux_guest.svg/raw`. A cache should be in place to avoid requesting the same symbols from the controller too many times.

![Screenshot from 2020-01-30 19-27-04](https://user-images.githubusercontent.com/4752614/73446013-f43cc480-4396-11ea-976f-7a56c5eb4633.png)

Other information like the product name, vendor, status, maintainer etc. can be retrieved to show in a detailed view.

![detailed_appliance_view](https://user-images.githubusercontent.com/4752614/75852267-8f640680-5e3b-11ea-8cfe-2cc671081a99.png)

**Step 2 - install the appliance**

Now we can install the appliance once it has been selected for installation or a .gns3a file has been imported.

Analyze the "versions" and "images" fields to show all versions of the appliance with the associated images (this is not needed for Docker appliances).

![Screenshot from 2020-03-04 17-25-00](https://user-images.githubusercontent.com/4752614/75853060-35fcd700-5e3d-11ea-9752-e06d32e2f7c6.png)

Then request GET `http://localhost:3080/v2/computes/<compute_id>/<appliance_type>/images` to check what images are already installed on a specific compute. Example: `http://localhost:3080/v2/computes/local/qemu/images`.

User has to provide the missing images via "import" for local files or download from the vendor website. MD5 and filesize are used to check if the files are the correct ones.

![Screenshot from 2020-03-04 17-34-47](https://user-images.githubusercontent.com/4752614/75853671-83c60f00-5e3e-11ea-8e1a-3ae4ca2a8365.png)

Once all missing files have been provided, the appliance can be installed. The missing files are then uploaded to the compute using POST `http://localhost:3080/v2/<appliance_type>/images/<image_name>`. Example: `http://localhost:3080/v2/qemu/images/asav992.qcow`.

Finally, the usage information is shown:

![Screenshot from 2020-03-04 17-37-26](https://user-images.githubusercontent.com/4752614/75854146-69406580-5e3f-11ea-9a4d-e2cbf993c38e.png)

**Step 3 - create the template**

Based on the appliance info, a new template can be created. Currently this is done on the UI side in https://github.com/GNS3/gns3-gui/blob/master/gns3/dialogs/appliance_wizard.py#L578L579
and https://github.com/GNS3/gns3-gui/blob/master/gns3/registry/appliance_to_template.py

I think we could add a new endpoint to automate this part on the server.

**Comment by grossmj** [comment]
We could also save some steps if we implement https://github.com/GNS3/gns3-server/issues/1552

**Comment by piotrpekala7** [comment]
I'm working on this task here: https://github.com/GNS3/gns3-web-ui/tree/Create-templates-from-appliances

**Comment by piotrpekala7** [comment]
It probably won't be added in next release

**Comment by grossmj** [comment]
You are right, this is too big to be included in the next release. That's fine, this isn't the most important for now.

**Comment by piotrpekala7** [comment]
pr: https://github.com/GNS3/gns3-web-ui/pull/884

**Comment by piotrpekala7** [comment]
questions on pr

**Comment by piotrpekala7** [comment]
?

**Comment by grossmj** [comment]
I am going to review this soon.

**Comment by piotrpekala7** [comment]
fixed in https://github.com/GNS3/gns3-web-ui/commit/e7dfa6242b97704fb89469c6ffb9ddfadef10baf

**Comment by piotrpekala7** [comment]
This task is not tested and I know that there may be bugs and some improvements may be needed, and I propose to open next tasks with this topic in separate threads
