### ISSUE TITLE
Show more information for HTTP errors

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#724]
For instance a request to this endpoint `v2/projects/ae3e2489-6c7c-4518-9950-b3c9bc4b0489/open` returns an (expected) 409 error. The JSON content returned is the following:

```
{
    "message": "Cannot connect to compute 'Docker server' with request POST /projects",
    "status": 409
}
```
An error is shown like this in the web-ui:

![Screenshot from 2020-03-03 16-53-09](https://user-images.githubusercontent.com/4752614/75748618-dab0e300-5d6f-11ea-84bd-7854114c553b.png)

It would be great to add the content of the `message` field if existing to the error page.

Another example when starting a VPCS node with the VPCS binary not executable with the API request `v2/compute/projects/0318f9f3-2c3d-4a2a-91c9-c97abb43b79b/vpcs/nodes/4c348e3d-8a61-4572-a8c7-fbf695b78196/start`

An error popup is shown in the web-ui (which could be displayed for a longer time by the way...)

![Screenshot from 2020-03-03 17-05-42](https://user-images.githubusercontent.com/4752614/75749478-d685c500-5d71-11ea-88fa-067588bc3c6f.png)

The actual returned JSON content is:

```
{
    "exception": "VPCSError",
    "message": "No path to a VPCS executable has been set",
    "status": 409
}
```
Same as above, it would be nice to add the error information to the popup.

**Comment by piotrpekala7** [comment]
Fixed with https://github.com/GNS3/gns3-web-ui/commit/2b45f7a6434b6d01608505be9736a49ab54d7ab2
