### ISSUE TITLE
Icons are displayed with wrong colors in 'change symbol' dialog

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#725]
![Screenshot from 2020-03-03 17-16-36](https://user-images.githubusercontent.com/4752614/75749883-c8847400-5d72-11ea-8cbe-6f8768460e00.png)

You can see that the PC3 symbol has not the same color as the one listed in the change symbol dialog (top right). This is Linux with Chrome.

**Comment by piotrpekala7** [comment]
Fixed with https://github.com/GNS3/gns3-web-ui/commit/ae540777a4118e02c01f62635a348b1f75b50041
