### ISSUE TITLE
Show interface availability 

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#727]
Adding a link to a node with no available interface shows an empty drop down list.

![Screenshot from 2020-03-03 17-42-27](https://user-images.githubusercontent.com/4752614/75751578-ba385700-5d76-11ea-8dbb-0069059fc82f.png)

I think all interfaces should be displayed like in the desktop Ui and red/green icons should be used to indicate availability.

![select_interface](https://user-images.githubusercontent.com/4752614/75751901-8447a280-5d77-11ea-9fd3-8336bdf5c261.png)

**Comment by grossmj** [comment]
This problem is also listed in the UX review.

**Comment by piotrpekala7** [comment]
Fixed with https://github.com/GNS3/gns3-web-ui/commit/34059da0f6e084892c896aef35ec498255f77ac8
