### ISSUE TITLE
Size suffixes should be displayed

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#728]
In all template and node settings, appropriate suffixes should be displayed. For example "MB" should be added for the RAM setting for Qemu templates:

![Screenshot from 2020-03-03 18-20-17](https://user-images.githubusercontent.com/4752614/75754712-1605de80-5d7d-11ea-9d31-324e910583e6.png)

![Screenshot from 2020-03-03 18-22-05](https://user-images.githubusercontent.com/4752614/75754711-14d4b180-5d7d-11ea-8888-9ad242efa399.png)

![Screenshot from 2020-03-03 18-29-01](https://user-images.githubusercontent.com/4752614/75754703-12725780-5d7d-11ea-8ad7-641393434e47.png)

**Comment by piotrpekala7** [comment]
Fixed with https://github.com/GNS3/gns3-web-ui/commit/117e67ed33354d9e4160a76a1574a4549d2a3751
