### ISSUE TITLE
Bring to front

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#729]
I noticed that the "bring to front" feature sets an object layer to 100. Wouldn't it be better to check what is the highest existing layer for all objects and set the layer of the selected item to this value + 1?

![Screenshot from 2020-03-03 18-50-43](https://user-images.githubusercontent.com/4752614/75756105-f4f2bd00-5d7f-11ea-99ec-9ebb8d597969.png)

**Comment by piotrpekala7** [comment]
Fixed with https://github.com/GNS3/gns3-web-ui/commit/1622d7d60a5d34b185ad42cc8f2ed5803f0f7e4c
