### ISSUE TITLE
Error message when creating Qemu VM template

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#731]
The error "Cannot read property 'path' of undefined" is shown if I forget to select the Qemu binary in the option. We should have a more user friendly message.

![Screenshot from 2020-03-04 17-18-45](https://user-images.githubusercontent.com/4752614/75852597-49f40900-5e3c-11ea-9d9e-df820768af93.png)

**Comment by piotrpekala7** [comment]
fixed with https://github.com/GNS3/gns3-web-ui/commit/f6f7ceb627caccb73267c651e6ea190ee1fd6b7a
