### ISSUE TITLE
Uncaught exception when going back to project

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#732]
I got it when I click to "Back to project" and the server is shutdown

![Screenshot from 2020-03-04 18-57-08](https://user-images.githubusercontent.com/4752614/75859507-0c967800-5e4a-11ea-9002-46ca24326b61.png)

**Comment by piotrpekala7** [comment]
You mean text in toast message is not wrapped?

**Comment by grossmj** [comment]
An "Server is unreachable" message should be displayed like in other part of the web ui.

**Comment by piotrpekala7** [comment]
ok, you mean not to show the full message

**Comment by piotrpekala7** [comment]
Fixed with https://github.com/GNS3/gns3-web-ui/commit/ac3335a33df5df712d851026ea066023e6dff94c
