### ISSUE TITLE
Use Snyk instead of greenkeeper.io

### ISSUE THREAD

**Issue by ziajka** [GNS3/gns3-web-ui#747]
"We’ll stop Greenkeeper’s operation as an independent service on June 3rd, 2020. For your dependency update needs, we have a brilliant alternative for you: Snyk. "

greenkeeper.io

**Comment by piotrpekala7** [comment]
I added proper comment on confluence page, the only question is if we should get approval to use it?

**Comment by grossmj** [comment]
Just configured Snyk. I think it should be fine now.
