### ISSUE TITLE
Default filename while taking a screenshot

### ISSUE THREAD

**Issue by ziajka** [GNS3/gns3-web-ui#771]
We can support default filename while taking a screenshot:

![image](https://user-images.githubusercontent.com/29223277/78156707-70a75e80-743f-11ea-8a56-be0c0c573c74.png)

**Comment by piotrpekala7** [comment]
Fixed with https://github.com/GNS3/gns3-web-ui/commit/24fffafbf150560f71f8fda78fc5635522b9c711
