### ISSUE TITLE
Animation in "Show node information" dialog

### ISSUE THREAD

**Issue by ziajka** [GNS3/gns3-web-ui#772]
We may consider not using animation when switching tabs in "Show node information"

![image](https://user-images.githubusercontent.com/29223277/78157029-caa82400-743f-11ea-925a-42c1c304f485.png)

**Comment by piotrpekala7** [comment]
Fixed with https://github.com/GNS3/gns3-web-ui/commit/f71af8c57cb360635868bd21fe1a3c6a9e7af693
