### ISSUE TITLE
Smaller margin (top/bottom) in context menu

### ISSUE THREAD

**Issue by ziajka** [GNS3/gns3-web-ui#773]
We may want to consider a smaller margin (top/bottom) in the context menu.
![image](https://user-images.githubusercontent.com/29223277/78157255-0b07a200-7440-11ea-9211-164a63fbec09.png)

**Comment by piotrpekala7** [comment]
In my opinion we should **not** override default values from angular material components

**Comment by ziajka** [comment]
Do we have other ability to change that margin?

**Comment by piotrpekala7** [comment]
@ziajka According to my knowledge, we don't have that option. The only way is to override the style / set negative margins

**Comment by ziajka** [comment]
In my option we should present it in a nicer way, I don't like idea of modifying styles but probably that's the way.

**Comment by piotrpekala7** [comment]
Ok, it's up to you

**Comment by piotrpekala7** [comment]
makes no sense as angular 9.1 bring updates in material design
