### ISSUE TITLE
[Object object] during changing the Log Level to Warning

### ISSUE THREAD

**Issue by ziajka** [GNS3/gns3-web-ui#774]
I'm getting [Object object] during changing the Log Level to Warning in GNS3 Console. It doesn't happen to different log levels. 

![image](https://user-images.githubusercontent.com/29223277/78157468-4904c600-7440-11ea-87ff-0b8dca568fb3.png)

**Comment by piotrpekala7** [comment]
I can't reproduce the problem based on this description

**Comment by ziajka** [comment]
Closed for now.
