### ISSUE TITLE
Update to 2020 in the footer

### ISSUE THREAD

**Issue by ziajka** [GNS3/gns3-web-ui#775]
We may consider having an automatic script (during the release) which does that.

![image](https://user-images.githubusercontent.com/29223277/78158081-18715c00-7441-11ea-8b99-e2e8b06ceb05.png)

**Comment by piotrpekala7** [comment]
Fixed with https://github.com/GNS3/gns3-web-ui/commit/f722872a9445de55619ba25bb386f844d1384794
