### ISSUE TITLE
Console window position

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#780]
The position of the console window on my 13,3 inch laptop monitor isn't great as it overlaps the project toolbar.

![Screenshot from 2020-04-03 17-13-37](https://user-images.githubusercontent.com/4752614/78332137-f4dc1c00-75ce-11ea-9106-7b9994390228.png)

Maybe it would be better to have a bottom pane that can be resized or completely collapsed. Similar to this in the desktop ui (but with the tabs at the top).

![Screenshot from 2020-04-03 17-16-49](https://user-images.githubusercontent.com/4752614/78332275-3a98e480-75cf-11ea-90af-fcfbcfe2fc09.png)

Another example with VIRL2:

https://youtu.be/sW5-jHLygFg?t=1796

An advantage of this is we can maybe add more tabs later on, for instance "Project notes"...

**Comment by piotrpekala7** [comment]
From mail converstion:

> Option to resize is available on branch https://github.com/GNS3/gns3-web-ui/tree/HTML5-console-support. Unfortunately current implementation of resizing widget doesn't work properly due to problems related do this package: https://www.npmjs.com/package/xterm-addon-fit. We are not able to reduce the window size at this time without affecting the proper console behavior. This should definitely be done in the future.

**Comment by piotrpekala7** [comment]
@ziajka @grossmj We need a quick decision on how to work around this problem, because we cannot solve it in the near future

**Comment by grossmj** [comment]
@piotrpekala7 I would say hide the window by default. Users will have to use the "HTTP console in a tab" feature in the meantime.

**Comment by piotrpekala7** [comment]
@ziajka ?

**Comment by ziajka** [comment]
![image](https://user-images.githubusercontent.com/29223277/79208532-71c68b80-7e42-11ea-850a-4bb460318f42.png)

**Comment by ziajka** [comment]
![image](https://user-images.githubusercontent.com/29223277/79208753-c7029d00-7e42-11ea-9f4b-8e8b009ffa86.png)

**Comment by ziajka** [comment]
Idea to discuss in the future: bottom bar that allows opening the console (like in the current GUI).

For now:
- Minimize the window ability
- Minimized on default

**Comment by piotrpekala7** [comment]
Widget is minimized at start https://github.com/GNS3/gns3-web-ui/commit/1199dedc2321e185a72a9b532d55b6fc19501525

**Comment by piotrpekala7** [comment]
In the case of minimizing the widget, there is a problem how to react to the opening of a new console for node when the console wrapper is not attached to the document?

**Comment by piotrpekala7** [comment]
The same problem appears here https://github.com/GNS3/gns3-web-ui/issues/781

**Comment by piotrpekala7** [comment]
@grossmj @ziajka please check, I need information if something needs improvement

**Comment by ziajka** [comment]
Maybe we could use "hidden" feature, it should allow attaching to the DOM,

**Comment by piotrpekala7** [comment]
Unfortunately, this is not a solution to this problem. We use hidden https://github.com/GNS3/gns3-web-ui/blob/master/src/app/components/project-map/console-wrapper/console-wrapper.component.html#L51.

**Comment by piotrpekala7** [comment]
` <app-web-console [hidden]="!(selected.value===(index+1))" [server]="server" [node]="nodes[index]"></app-web-console>`

**Comment by piotrpekala7** [comment]
Option to minimize added in https://github.com/GNS3/gns3-web-ui/commit/c23892f836848c9bf559d7b843cb2583ea7e5872

**Comment by piotrpekala7** [comment]
Next features will be delivered in https://github.com/GNS3/gns3-web-ui/issues/837
