### ISSUE TITLE
Web console tab issues

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#781]
There should be a button to "Web console to all nodes". One workaround is to select all the nodes and then use the contextual menu however this doesn't work well. Only the console for the last node opens correctly (PC3 in this example), other consoles show a black square.

![Screenshot from 2020-04-03 17-43-48](https://user-images.githubusercontent.com/4752614/78334141-c2ccb900-75d2-11ea-82d9-7289bbb2ada6.png)

Another problem is if I open web consoles and then go back the projects page and then come back to the previously opened project, all the web console tabs are gone.

**Comment by piotrpekala7** [comment]
The xterm console is attached to the HTML element: https://github.com/GNS3/gns3-web-ui/blob/master/src/app/components/project-map/web-console/web-console.component.ts# L38. We actually manage the visibility of https://github.com/GNS3/gns3-web-ui/blob/master/src/app/components/project-map/console-wrapper/console-wrapper.component.html#L51. We are unable to provide support for opening the console for many nodes.

**Comment by piotrpekala7** [comment]
Option to open console for many some nodes at once disabled

**Comment by grossmj** [comment]
> We are unable to provide support for opening the console for many nodes.

Is this something that can be done in the future?

**Comment by piotrpekala7** [comment]
Xterm.js console is attached to the DOM -> https://github.com/xtermjs/xterm.js/blob/master/src/public/Terminal.ts#L48. We have no influence on this, the solution is to create a separate branch with xterm and modify their terminal to meet our needs.

**Comment by grossmj** [comment]
Do you think we can write a PR to make a change upstream, to the Xterm.js repository?

**Comment by piotrpekala7** [comment]
@ziajka Could you help with estimating this task?

**Comment by piotrpekala7** [comment]
From my investigation open function is called on HTML element so open function need to be rewritten: https://github.com/xtermjs/xterm.js/blob/master/src/public/Terminal.ts#L63, This is possible, but I cannot estimate and plan it without any support

**Comment by piotrpekala7** [comment]
Warning before navigating to another project while consoles are open added in https://github.com/GNS3/gns3-web-ui/commit/8da44071099e35969401057506cf6ed2f74b1c6b

**Comment by piotrpekala7** [comment]
Next features will be delivered in https://github.com/GNS3/gns3-web-ui/issues/837
