### ISSUE TITLE
Leverage GA to get useful stats

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#782]
In addition of the standard GA stats, it would be useful to get the following information:

1. How long people use the software.
2. Which appliance, vendors are used.
3. Maybe some other useful stats that could be relevant for marketing purposes?

Regarding 1, we already do it in the desktop interface: we start a timer when the GUI is launched and then the time spent in the software is sent to GA using an GA event when the application is closed. 

Using tags could be an alternative to sending events... I am not an GA expert, maybe we already have everything we need in GA and this is just a matter of generating reports from there?

**Comment by piotrpekala7** [comment]
firstly, I added some 'code' fixes https://github.com/GNS3/gns3-web-ui/commit/26153aa0e77d6dd9e49d7ea196dfdb830bd24f6c, https://github.com/GNS3/gns3-web-ui/commit/6d023828ec01b9ad762da693bca78322060a8700

**Comment by piotrpekala7** [comment]
I will try to answer the rest of the information in an e-mail

**Comment by piotrpekala7** [comment]
we are waiting for more information from marketing

**Comment by piotrpekala7** [comment]
for the last year no one asked for any additional information so this task can be closed
