### ISSUE TITLE
Allow copy/paste for HTML5 console

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#786]
The HTML5 console should support copy and paste.

**Comment by piotrpekala7** [comment]
In this commit https://github.com/GNS3/gns3-web-ui/commit/71c1798152840addaa1215bc4ad65d09885f9895 I stop propagation of the event so now it's  handled by terminal not by application. It should work in most of cases

**Comment by piotrpekala7** [comment]
Genrally xterm give us option to copy paste by clicking insert https://github.com/xtermjs/xterm.js/issues/2478

**Comment by piotrpekala7** [comment]
Moreover in some cases only ctrl+shift+v will work https://github.com/xtermjs/xterm.js/issues/292

**Comment by piotrpekala7** [comment]
More limitations are included in this post: https://github.com/xtermjs/xterm.js/issues/1411

**Comment by grossmj** [comment]
Works with the shortcuts: CTRL+C, CTRL+V
