### ISSUE TITLE
Drag & drop to add new nodes

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#787]
We need to simplify how nodes are added to the projects.

![image](https://user-images.githubusercontent.com/4752614/78775367-43295a80-79d5-11ea-8c15-fd619052e8d2.png)

One of the best way is to just drag & drop similar to what VIRL2 does: https://youtu.be/sW5-jHLygFg?t=1796

**Comment by ziajka** [comment]
As discussed: 

![image](https://user-images.githubusercontent.com/29223277/79204807-6ae94a00-7e3d-11ea-903d-a41989983b1e.png)

**Comment by piotrpekala7** [comment]
![S4](https://user-images.githubusercontent.com/31202938/79620085-111fa300-810f-11ea-95eb-70586980998d.JPG)
Should I improve sth?

**Comment by piotrpekala7** [comment]
@grossmj @ziajka I am kindly asking you for any feedback

**Comment by piotrpekala7** [comment]
I created a base solution https://github.com/GNS3/gns3-web-ui/tree/Drag-%26-drop-to-add-new-nodes

**Comment by piotrpekala7** [comment]
@grossmj @ziajka please check, I need information if something needs improvement

**Comment by piotrpekala7** [comment]
there is a slight displacement of the node after adding because it does not take into account where the template was clicked and I do not know the size of its icon

**Comment by grossmj** [comment]
> @grossmj @ziajka please check, I need information if something needs improvement

I would maybe have something a bit more similar to https://github.com/GNS3/gns3-web-ui/issues/787#issuecomment-613310467, a bit like a panel. Let's discuss this during our next meeting. Also, I would have it a bit bigger because I feel the list is small on my side (I can only see 3 templates at the same time).

![Screenshot from 2020-04-28 16-31-25](https://user-images.githubusercontent.com/4752614/80457055-ceab6100-896d-11ea-9097-ad8ae6ff819c.png)

Another thing, can we use the template name to drag it to the canvas? (similar behavior as in the desktop Ui)

> there is a slight displacement of the node after adding because it does not take into account where the template was clicked and I do not know the size of its icon

This seems fine.

**Comment by piotrpekala7** [comment]
resizing:
https://stackoverflow.com/questions/51325930/how-to-increase-the-width-of-the-mat-menu-item

**Comment by ziajka** [comment]
As discussed, two steps:
1) Make icons smaller
2) Ability to resize (maybe during another task)
![image](https://user-images.githubusercontent.com/29223277/80465173-22508700-893b-11ea-8c72-16fabf3d28aa.png)

**Comment by piotrpekala7** [comment]
![Capture](https://user-images.githubusercontent.com/31202938/81284105-f7aeae80-905d-11ea-9a54-32c93d717c79.JPG)

fixed

**Comment by piotrpekala7** [comment]
bug fixes in https://github.com/GNS3/gns3-web-ui/issues/840
