### ISSUE TITLE
Add tooltips for the zoom in / zoom out toolbar

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#788]
![image](https://user-images.githubusercontent.com/4752614/78776289-c4352180-79d6-11ea-8b64-77c424a58c16.png)

**Comment by piotrpekala7** [comment]
Added in https://github.com/GNS3/gns3-web-ui/commit/e85fb93923679a163675264bd09acaa4f7c8053a

**Comment by piotrpekala7** [comment]
I added following tooltips: zoom in, reset zoom, zoom out, ready for check

**Comment by grossmj** [comment]
Fixed, thanks!
