### ISSUE TITLE
Error when clicking on "Fit in view"

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#789]
![image](https://user-images.githubusercontent.com/4752614/78776413-fa72a100-79d6-11ea-8299-567c46e0aab2.png)

**Comment by piotrpekala7** [comment]
Fixed in https://github.com/GNS3/gns3-web-ui/commit/0bcc662d91d4f3705966588ec20a740d9eafdf13

**Comment by piotrpekala7** [comment]
tested on Chrome and FF, windows platform

**Comment by grossmj** [comment]
Fixed, thanks!
