### ISSUE TITLE
Ad should not be displayed over and over again

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#790]
![image (1)](https://user-images.githubusercontent.com/4752614/78777123-23dffc80-79d8-11ea-9d10-0a4066d0ad04.png)

**Comment by piotrpekala7** [comment]
I save information if ad was showed in local storage, so now it appears once -> https://github.com/GNS3/gns3-web-ui/commit/33c35308f96288f86ec8decbf59fa6faea35f3e3

**Comment by grossmj** [comment]
Do you mean the ad won't be displayed next time a user loads the web-ui? What if this is an ad for a different product for instance?

**Comment by piotrpekala7** [comment]
Yes, this ad will only show once.

**Comment by piotrpekala7** [comment]
If specific behavior is needed, e.g. display only 5 times or display once a day, please describe the exact requirements

**Comment by grossmj** [comment]
Once a day is reasonable I think. We can adjust later.

**Comment by piotrpekala7** [comment]
Changed to one day in commit: https://github.com/GNS3/gns3-web-ui/commit/3f4bb0b1724f6c038f126567be12130351da3fa5

**Comment by grossmj** [comment]
Seems to work :+1:
