### ISSUE TITLE
Issues with server detection

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#791]
I opened a project in Chrome, the URL is `http://172.16.9.128:3080/static/web-ui/server/1/project/72f3db56-138f-4565-9c4b-0eba0346873a`

Then I open a Firefox browser and paste the URL there. I get the following error:

![Screenshot from 2020-04-08 20-31-18](https://user-images.githubusercontent.com/4752614/78777820-635b1880-79d9-11ea-8054-b2a8b5681948.png)

If I navigate to `172.16.9.128:3080/static/web-ui/bundled` first then I can paste that URL without any problem, even the next time I open Firefox. However, I get the same error if I clear the browser data and then that URL again.

I get the following error when trying to use the web-ui in private mode on Firefox. This seems to work on well Chrome.

![Screenshot from 2020-04-08 20-47-44](https://user-images.githubusercontent.com/4752614/78778305-3a875300-79da-11ea-97eb-48146dc9ea29.png)

**Comment by piotrpekala7** [comment]
The server id is saved in the browser's memory. Therefore, copying the URL to another browser or to the incognito tab is not supported.

**Comment by piotrpekala7** [comment]
In this commit https://github.com/GNS3/gns3-web-ui/commit/e7766ec708f4c6b12b329243eb26fc7290149400 I updated project map guard to navigate to servers page if server is not added so now in this situation you should be redirected to servers page. Tested on Chrome and Firefox

**Comment by grossmj** [comment]
> The server id is saved in the browser's memory. Therefore, copying the URL to another browser or to the incognito tab is not supported.

Is there a way to show a more explicit warning message in that situation?

**Comment by piotrpekala7** [comment]
Yes, I updated project map guard to navigate directly to servers page if server with this id doesn't exist. Marked as waiting for more information for you to check. We can navigate to error page of show toast on blank page if you prefer it

**Comment by grossmj** [comment]
> Yes, I updated project map guard to navigate directly to servers page if server with this id doesn't exist.

I tested and I confirm this works well on both Firefox and Chrome :+1: 

Only problem left is I get an error message if I open the web-ui in private mode on Firefox. I have no problem with Chrome, does Chrome handle private mode differently than Firefox?

![Screenshot from 2020-04-12 14-14-52](https://user-images.githubusercontent.com/4752614/79060766-3bfd9780-7cc8-11ea-93b1-8ae4a4ea4070.png)

**Comment by piotrpekala7** [comment]
@grossmj I found that IndexedDB is **not supported in Firefox** in private window https://bugzilla.mozilla.org/show_bug.cgi?id=781982. We should avoid creating db in that case, unfortunately from stackoverflow:  _Google is remove the ability to detect Private Browsing Mode permanently in Chrome 76 onwards. So, if you're wanting to detect private browsing it's now impossible._ @ziajka What can we do about it?

**Comment by ziajka** [comment]
@ziajka we may detect if indexed is created and based on that information we may fallback to a different solution.

**Comment by piotrpekala7** [comment]
I was looking for alternatives to client db storage in private browsing mode, from this point https://stackoverflow.com/questions/53607326/alternatives-to-client-db-storage-in-private-browsing-mode I find https://www.npmjs.com/package/local-storage-fallback but it's nothing more than local storage

**Comment by ziajka** [comment]
It should be fine, we don't store much of the data. It's still a fallback.

**Comment by piotrpekala7** [comment]
This is not a problem of the size of the data, but of how to read and write and process it. 
- Local storage can only save strings, so storing objects requires that they be turned into strings using JSON.stringify - you can’t ask local storage to store an object directly because it’ll store “[object Object]”
- It's not about creating alternative version for get method https://github.com/GNS3/gns3-web-ui/blob/master/src/app/services/server.service.ts#L21 but injecting another version of server service and creating common interface, then it should applied to ServerFinder, AddServerDialog, ServerDiscoveryComponent, GNS3VMComponent, BundledServerFinderComponent and 'preferences services'
If so, what's the point of keeping IndexedDb at all? 

We have try to decrease loading time by introducing guards https://github.com/GNS3/gns3-web-ui/blob/master/src/app/guards/project-map-guard.ts#L20. I have big concerns about application performance in the context of proposed changes. Am I wrong?

**Comment by piotrpekala7** [comment]
@grossmj @ziajka I am kindly asking you for any feedback

**Comment by ziajka** [comment]
Great points. Now we have more touching points. The alternative is to disable access to Web-UI in incognito mode or maybe we can just provide "In Memory" - only accessible from the given tab because of no sharing. What do you think?

**Comment by piotrpekala7** [comment]
'In memory' -> if you mean application memory we will receive questions from community like these: why the behavior is different in incognito mode and normal mode? after refreshing page...? etc.

**Comment by piotrpekala7** [comment]
we can disable access but only for browsers **but only for browsers that do not support our way of storing data** as I know it's only FF in incognito mode

**Comment by piotrpekala7** [comment]
@grossmj Do you agree with this or do you have another idea?

**Comment by ziajka** [comment]
@piotrpekala7 yes, we can potentially get that feedback from community.

If using local storage && stringify it should be fine. We can try to find lib that could do that abstraction for us, if there is not then we could try to implement. IndexedDb is better performant and that's what we want to offer.

**Comment by piotrpekala7** [comment]
> @piotrpekala7 yes, we can potentially get that feedback from community.

I browse user questions every day now so I'm sure we will have to explain it

> If using local storage && stringify it should be fine. 

I maintain my recommendation. In addition, bugs should be removed before the release in May, but if we treat it as functionality, I rate the priority as very low

> We can try to find lib that could do that abstraction for us, if there is not then we could try to implement. 

I mentioned sample lib above. You can check if it suits what you need

> I was looking for alternatives to client db storage in private browsing mode, from this point https://stackoverflow.com/questions/53607326/alternatives-to-client-db-storage-in-private-browsing-mode I find https://www.npmjs.com/package/local-storage-fallback but it's nothing more than local storage

**Comment by grossmj** [comment]
> @grossmj Do you agree with this or do you have another idea?

I agree with this but if the lib mentioned above can be used that would be great.

So for now I would disable access and then later see if the lib can allow us to support FF incognito mode (low priority).

**Comment by piotrpekala7** [comment]
will be fixed in https://github.com/GNS3/gns3-web-ui/pull/889

**Comment by piotrpekala7** [comment]
Important! **changes in server detection**

**Comment by grossmj** [comment]
Now I can use the web-ui in incognito mode with FireFox :+1: 

However there is still an issue if I copy / paste this kind of URL: `http://localhost:4200/server/2/project/70c6dd23-f2da-41a5-b5d5-5e62e91f1754`

With Firefox:

![Screenshot from 2020-06-15 20-21-09](https://user-images.githubusercontent.com/4752614/84649873-6e38a900-af46-11ea-9bbd-a23c82279fb8.png)

With Chrome:

![Screenshot from 2020-06-15 20-24-43](https://user-images.githubusercontent.com/4752614/84649885-7395f380-af46-11ea-8dc7-897354048d19.png)

**Comment by piotrpekala7** [comment]
Unfortunately this doesn't work with latest Chrome version in incognito mode

**Comment by piotrpekala7** [comment]
when it comes to issue from screenshots; value from ServerService is checked before initialization in ProjectMapGuard and probably there is no option to solve it in current implementation -> according to following links:
https://github.com/angular/angular/issues/21702
https://github.com/angular/angular/issues/14279

**Comment by piotrpekala7** [comment]
I provided fix for private mode in Chrome browser https://github.com/GNS3/gns3-web-ui/commit/edb7aefba26efa1e1c6b9da98cb640d0903ed5ed

**Comment by piotrpekala7** [comment]
ProjectMapGuard doesn't work as expected also I notice that we should check if server exists for projects page

**Comment by piotrpekala7** [comment]
Fix for ProjectMap page -> https://github.com/GNS3/gns3-web-ui/commit/0f4890fd10d661f92d5bdf4090d1681262b8824d

**Comment by piotrpekala7** [comment]
Fix for console in new tab -> https://github.com/GNS3/gns3-web-ui/commit/6d0f41714a7b97b92d16329a5e5011f10d4ab741

**Comment by piotrpekala7** [comment]
code cleaned up -> https://github.com/GNS3/gns3-web-ui/commit/e853849cc913f02ba3284592758a1680935467cf

**Comment by piotrpekala7** [comment]
tested in Chrome, Chrome in private mode, Firefox, Firefox in private mode

**Comment by piotrpekala7** [comment]
please let me know if I missed sth

**Comment by grossmj** [comment]
> tested in Chrome, Chrome in private mode, Firefox, Firefox in private mode

Tested as well and everything works as expected. Thanks :+1:
