### ISSUE TITLE
Adding a built-in node leads to an error

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#792]
With the web-ui running in the GNS3 VM:

A user tries to add a built-in node and select to run it on the "vm"

![image (1)](https://user-images.githubusercontent.com/4752614/78779097-825aaa00-79db-11ea-9ecc-93c171e822ab.png)

Then this error is displayed.

![image](https://user-images.githubusercontent.com/4752614/78779111-88508b00-79db-11ea-81e7-188c0e179eec.png)

I think "local" should be the default in this case, especially when the GNS3 VM is not configured in the preferences.

![Screenshot from 2020-04-08 20-50-14](https://user-images.githubusercontent.com/4752614/78779027-68b96280-79db-11ea-9fab-8473af31b2df.png)

**Comment by piotrpekala7** [comment]
Fix in https://github.com/GNS3/gns3-web-ui/commit/9a33b28576f813f196cc8f0e27e8bbaf4b10b811

**Comment by piotrpekala7** [comment]
When user choose one of built-in templates (ethernet switch, ethernet-hub, cloud) local will be default, if gns3 vm is not configured user will receive error that it needs configuration

**Comment by piotrpekala7** [comment]
tested on ff & chrome

**Comment by grossmj** [comment]
Tested and everything seems good :+1:
