### ISSUE TITLE
Cannot add additional links to nodes

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#795]
Bug described in https://gns3.com/community/discussion/gns3-web-interface-2

I confirm the bug too, I cannot add more links to already connected Qemu VMs... possibility to other node types.

![Screenshot from 2020-04-09 14-16-46](https://user-images.githubusercontent.com/4752614/78858867-c9dd4680-7a6c-11ea-8073-764adc5bf47d.png)

**Comment by piotrpekala7** [comment]
@ziajka Probably this line https://github.com/GNS3/gns3-web-ui/commit/34059da0f6e084892c896aef35ec498255f77ac8#diff-b40cdecf82e9cebd56b024f4d597bab9R59 is a problem, can you check what's wrong here?

**Comment by piotrpekala7** [comment]
@grossmj @ziajka I am kindly asking you for any feedback

**Comment by grossmj** [comment]
> Should I compare adapter number?

This might be the problem here, you must make sure that the port number for a given adapter number is available.

Reminder: an adapter can contain multiple ports. For example a node can have an Ethernet adapter with 4 ports and another Serial adapter with only one port.

**Comment by piotrpekala7** [comment]
![refBugAdapters](https://user-images.githubusercontent.com/31202938/80619648-47312100-8a45-11ea-9a5e-91caf9a2bbbb.JPG)

I checked for several cases and it works fine

**Comment by grossmj** [comment]
I still get the issue, for example between Qemu nodes or Docker nodes.

![Screenshot from 2020-05-06 18-46-34](https://user-images.githubusercontent.com/4752614/81160967-f633a680-8fc9-11ea-8348-01c1e2cf0ef2.png)

**Comment by piotrpekala7** [comment]
@ziajka Can you help fix it today cause it blocks our release?

**Comment by piotrpekala7** [comment]
This method https://github.com/GNS3/gns3-web-ui/blob/master/src/app/components/project-map/node-select-interface/node-select-interface.component.ts#L47 seems to be wrong

**Comment by piotrpekala7** [comment]
The filter mechanism was not changed in this commit https://github.com/GNS3/gns3-web-ui/commit/34059da0f6e084892c896aef35ec498255f77ac8#diff-b40cdecf82e9cebd56b024f4d597bab9R59

**Comment by piotrpekala7** [comment]
Did it work incorrectly from the beginning?

**Comment by grossmj** [comment]
I remember it was working in earlier versions of the Web-Ui

**Comment by piotrpekala7** [comment]
Ok, so I'll roll back these changes to a separate branch for review

**Comment by piotrpekala7** [comment]
Changes undone, return to original version https://github.com/GNS3/gns3-web-ui/commit/449c8a97db68266130830ecfde4386df63253d42

**Comment by grossmj** [comment]
Unfortunately no. Removing all links then trying to add one is showing multiple links etc. or no interfaces showing up in the menu. All in all, this is very buggy.

![Screenshot from 2020-05-06 19-55-22](https://user-images.githubusercontent.com/4752614/81166998-9e01a200-8fd3-11ea-97e9-e30eb94b40cb.png)

**Comment by piotrpekala7** [comment]
We have confirmation that this functionality has been working incorrectly from the beginning

**Comment by piotrpekala7** [comment]
@ziajka ?

**Comment by ziajka** [comment]
It should work, at least there should be multi-link support

**Comment by ziajka** [comment]
Ok, in the early version of WebUI there was no https://github.com/GNS3/gns3-web-ui/blob/master/src/app/components/project-map/node-select-interface/node-select-interface.component.ts#L48 
It sounds to me like the issue there (as Piotr mentioned as well).

Are we getting proper datatypes here: https://github.com/GNS3/gns3-web-ui/blob/master/src/app/components/project-map/node-select-interface/node-select-interface.component.ts#L59? 

In case it requires more investigation then we should release as it is (known bug); have a proper fix in place and do another release. @grossmj @piotrpekala7 agree?

**Comment by grossmj** [comment]
> In case it requires more investigation then we should release as it is (known bug); have a proper fix in place and do another release. @grossmj @piotrpekala7 agree?

Well, I don't think we should release with this bug because 1st it has already been reported one month ago and 2nd this is an important feature to have working right in my opinion. I would say let's postpone the GNS3 release for a day or two in order to investigate and hopefully fix this issue.

**Comment by ziajka** [comment]
That's fine. Let's then concentrate on fixing the issue.

**Comment by grossmj** [comment]
Fixed in v2020.2.0-beta.3, thanks :+1:
