### ISSUE TITLE
Connection to host lost

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#796]
I get the message "Connection to host lost" when clicking "Go to template preferences" from the add a node window. This doesn't happen all the time but definitely like 80% of it for me.

![Screenshot from 2020-04-09 14-23-18](https://user-images.githubusercontent.com/4752614/78859211-db731e00-7a6d-11ea-8dcb-b323ba2ca960.png)

![Screenshot from 2020-04-09 14-24-09](https://user-images.githubusercontent.com/4752614/78859222-e0d06880-7a6d-11ea-978e-ffb89f97cd36.png)

**Comment by piotrpekala7** [comment]
Thanks for reporting. I could not reproduce this error in my environment. I added full error message with this commit: https://github.com/GNS3/gns3-web-ui/commit/1afbb39d854f99df2a9fb32e2cd7d3eb6e09d5e2 to project.map.component.

**Comment by piotrpekala7** [comment]
It's not expected behavior as we don't have any server calls at main preferences page:
https://github.com/GNS3/gns3-web-ui/blob/master/src/app/components/preferences/preferences.component.ts

**Comment by piotrpekala7** [comment]
Probably full error message will give us more information needed to fix this issue

**Comment by grossmj** [comment]
Ok, let's try in the next release.

**Comment by piotrpekala7** [comment]
Do you have broader description of the error?

**Comment by grossmj** [comment]
We will have to wait for the next release since the error only appears when a use the Web Ui running in the GNS3 VM.

**Comment by grossmj** [comment]
This seems fixed now.
