### ISSUE TITLE
Wrong adapter types for Qemu VMs

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#797]
Still seems there is an issue with adapter types.

![Screenshot from 2020-04-09 14-14-17](https://user-images.githubusercontent.com/4752614/78859352-386ed400-7a6e-11ea-8cb2-6d206e966b84.png)

**Comment by piotrpekala7** [comment]
Updated in https://github.com/GNS3/gns3-web-ui/commit/10f73760305eee9dbefc541f6b4d3f8ca953af58

**Comment by grossmj** [comment]
Confirmed, this is fixed. Thanks :+1:
