### ISSUE TITLE
Error message when adding interface to Cloud node

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#803]
There is an error when adding a new Ethernet interface to an existing Cloud node.

![Screenshot from 2020-04-12 20-03-25](https://user-images.githubusercontent.com/4752614/79066670-e8f00880-7cf8-11ea-9c74-6cd4825e85c1.png)

**Comment by piotrpekala7** [comment]
fixed in https://github.com/GNS3/gns3-web-ui/commit/09a03ea013c68dbcd2e8712c40d72735ec64e2e9

**Comment by piotrpekala7** [comment]
tested on chrome & FF

**Comment by grossmj** [comment]
Seems to be fixed.
