### ISSUE TITLE
Add default values for New Ethernet switch & New Ethernet hub templates

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#805]
"Number of ports" should be 8

![Screenshot from 2020-04-12 21-25-33](https://user-images.githubusercontent.com/4752614/79068187-3c1b8880-7d04-11ea-9652-26881fc7bdfe.png)

**Comment by piotrpekala7** [comment]
Fixed in https://github.com/GNS3/gns3-web-ui/commit/ee784783a94559890d7fb472ce66fbf45d9b7392, it can be closed

**Comment by grossmj** [comment]
Fixed.
