### ISSUE TITLE
Server error message in the preferences should be displayed

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#806]
For example, when adding a new VMware template with the following error returned:

```
{
    "exception": "VMwareError",
    "message": "VMware is not installed (vmware or vmplayer executable could not be found in $PATH)",
    "status": 409
}
```

![Screenshot from 2020-04-12 21-47-41](https://user-images.githubusercontent.com/4752614/79068596-49864200-7d07-11ea-869a-0c01b9f3a299.png)

**Comment by piotrpekala7** [comment]
Fixed in https://github.com/GNS3/gns3-web-ui/commit/b3aee79f407950e919862f2f3edcb9fa75a1ab8f, tested in chrome and ff

**Comment by grossmj** [comment]
Fixed :+1:
