### ISSUE TITLE
Server type in template preferences

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#807]
I notice it is not possible to select the server type for these templates:

* Ethernet hubs
* Ethernet switches
* Cloud nodes
* Dynamips
* VPCS
* Qemu
* VMware
* VirtualBox

For instance, you can see the following wizard page in the desktop Ui when adding a new VPCS template:

![Screenshot from 2020-04-12 21-55-23](https://user-images.githubusercontent.com/4752614/79087677-357e2700-7d7f-11ea-8d94-8a9965889d75.png)

It is only possible to select the server type for IOU and Docker templates:

![Screenshot from 2020-04-13 11-52-14](https://user-images.githubusercontent.com/4752614/79087616-023b9800-7d7f-11ea-9b9b-25a4a3796d54.png)

![Screenshot from 2020-04-13 12-03-31](https://user-images.githubusercontent.com/4752614/79087621-07004c00-7d7f-11ea-911b-2cde84d75741.png)

Currently, we should be able to select between 3 server types: remote, GNS3 VM or local for each template.

However we have a few problems here:

1. We don't support remote servers in the web ui yet. Like below in the desktop interface.

![Screenshot from 2020-04-13 11-44-41](https://user-images.githubusercontent.com/4752614/79087908-00be9f80-7d80-11ea-9145-7d2accf101d2.png)

2. When running the web ui in the GNS3 VM, a user would naturally select the GNS3 VM server type to add a template to be used to create nodes in the VM however this won't work because from the pov of the web-ui, the template must be run locally (local server type). This is confusing I think.

This is a mess, so while waiting to have support for remote servers and to clarify the GNS3 VM vs local issue, I propose to remove all existing server type radio buttons if not running the Electron JS interface and implicitly default to the "local server" type when adding templates.

**Comment by piotrpekala7** [comment]
> This is a mess, so while waiting to have support for remote servers and to clarify the GNS3 VM vs local issue

What do we need to support remote servers? List here or create a new task with proper requirements, please

**Comment by piotrpekala7** [comment]
Option to choose server type for docker templates removed in https://github.com/GNS3/gns3-web-ui/commit/d3d897c9361fa6798e49f8d67e9d06d3106fb75f, only one option is visible

**Comment by grossmj** [comment]
> @grossmj @ziajka What do we need to support remote servers? List here or create a new task with proper requirements, please.

I will create a new task to support remote servers. This can wait a little bit since not too many of our users use complicated setups with remote servers.

An user should be able to consistently choose the server type for each template he wants to create. So for now "local" or "GNS3 VM" (or a remote server when we support it). The GNS3 VM should be grayed out if it is not configured in the preferences.

So something like this for all the templates below:

1. Run this <Node type> locally
2. Run this <Node type> on the GNS3 VM

* Ethernet hubs
* Ethernet switches
* Cloud nodes
* Dynamips
* VPCS
* Qemu
* Docker
* IOU

VMware and VirtualBox don't support the GNS3 VM server type so there is nothing to change at this point.

![Screenshot from 2020-04-28 16-06-47](https://user-images.githubusercontent.com/4752614/80455494-ff3dcb80-896a-11ea-9b81-9d86203cb3aa.png)

**Comment by piotrpekala7** [comment]
> So something like this for all the templates below:
> 
> Run this locally
> Run this on the GNS3 VM
> Ethernet hubs
> Ethernet switches
> Cloud nodes
> Dynamips
> VPCS
> Qemu
> Docker
> IOU

added in https://github.com/GNS3/gns3-web-ui/commit/7a5437c29e73b80a1abcbef8611ec9bcd05bbdca and in https://github.com/GNS3/gns3-web-ui/commit/c684577c57bf203bf8ed2b77f9088a3f79e85141

**Comment by piotrpekala7** [comment]
Ethernet hubs +
Ethernet switches +
Cloud nodes +
Dynamips +
VPCS +
Qemu +
Docker +
IOU +

**Comment by grossmj** [comment]
All good, thanks :+1:
