### ISSUE TITLE
Adding new IOS template

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#808]
There are a few issues to add new IOS templates

1. We cannot select an existing or upload an IOS image:

![Screenshot from 2020-04-13 12-36-18](https://user-images.githubusercontent.com/4752614/79088942-66f8f180-7d83-11ea-9172-f22a70418d03.png)

![Screenshot from 2020-04-13 12-31-16](https://user-images.githubusercontent.com/4752614/79088857-1da8a200-7d83-11ea-85ee-c29a57077dee.png)

2. A default name & platform should be chosen based on the IOS image name:

For example `c3660-a3jk9s-mz.124-25d.bin` should be c3600.

The detection code for the desktop Ui can be found there: https://github.com/GNS3/gns3-gui/blob/master/gns3/modules/dynamips/dialogs/ios_router_wizard.py#L119L156

Default name should be the platform type.

![Screenshot from 2020-04-13 12-35-54](https://user-images.githubusercontent.com/4752614/79088976-8132cf80-7d83-11ea-80ea-b5a163fe5502.png)

3. A default RAM value should be chosen depending on the platform.

* "c1700": 160MB
* "c2600": 160MB
* "c2691": 192MB
* "c3600": 192MB
* "c3725": 128MB
* "c3745": 256MB
* "c7200": 512MB

![Screenshot from 2020-04-13 12-46-42](https://user-images.githubusercontent.com/4752614/79089360-08cd0e00-7d85-11ea-8765-f799731d6003.png)

4. There is nothing for network adapters and WICs.

Default adapters are found using a compatibility matrix in the desktop interface: https://github.com/GNS3/gns3-gui/blob/master/gns3/modules/dynamips/settings.py

![Screenshot from 2020-04-13 12-53-07](https://user-images.githubusercontent.com/4752614/79089635-f0a9be80-7d85-11ea-99fa-02d61ebb6305.png)

**Comment by piotrpekala7** [comment]
@grossmj @ziajka I need IOS image to realize this task

**Comment by piotrpekala7** [comment]
Thank you Jeremy

**Comment by piotrpekala7** [comment]
I added option to upload IOS image https://github.com/GNS3/gns3-web-ui/blob/master/src/app/components/preferences/dynamips/add-ios-template/add-ios-template.component.ts#L116, actually it's not working properly as I received 404, we have correct for images to upload https://gns3-server.readthedocs.io/en/latest/api/v2/compute/dynamips_vm/dynamipsimagesfilename.html. Guys do you have any idea what's wrong?

**Comment by piotrpekala7** [comment]
Ref 1 We cannot select an existing or upload an IOS image
Ref 2 A default name & platform should be chosen based on the IOS image name
Ref 3 A default RAM value should be chosen depending on the platform
fixed in https://github.com/GNS3/gns3-web-ui/commit/b6d02ca5d46c17d72140f5f9f627bc6ca036f2cd

**Comment by grossmj** [comment]
> Ref 1 We cannot select an existing or upload an IOS image
Ref 2 A default name & platform should be chosen based on the IOS image name
Ref 3 A default RAM value should be chosen depending on the platform
fixed in b6d02ca

This seems to work however I cannot complete the process of adding an IOS template:

![Screenshot from 2020-04-28 15-39-14](https://user-images.githubusercontent.com/4752614/80452941-80469400-8966-11ea-91ee-a15291ac5d96.png)

I checked and all fields are filled. PS: idle-pc should be optional.

Do you still have a problem to upload IOS images?

**Comment by piotrpekala7** [comment]
I am still working on it so I have listed only those 3 things that I have already repaired and are working

**Comment by piotrpekala7** [comment]
Ref 4 There is nothing for network adapters and WICs
fixed in https://github.com/GNS3/gns3-web-ui/commit/e78ca38f3018d901dd1adbe6cd1af1ad86390691

**Comment by piotrpekala7** [comment]
Fixes after verification https://github.com/GNS3/gns3-web-ui/commit/a75de3b179c0d52010c18d8089a34db2dc0a89cb

**Comment by piotrpekala7** [comment]
Tested and verified on Chrome and Firefox with following images:
c1700
c2600
c7200

**Comment by grossmj** [comment]
There are still some issues when adding IOS router templates:

**c7200, c3725, c3745, c2691**

There are no network adapters.

![Screenshot from 2020-05-20 16-38-00](https://user-images.githubusercontent.com/4752614/82415873-50e3fc80-9ab8-11ea-937a-3179f8e86cee.png)

**c3600**

Platform is not set to 3600 (IOS images starting with c3620, c3640, c3660).
Chassis should be set based on the IOS image name by default.
RAM should be set to 192MB by default.

![Screenshot from 2020-05-20 16-33-06](https://user-images.githubusercontent.com/4752614/82416051-96082e80-9ab8-11ea-9a00-b228b2afc775.png)

![Screenshot from 2020-05-20 16-41-58](https://user-images.githubusercontent.com/4752614/82416254-dff11480-9ab8-11ea-9a2c-1f3c229b6375.png)

**c2600**

Chassis should be set to 2610 by default.

![Screenshot from 2020-05-20 16-51-05](https://user-images.githubusercontent.com/4752614/82417053-25faa800-9aba-11ea-8483-b96304518d54.png)

**c1700**

Chassis should be set to 1720 by default.

![Screenshot from 2020-05-20 16-53-46](https://user-images.githubusercontent.com/4752614/82417495-c94bbd00-9aba-11ea-9beb-78a205154796.png)

**Comment by piotrpekala7** [comment]
fix for network adapters https://github.com/GNS3/gns3-web-ui/commit/6bf268b47fe50d2d1ab1150d9c7d4301bfd3369d

**Comment by piotrpekala7** [comment]
fix for platforms https://github.com/GNS3/gns3-web-ui/commit/de0454f420f78c0ded2280b6f59d8948661b350b
