### ISSUE TITLE
Use node names in HTTP console tabs

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#828]
Would it be possible to use the node name instead of "GNS3 Web UI" when opening a HTTP console in a new tab?

![Screenshot from 2020-04-26 18-01-30](https://user-images.githubusercontent.com/4752614/80302238-038dab80-87e8-11ea-8568-ebe05a932c24.png)

**Comment by piotrpekala7** [comment]
yes, fixed in https://github.com/GNS3/gns3-web-ui/commit/18f7f350f7c87d701abcc963c687ebc7e3bfcbd7

**Comment by grossmj** [comment]
Maybe I missed something but it still seems that I get the default tab name on both Firefox and Chrome on Linux. Can you double check please?

![Screenshot from 2020-05-05 18-26-53](https://user-images.githubusercontent.com/4752614/81049824-16962f00-8efe-11ea-9574-22a347218c62.png)

Thanks

**Comment by grossmj** [comment]
My bad, I was on the wrong branch.

**Comment by piotrpekala7** [comment]
no problem
