### ISSUE TITLE
Option to auto-hide menu toolbar on the left side

### ISSUE THREAD

**Issue by cioby23** [GNS3/gns3-web-ui#833]
When having large topologies which begin from the margin of the canvas the toolbar is covering part of the topology as shown below:

![image](https://user-images.githubusercontent.com/7124193/80467749-f3d8a900-8946-11ea-80bf-0d432941335c.png)

Please provide a option to auto-hide the toolbar.

Also as a side note (and this is my personal opinion) the sidebar should have a zero margin from the left of the page instead of floating on the topology.

**Comment by piotrpekala7** [comment]
Fixed in https://github.com/GNS3/gns3-web-ui/commit/82891b248f1e7b0d01b1e79a41be2980107d86f8: ctrl + h to hide left toolbar, shortcut visible in help section

**Comment by piotrpekala7** [comment]
tested in ff & chrome, will be with beta-4

**Comment by grossmj** [comment]
Working. Thanks :+1:

**Comment by cioby23** [comment]
Thanks for adding this feature.
It is possible to set the toolbar position to 0 from top and left and remove the 20px margin like this ?
![image](https://user-images.githubusercontent.com/7124193/81510174-8cdccc00-9318-11ea-87ca-9bfc63e38d60.png)

Or this is the desired way how the toolbar should be placed having a 20 px margin from the top and left side?
