### ISSUE TITLE
Web console future enhancements

### ISSUE THREAD

**Issue by piotrpekala7** [GNS3/gns3-web-ui#837]
- the ability to open consoles for many nodes at once
- option to restore open consoles after returning to the project
- option to resize console window

**Comment by piotrpekala7** [comment]
Above, I have listed console-related tasks that currently require a contribution to the xterm.js repository. We decided to wait for the new version of the mentioned package

**Comment by piotrpekala7** [comment]
The task is blocked, we are waiting for xterm to release a new version of the package

**Comment by ziajka** [comment]
Yes, we are waiting for the new release.

**Comment by grossmj** [comment]
Looks like they released 26 days ago: https://github.com/xtermjs/xterm.js/releases Are we waiting for another release?

**Comment by piotrpekala7** [comment]
new version for xterm-addon-search also has been released

**Comment by piotrpekala7** [comment]
in CoreTerminal class there's new function for resizing https://github.com/xtermjs/xterm.js/blob/master/src/common/CoreTerminal.ts#L132

**Comment by grossmj** [comment]
Perfect, I believe this task is blocked anymore.

**Comment by piotrpekala7** [comment]
I will try to refine this task on branch https://github.com/GNS3/gns3-web-ui/tree/Web-console-future-enhancements

**Comment by grossmj** [comment]
@piotrpekala7 Please move this task to the https://github.com/GNS3/gns3-web-ui/milestone/10 if you don't have enough time.

**Comment by piotrpekala7** [comment]
I updated xterm to latest version 4.8.1 https://www.npmjs.com/package/xterm

**Comment by piotrpekala7** [comment]
when it comes to: option to restore open consoles after returning to the project & the ability to open consoles for many nodes at once
-> open function is still called on HTML element, I didn't find any solution how to rewrite openTerminal function in xterm repository (I mean create separate version of xterm package for our purposes)

**Comment by piotrpekala7** [comment]
I checked resize option cause xterm-fit-addon was also updated: I enabled option to resize console-wrapper in console-wrapper-component.html with mwlResizable package and create subscription in web-console-component but calling resize option on terminal (I mean div element) doesn't work properly

**Comment by grossmj** [comment]
Web console refactoring may help with this issue: https://github.com/GNS3/gns3-server/issues/1779

**Comment by grossmj** [comment]
Maybe we should change our strategy for this issue. What about something similar to CML 2? Would that help?

![Screenshot from 2020-07-30 18-16-15](https://user-images.githubusercontent.com/4752614/88902349-3d5fc980-d291-11ea-81e6-cbac718584ca.png)

Demo video: https://youtu.be/H1N1x9kt-pY?t=1107

@piotrpekala7 I will get you access to CML 2 so you can test by yourself.

**Comment by piotrpekala7** [comment]
it looks very good, I had the opportunity to test it, but do we have any information about the possible implementation in our case?

**Comment by piotrpekala7** [comment]
I found such a thread https://github.com/microsoft/vscode/issues/6838 in the microsoft repository because visual studio code also uses xterm and they also have some limitations

**Comment by grossmj** [comment]
I see 2 options from here:

* Describe the problem with have with xterm.js on https://github.com/xtermjs/xterm.js/issues and see if anyone can suggest a solution.
* Seek an alternative, hterm could be interesting: see https://codehz.github.io/hterm-vs-xterm/ and https://github.com/codehz/hterm-vs-xterm for a starting point. We also need to determine if hterm is still maintained.

**Comment by piotrpekala7** [comment]
![console-resize-option](https://user-images.githubusercontent.com/31202938/91839194-f7f73900-ec4e-11ea-9c3a-dc24ef782806.JPG)

I added option to resize, pr here https://github.com/GNS3/gns3-web-ui/pull/968

**Comment by grossmj** [comment]
Good job! Working well. I think you can merge the PR.

**Comment by piotrpekala7** [comment]
option to resize merged

**Comment by piotrpekala7** [comment]
I did an analysis with more experienced people than me, the solution that I proposed to you about running multiple consoles simultaneously by managing the visibility of elements found it too risky, delays in rendering can be confusing for users. At the moment, we do not have any suggestions for implementing this functionality

**Comment by piotrpekala7** [comment]
1) option to resize window is closed and works fine

2) option to restore open consoles after returning to the project is not possible with xtermjs

3) option to open many consoles with one click -> I opened new task with 3.0 milestone https://github.com/GNS3/gns3-web-ui/issues/1128
