### ISSUE TITLE
Display issue with map settings

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#839]
Looks like there is a problem with map settings. Tested on Chrome Linux.

![Screenshot from 2020-05-05 18-22-54](https://user-images.githubusercontent.com/4752614/81049887-3cbbcf00-8efe-11ea-98f8-bb707477b12f.png)

**Comment by piotrpekala7** [comment]
Fixed in https://github.com/GNS3/gns3-web-ui/commit/53c57b069ed296319459179bdd6ae7143d4b2422
