### ISSUE TITLE
Display issues in drag & drop dialog

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#840]
When a template has a long name:

![Screenshot from 2020-05-05 18-20-13](https://user-images.githubusercontent.com/4752614/81050004-72f94e80-8efe-11ea-8950-7ac6ec7c719d.png)

The symbol for any Docker template isn't displayed. Can still drag & drop it on the canvas and it shows correctly there.

![Screenshot from 2020-05-05 18-25-22](https://user-images.githubusercontent.com/4752614/81050064-873d4b80-8efe-11ea-9d72-4d80eecb1f45.png)

**Comment by grossmj** [comment]
Also, looks like the "Search by Name" and "Filter templates by type" don't work as expected.

![Screenshot from 2020-05-05 19-49-36](https://user-images.githubusercontent.com/4752614/81056392-a392b580-8f09-11ea-81ea-116d5b317a68.png)

**Comment by piotrpekala7** [comment]
Ok, so we have 3 issues here:
1) search and filter doesn't work properly
2) long text is not wrapped
3) not every icon is displayed properly

**Comment by piotrpekala7** [comment]
2 -> fix for displaying text https://github.com/GNS3/gns3-web-ui/commit/81b6eb32cfe5275fb456e5f57831cbef2de5e69c

**Comment by piotrpekala7** [comment]
1 -> fix for search and filter

**Comment by piotrpekala7** [comment]
3 -> fixed in https://github.com/GNS3/gns3-web-ui/commit/5600364583853c6c2079531e1403d056203df7b4

**Comment by piotrpekala7** [comment]
please verify, If sth is still wrong I do in asap tomorrow

**Comment by grossmj** [comment]
There is still something wrong.

I don't get a list of templates if I immediately type in the "search by name" field. I am forced to go back to projects and then back to the project to be able to see templates after that.

![Screenshot from 2020-05-06 12-06-46](https://user-images.githubusercontent.com/4752614/81133923-43942180-8f92-11ea-88d6-a67e15d3f47d.png)

However, it works if I first set the template type to "all" for instance:

![Screenshot from 2020-05-06 12-07-10](https://user-images.githubusercontent.com/4752614/81133921-4262f480-8f92-11ea-83f2-a2624a9450dd.png)

Looks like you must set "Filter by template types" to "all" by default.

**Comment by piotrpekala7** [comment]
fixed in https://github.com/GNS3/gns3-web-ui/commit/79dee7359034ecc96678d583a26030d5e2e3e67e, please verify

**Comment by grossmj** [comment]
All good now. Thanks :+1:
