### ISSUE TITLE
New port setting for GNS3 VM preferences

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#841]
I have added a new "port" setting for the GNS3 VM preferences in the desktop Ui. This setting should be added in the web ui for VMware and VirtualBox virtualization engines.

![Screenshot from 2020-05-05 21-39-44](https://user-images.githubusercontent.com/4752614/81064513-fa53bb80-8f18-11ea-8d3d-c64ee501fe1b.png)

![Screenshot from 2020-05-05 21-38-06](https://user-images.githubusercontent.com/4752614/81064409-d1cbc180-8f18-11ea-9f43-cf93230fc1c0.png)

**Comment by piotrpekala7** [comment]
Added in https://github.com/GNS3/gns3-web-ui/commit/81b388a7fe18c5a922a5f06c187481cf1d8358e0

**Comment by piotrpekala7** [comment]
tested on chrome & ff

**Comment by grossmj** [comment]
My preferences shows an empty port value:

![Screenshot from 2020-05-08 13-18-09](https://user-images.githubusercontent.com/4752614/81368273-83900b80-912e-11ea-8990-4a0ff6a69630.png)

Doing a HTTP GET on http://localhost:3080/v2/gns3vm, I can see "port" is there.

```
{
    "enable": false,
    "engine": "vmware",
    "headless": false,
    "port": 80,
    "ram": 2048,
    "vcpus": 4,
    "vmname": "GNS3 VM TEST",
    "when_exit": "keep"
}
```

**Comment by piotrpekala7** [comment]
fixed in https://github.com/GNS3/gns3-web-ui/commit/afa9facb3ad9263fff2e04cb2a4e0ce3a91ddb64
