### ISSUE TITLE
Bundled web-ui doesn't like new default port

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#843]
The bundled web-ui doesn't like the new default port set to 80 when running in the GNS3 VM.

Trying to create or open a running project never finishes:

![Screenshot from 2020-05-06 16-39-32](https://user-images.githubusercontent.com/4752614/81146879-502b7080-8fb8-11ea-9bac-a69ce3c2ebeb.png)

Symbols cannot be displayed:

![Screenshot from 2020-05-06 16-42-02](https://user-images.githubusercontent.com/4752614/81147112-c5974100-8fb8-11ea-9fa5-46b102de57f7.png)

The Servers page shows "NaN" for the port.

![Screenshot from 2020-05-06 16-36-17](https://user-images.githubusercontent.com/4752614/81146683-eca14300-8fb7-11ea-830a-b56126f79022.png)

Running the gns3-server back on port 3080 fixes these issues.

**Comment by piotrpekala7** [comment]
How did you add this server? Did you enter the port into the add node dialog?

**Comment by piotrpekala7** [comment]
Does it work then?

**Comment by grossmj** [comment]
Only with port 3080

**Comment by grossmj** [comment]
I opened with /static/web-ui/bundled directly

**Comment by piotrpekala7** [comment]
What port was visible in the browser bar when opened?

**Comment by piotrpekala7** [comment]
https://raw.githubusercontent.com/GNS3/gns3-web-ui/master/src/app/components/bundled-server-finder/bundled-server-finder.component.ts

parseInt(this.document.location.port, 10))

**Comment by piotrpekala7** [comment]
Fixed in https://github.com/GNS3/gns3-web-ui/commit/3f0772c352e2f6ddf7238416a86537a51ded6c2d

**Comment by piotrpekala7** [comment]
please verify

**Comment by grossmj** [comment]
Fixed in v2020.2.0-beta.3, thanks :+1:
