### ISSUE TITLE
Feature Request : Attach Reference documents

### ISSUE THREAD

**Issue by saviodsouza** [GNS3/gns3-web-ui#844]
Hi Guys,

I would like to suggest a new feature to store reference files within gns3 poject.

A "Reference Files" dock in the UI / WUI to upload/download project related documents like :

General Notes (*.txt, *.docx, *.pdf)
Diagrams (png, jpg, *.dia, etc)
other docs (any type of file)

/project-files/
/reference-files/ #these files can be stored here.
project.gns3

Readme file is created only when project is exported.....
At present it is easily possible to create a new folder and put project reference files in it, if the project folder path is on local pc.
It is not possible if you have all files stored in the remote main server repository. 

Any more inputs ;)

Thank you.
sd

**Comment by piotrpekala7** [comment]
This task is not refined, there are no implementation details, no requirements here

**Comment by piotrpekala7** [comment]
@ziajka Is there a description of this task somewhere and it is not linked here?

**Comment by saviodsouza** [comment]
No 

I had just put a feature request

I have no programing knowledge.
What do I have to add and where.

**Comment by piotrpekala7** [comment]
@ziajka Is there a description of this task somewhere and it is not linked here?

**Comment by saviodsouza** [comment]
No

**Comment by piotrpekala7** [comment]
This task requires changes by server side, we should have another endpoint for project files if we want to implement it in web UI
