### ISSUE TITLE
Open ad in new tab/window

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#845]
The target website should be opened in a new tab/window when clicking on "Check it out" button.

![Screenshot from 2020-05-07 13-04-03](https://user-images.githubusercontent.com/4752614/81251838-680bfe80-9063-11ea-825c-55e57684e679.png)

**Comment by piotrpekala7** [comment]
The content of the ad is directly injected into the component with notifications. So it can be done **only** by a person who has adbutler credentials and sets ads

**Comment by piotrpekala7** [comment]
We are rendering only wrapper div in web UI: https://github.com/GNS3/gns3-web-ui/blob/master/src/app/components/adbutler/adbutler.component.html
