### ISSUE TITLE
Snap to grid feature is not working at all

### ISSUE THREAD

**Issue by cioby23** [GNS3/gns3-web-ui#846]
I enabled Snap to grid feature for a project in the web-ui and it does not take into account if the option is enabled. I can move the nodes freely on the topology without respecting the snap to grid option
On the classic gui is working as expected as seen in the picture below:

![image](https://user-images.githubusercontent.com/7124193/81509795-d972d800-9315-11ea-83a6-e2a5bb272881.png)

On the web-gui the position of the nodes is missaligned from the grid. I think there is an inconsistency in the way the web gui calculates nodes position on the topology compared with the classic gui.

![image](https://user-images.githubusercontent.com/7124193/81509858-49815e00-9316-11ea-8602-f836a64f8f48.png)

**Comment by piotrpekala7** [comment]
![snapToGridOption](https://user-images.githubusercontent.com/31202938/81532557-e10d9d80-9364-11ea-971b-8b23c3771602.JPG)

I tested this function on two browsers and it works as it should. In the project settings you have two types of grids: node grid & drawing grid. For nodes, the first value is taken into account

**Comment by cioby23** [comment]
I have set the drawing grid to 0 and the node grid I have left it at 60. So the snap to grid it seems to work but the problem is that the node does not position on the intersection between the lines like in the classic gui (and shown also on your screenshot).

I'm using GNS3 2.2.8 with the latest web-ui package beta. running on Archlinux

**Comment by piotrpekala7** [comment]
Is the position aligned with the grid after moving the node?

**Comment by cioby23** [comment]
Once I move the node on the grid I see the Snap to grid feature tries to place the node on the next area but it does align the node on the grid by placing it on the center point (intersection between the lines) as shown above.
As you can see the node is placed in between the squares of the grid. Below is how it looks on the classic GUI as it's correct.

![image](https://user-images.githubusercontent.com/7124193/81554407-660dac80-938f-11ea-9cfe-0cbf5a2b83db.png)

Also spotted another difference between web-ui in classic gui 
For the drawing grid you can to down to 0 and below on the web-ui on the classic-gui you can go down to minimum 5 and no below.

**Comment by piotrpekala7** [comment]
working on Firefox 77.0.1 & Chrome Version 83.0.4103.61

**Comment by cioby23** [comment]
Just did some more in depth tests and it works partially with only some specific values configured for the node grid size.

For example i have tested with values like 50 and 100 and it was ok but for any other values in between 60, 70, 80 or below 40, 30 the node does not align properly on the grid as shown above. 
The tests were done on Chrome and Firefox latest versions on both Linux and Windows 10.

Please try and do the tests with multiple random values between 0 and 100.

I do not know how these have are calculated based on the topology canvas size, but only when used 50 or 100 I was able to successfully align the node properly to the grid when the Snap the grid option was enabled.

When using other values like 60 for example there is no correlation between the node position on the desktop GUI (which works fine) and the node position in the web-ui (which is not the same as on the desktop GUI). This only works for 50 and 100 values as mentioned above.

**Comment by piotrpekala7** [comment]
Hmmm...

we have simple algorithm for snap to grid option:

`    if (project.snap_to_grid) {
      xPosition = Math.round((xPosition + node.width/2) / project.grid_size) * project.grid_size;
      yPosition = Math.round((yPosition + node.height/2) / project.grid_size) * project.grid_size;

      xPosition = Math.round(xPosition - node.width/2);
      yPosition = Math.round(yPosition - node.height/2);
    }`

**Comment by piotrpekala7** [comment]
Can anyone help with this task?

**Comment by grossmj** [comment]
I don't know if this can help but here is the algorithm we have in the desktop Ui:

```
        if change == QtWidgets.QGraphicsItem.ItemPositionHasChanged and self.isActive() and self._main_window.uiSnapToGridAction.isChecked():
            grid_size = self._graphics_view.drawingGridSize()
            mid_x = self.boundingRect().width() / 2
            tmp_x = (grid_size * round((self.x() + mid_x) / grid_size)) - mid_x
            mid_y = self.boundingRect().height() / 2
            tmp_y = (grid_size * round((self.y() + mid_y) / grid_size)) - mid_y
            if tmp_x != self.x() and tmp_y != self.y():
                self.setPos(tmp_x, tmp_y)
```

**Comment by piotrpekala7** [comment]
honestly I tried to 'translate' it before

```
      xPosition = (project.grid_size * Math.round((x + node.width/2) / project.grid_size)) - node.width/2;
      yPosition = (project.grid_size * Math.round((x + node.width/2) / project.grid_size)) - node.width/2;
```

**Comment by grossmj** [comment]
Indeed, this should be the same. Here is my 'translation' but I doubt this changes anything.

```
      midXPosition = node.width / 2
      xPosition = (project.grid_size * Math.round((x + midXPosition ) / project.grid_size)) - midXPosition;
      midYPosition = node.height / 2
      yPosition = (project.grid_size * Math.round((y + midYPosition) / project.grid_size)) - midYPosition;
```

**Comment by piotrpekala7** [comment]
in my opinion this algorithm will not work because the grid is drawn in a different way in WebUI than in GUI

**Comment by piotrpekala7** [comment]
I also tried 

```
      let midXPosition = node.width / 2;
      xPosition = (project.grid_size * Math.round((x + midXPosition)/project.grid_size)) - midXPosition + ((project.scene_width - (Math.floor(project.scene_width/project.grid_size) * project.grid_size)) / 2);

      let midYPosition = node.height / 2;
      yPosition = (project.grid_size * Math.round((y + midYPosition)/project.grid_size)) - midYPosition + ((project.scene_height - (Math.floor(project.scene_height/project.grid_size) * project.grid_size)) / 2);
```

**Comment by piotrpekala7** [comment]
I still don't understand what's wrong with original code...

**Comment by ziajka** [comment]
Looks like the root cause is misalignment how grids are drawn between Web UI & GUI. In my opinion, we should keep them consistent (if possible). If they are consistent then the issue probably goes away. @grossmj what do you think?

**Comment by grossmj** [comment]
> Looks like the root cause is misalignment how grids are drawn between Web UI & GUI. In my opinion, we should keep them consistent (if possible). If they are consistent then the issue probably goes away. @grossmj what do you think?

Indeed, @piotrpekala7 has trying to use the same algorithm as in the desktop GUI however there is still a problem somewhere.

**Comment by ziajka** [comment]
Yes, this will require then adjusting grids - mechanism responsible for drawing them on the plot.

**Comment by piotrpekala7** [comment]
the same issue for drawing grid

**Comment by piotrpekala7** [comment]
if I can do that, I will change the way the grid is drawn for nodes and drawings

**Comment by piotrpekala7** [comment]
for for nodes -> https://github.com/GNS3/gns3-web-ui/commit/1a8701d845302f2a7a051f1d8c02d4d33a509637

**Comment by piotrpekala7** [comment]
fix fro drawings -> https://github.com/GNS3/gns3-web-ui/commit/c7dc56babdb9613166a5122296272b5fc43d777c

**Comment by piotrpekala7** [comment]
tested with values: 60, 70, 80, 100, 150, 200, 250

**Comment by piotrpekala7** [comment]
works as expected on Chrome and FF
