### ISSUE TITLE
Ability to quickly change Hostname from right click

### ISSUE THREAD

**Issue by jeepacation** [GNS3/gns3-web-ui#848]
Hi Guys,

From within the web-ui can we develop a better way of changing hostnames of (some) devices? 

This specific example is for IOU

Currently you have to; (from what i can gather)

- right click on node
- click configure
- change name
- configure network eth adaptors (req'd field)
- configure serial adaptors (req'd field)
- click apply

![image](https://user-images.githubusercontent.com/42051349/81618967-db2ebf80-942b-11ea-9ba2-b2f19748e10e.png)

could we look at adding a line to the right click menu similar to GNS3 Client?

Please correct me if i'm wrong or i have missed something :-)

**Comment by grossmj** [comment]
This should be done like in the Desktop Ui.

![hostname_change](https://user-images.githubusercontent.com/4752614/82408611-19228800-9aab-11ea-8eb3-39a4c6abc6a8.png)

![Screenshot from 2020-05-20 15-01-34](https://user-images.githubusercontent.com/4752614/82408615-1d4ea580-9aab-11ea-8a26-41583fbff4eb.png)

**Comment by piotrpekala7** [comment]
Fixed in https://github.com/GNS3/gns3-web-ui/commit/932c4828559e0b7830031bebef8195c7d145a7e1

**Comment by grossmj** [comment]
Working, thanks :+1:
