### ISSUE TITLE
Progress bar for node creation

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#861]
There is no progress bar or indication a node is being created when adding a new one to the canvas. This is mostly problematic for Docker containers because images that are not already on the system must be downloaded which can take some time.

To reproduce:

1. Create a new Docker container template with a new Docker image:

![Screenshot from 2020-05-18 18-31-23](https://user-images.githubusercontent.com/4752614/82194649-4dc10300-9936-11ea-8652-f92280748b12.png)

2. Use the template. Nothing happens for 10-15 seconds depending on your Internet connection speed. In the background the server is downloading the Docker image but there is no indication that something is actually in progress for users.

![Screenshot from 2020-05-18 18-32-15](https://user-images.githubusercontent.com/4752614/82194666-53b6e400-9936-11ea-9b27-fd292cf6e5d4.png)

3. The node is suddenly created on the canvas.

![Screenshot from 2020-05-18 18-32-38](https://user-images.githubusercontent.com/4752614/82194678-59142e80-9936-11ea-96af-c658d48ba0fe.png)

Solution: I think a progress bar like the one used when opening projects would be enough for this situation.

**Comment by piotrpekala7** [comment]
activated in https://github.com/GNS3/gns3-web-ui/commit/06e3befe0e45a0b90d973c2c723aff2ff79b534d

**Comment by grossmj** [comment]
Working, thanks :+1:
