### ISSUE TITLE
Same question is asked after going back to project

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#862]
A question is asked if I open a console for a node and then go to the projects page. This is fine, even if I close all the consoles.

![Screenshot from 2020-05-18 18-44-25](https://user-images.githubusercontent.com/4752614/82195704-ce343380-9937-11ea-92ae-5d9312f3381c.png)

![Screenshot from 2020-05-18 18-45-01](https://user-images.githubusercontent.com/4752614/82195729-dab88c00-9937-11ea-88f2-d7c32ef70229.png)

However, the same question gets asked again when I go back to the project and then go to any other page (like preferences for instance).

**Comment by piotrpekala7** [comment]
The consoles will be closed every time you leave the map, so this question appears every time you want to go to another page, no matter if it is a list of projects or preferences

**Comment by grossmj** [comment]
> The consoles will be closed every time you leave the map, so this question appears every time you want to go to another page, no matter if it is a list of projects or preferences

The problem is when going back to the project with no console opened. The information that consoles have been opened should be reset when leaving the project view.

**Comment by piotrpekala7** [comment]
fixed in https://github.com/GNS3/gns3-web-ui/commit/b8ded15ef7fea7655e0506dbe8d913226be5020f
