### ISSUE TITLE
Upload IOS Router image button is not working

### ISSUE THREAD

**Issue by Fabricio20** [GNS3/gns3-web-ui#870]
When uploading an IOS Image, the uploader does not disable (or fill) the dropdown.

**Steps to Reproduce:**
- New Project
- Preferences
- Dynamips
- Add IOS Router Template
- Upload an image file
- Notice the "Image Uploaded" pop-up at the bottom
- Notice the dropdown box stays empty but is now red (invalid)
- Fill out all other fields, try to submit and you are met with a "Fill all the required fields" message.

**Evidence**:
![image](https://user-images.githubusercontent.com/7545720/82386959-22a8e300-9a0c-11ea-8ad6-60ff492f31e6.png)

**Notes**:
Not sure if the upload should be adding an entry to the list so I can then select it or if it should disable the dropdown. I tested 4 versions before this one and it's actually an issue from day 0 (as it was introduced).

I got as far as finding the responsible file `add-ios-template.component.html` but not I'm not yet that well-versed on Angular-Material and uploaders 😅

**Comment by grossmj** [comment]
This issue has been fixed recently. Please see https://github.com/GNS3/gns3-web-ui/issues/847 for details.
