### ISSUE TITLE
Symbol selection

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#871]
Minor cosmetic issues when selecting a symbol in the preferences. The group box doesn't extend all the way to the bottom.

![Screenshot from 2020-05-20 15-16-55](https://user-images.githubusercontent.com/4752614/82410170-7b30bc80-9aae-11ea-8193-780061bbf065.png)

**Comment by piotrpekala7** [comment]
fixed in https://github.com/GNS3/gns3-web-ui/commit/3a57e73192dadfb2c13fe7d3592e5d06f5a92cfd
