### ISSUE TITLE
Error when selecting existing Docker image

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#872]
`image` is set to nothing when sending the API request, therefore the server complains that the image name is too short. I do not have the problem if I specify a new image.

![Screenshot from 2020-05-20 15-49-32](https://user-images.githubusercontent.com/4752614/82411779-905b1a80-9ab1-11ea-839d-ea11c1489588.png)

**Comment by piotrpekala7** [comment]
Fixed in https://github.com/GNS3/gns3-web-ui/commit/7625ff5cfaacd2452eca88584f9430b0705d9008
