### ISSUE TITLE
Prevent user to move to another step when adding template?

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#873]
Is it possible to prevent users to move to another step if the current one isn't complete/valid? For instance I shouldn't be allowed to go to step 3 "Container name" until I select an image in step 2.

![Screenshot from 2020-05-20 15-20-15](https://user-images.githubusercontent.com/4752614/82410482-26da0c80-9aaf-11ea-9aeb-cccb23b725f9.png)

**Comment by piotrpekala7** [comment]
Yes, it's possible https://stackoverflow.com/questions/52947587/angular-material-stepper-component-prevent-going-to-all-the-non-visited-steps. To achieve that we should mark correct flag after every finished step

**Comment by piotrpekala7** [comment]
@grossmj Do you want to introduce it in preferences section? I mean creating templates

**Comment by piotrpekala7** [comment]
It has its pros and cons, right now we are verifying user input at the end

**Comment by piotrpekala7** [comment]
We can also inform users before the next step that the previous one is not finished, but it can be annoying

**Comment by piotrpekala7** [comment]
?

**Comment by grossmj** [comment]
> @grossmj Do you want to introduce it in preferences section? I mean creating templates

Let's validate each step in the preferences section with one final check at the end.

**Comment by piotrpekala7** [comment]
dynamips -> https://github.com/GNS3/gns3-web-ui/commit/0463b8c3b8bd34e8bf5fea39e9e28a551cea96e4

**Comment by piotrpekala7** [comment]
IOU -> https://github.com/GNS3/gns3-web-ui/commit/68a13e293bff3937f63a0315efae997e0d79729c

**Comment by piotrpekala7** [comment]
qemu -> https://github.com/GNS3/gns3-web-ui/commit/d190765a998117f0bcf0581c1f9b3220bedb8fbe

**Comment by piotrpekala7** [comment]
docker -> https://github.com/GNS3/gns3-web-ui/commit/d6808ba1d7015542f786268899e0c6fe113b8b00

**Comment by grossmj** [comment]
Works well :+1: 

One last thing (I am being picky), is this possible to have gray numbers for steps that have not been opened yet? For instance in the new Docker template, steps 4, 5, 6 should be in same style as step 3.

![Screenshot from 2020-06-11 16-23-25](https://user-images.githubusercontent.com/4752614/84354426-014ca880-ac00-11ea-8f80-3be6ea329e26.png)

**Comment by piotrpekala7** [comment]
Unfortunately this is not possible. From Angular Material docs: steps are marked with 'pen' when input is edited -> we do that for default values

**Comment by grossmj** [comment]
> Unfortunately this is not possible. From Angular Material docs: steps are marked with 'pen' when input is edited -> we do that for default values

Ok, this is fine then. Thanks :+1:
