### ISSUE TITLE
Default values in templates

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#874]
**Docker**

Default number of network adapters for Docker templates should be 1

![Screenshot from 2020-05-20 15-22-07](https://user-images.githubusercontent.com/4752614/82414020-8b986580-9ab5-11ea-99f6-3fef9cf6652f.png)

**Qemu VM**

Default RAM for Qemu VM template should be 256 MB and Qemu binary should be selected (first available in the list).

![Screenshot from 2020-05-20 16-20-19](https://user-images.githubusercontent.com/4752614/82414191-d2865b00-9ab5-11ea-83f8-938e2ba7709f.png)

**IOU**

When creating the IOU template, the following fields for the API request should be:

For L2 IOU images

- ethernet_adapters: 4
- serial_adapters: 0

For L3 IOU images

- ethernet_adapters: 2
- serial_adapters: 2

**Comment by grossmj** [comment]
**Qemu VM**

"This is a legacy ASA VM" should be removed.

![Screenshot from 2020-05-20 16-27-36](https://user-images.githubusercontent.com/4752614/82414892-e67e8c80-9ab6-11ea-8146-b3ab267114bc.png)

**Comment by piotrpekala7** [comment]
Fixed in https://github.com/GNS3/gns3-web-ui/commit/455a13b96f9d87a0b76c7dc6e1645aa44cbbe8bb
