### ISSUE TITLE
Verification of icon size

### ISSUE THREAD

**Issue by piotrpekala7** [GNS3/gns3-web-ui#876]
We should check the size of icons added by users before adding them to the map and scale them accordingly.

**Comment by piotrpekala7** [comment]
fixed in https://github.com/GNS3/gns3-web-ui/commit/672d25132f417194aa46c99125419eb47b83eb91, maximum icon size should be 200px

**Comment by grossmj** [comment]
> fixed in 672d251, maximum icon size should be 200px

Why 200px?

**Comment by piotrpekala7** [comment]
I decided that this limit value for the icon size would be appropriate

**Comment by piotrpekala7** [comment]
we can change it

**Comment by grossmj** [comment]
Let's limit at 64 px like in the desktop Ui.

**Comment by piotrpekala7** [comment]
changed in https://github.com/GNS3/gns3-web-ui/commit/7fa49824c65a2a6b80c9ea2418819f1cc33c1b40
