### ISSUE TITLE
New option for Qemu VMs

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#885]
I have added a new option for Qemu VMs in https://github.com/GNS3/gns3-server/pull/1768

The option name is "replicate_network_connection_state" and is `true` by default.

![Selection_002](https://user-images.githubusercontent.com/4752614/83965654-4ae17e80-a8f4-11ea-9bab-a132a092d11d.png)

The option should be added to the web-ui.

**Comment by piotrpekala7** [comment]
added in https://github.com/GNS3/gns3-web-ui/commit/2b380a2699db01ad1383c029c2acbe0f930a140c

**Comment by grossmj** [comment]
Verified, thanks :+1:
