### ISSUE TITLE
Invalid type for adapters field when adding Docker template

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#887]
The default number of adapters should be an integer.

![Screenshot from 2020-06-10 14-39-10](https://user-images.githubusercontent.com/4752614/84229318-6d5bdd80-ab28-11ea-85d1-294796780dfe.png)

**Comment by piotrpekala7** [comment]
fixed https://github.com/GNS3/gns3-web-ui/commit/da5dcd5fe9fdbf8d10178b45587115fefd81a295
