### ISSUE TITLE
Invalid property when adding VMware VM template

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#888]
`power-off` should be `power_off`

![Screenshot from 2020-06-10 14-52-58](https://user-images.githubusercontent.com/4752614/84230013-2373f700-ab2a-11ea-8fb6-0b1fcaa7366b.png)

**Comment by piotrpekala7** [comment]
fixed https://github.com/GNS3/gns3-web-ui/commit/f06ba2bf774e415b126f1b47ea9608a523fb32f0
