### ISSUE TITLE
Web UI cannot set flag "Leave this project running in the background after closing"

### ISSUE THREAD

**Issue by candlerb** [GNS3/gns3-web-ui#890]
This is using the web-ui from gns3 2.2.9.  To replicate:

* Open a project
* Go to `Open Menu > Project Settings > Edit Project`
* Check all four boxes and Apply

    ![image](https://user-images.githubusercontent.com/44789/84632153-69dca380-aee6-11ea-8313-69480468946d.png)

* Go to `Open Menu > Project Settings > Edit Project`
* Look, the "Leave this project running" flag is *not* set

    ![image](https://user-images.githubusercontent.com/44789/84632233-837deb00-aee6-11ea-88f9-ce2bd6d0d73c.png)

* Start the project
* Close your web browser
* The project is terminated :-(

WORKAROUND: Connect with the full-fat GNS3 UI to set the flag, before closing the web browser.

**Comment by piotrpekala7** [comment]
fixed in https://github.com/GNS3/gns3-web-ui/commit/a7f5a5fa091b99386eda7d685eac67321e01938c
