### ISSUE TITLE
Misleading error message when starting a Qemu device

### ISSUE THREAD

**Issue by cioby23** [GNS3/gns3-web-ui#892]
OS: Linux (ArchLinux)
GNS3 web-ui: v2020.2.0-beta.5

I have created a simple topology with two vIOS L2 switches connected with dual links between them and when I try to start any of the vIOS L2 devices (Qemu) the below error appears:

![image](https://user-images.githubusercontent.com/7124193/84999431-ceebff80-b159-11ea-8fec-793edcd5aa74.png)

I checked on the GNS3 gui client side and the real error is listed below:

**QEMU process has stopped, return code: 1
Execution log:
ioctl(KVM_CREATE_VM) failed: 16 Device or resource busy
qemu-system-x86_64: failed to initialize kvm: Device or resource busy**

**Comment by piotrpekala7** [comment]
I understand that you would like us to enter more information when displaying notifications in the interface?

**Comment by cioby23** [comment]
Yes the real error is because the KVM module is in use by another hypervisor in my case Virtualbox. So I think the error message should be more descriptive and give the users a hint why the device cannot be started.
You can check here for an explanation of this error: https://tech.blog.sue.ss.it/2014/09/linux-kvm-error-ioctlkvm_create_vm-failed-16-device-or-resource-busy/

**Comment by piotrpekala7** [comment]
Thank you for the information, can you indicate other places where the error description is not detailed enough for you?

**Comment by cioby23** [comment]
For now I found only this one. If I found any other strange errors I'll report them here.

**Comment by grossmj** [comment]
@piotrpekala7 

A `log.error` event is sent to clients connected to the project using the project WebSocket. So what you need to do is display the content of that event.

**Comment by piotrpekala7** [comment]
Could you confirm that the error is displayed correctly in GNS3 console in web UI?

**Comment by grossmj** [comment]
@cioby23 Have you had a chance to have a look? Thanks :)

![Screenshot from 2020-06-25 18-08-25](https://user-images.githubusercontent.com/4752614/85686289-fa00c100-b70e-11ea-905f-4cd568a438ef.png)

**Comment by cioby23** [comment]
How can I test this ? I mean what are the steps to upgrade the web-ui with the latest changes ?
I'm on the 2.2.10 version using bundled web-ui 2020 beta-5.

**Comment by grossmj** [comment]
@cioby23 I think what @piotrpekala7 is asking is if you see any message in the console when you get the error. Nothing has been fixed yet.

**Comment by cioby23** [comment]
When I try to start a Qemu node (IOSvL2) with KVM acceleration enabled while I have a Virtualbox VM powered on I see the below messages in the web-ui console

```
POST http://127.0.0.1:8080/v2/projects/15f3e414-f608-4e51-b6e3-5711cdce8898/nodes/d1719fff-2727-4dea-97cf-1580b47aa697/start
Event received: node.updated - command_line: /usr/bin/qemu-system-x86_64 -name Cisco-IOSvL2-1 -m 512M -smp cpus=1 -enable-kvm -machine smm=off -boot order=c -drive file=/home/cioby/GNS3/projects/untitled/project-files/qemu/d1719fff-2727-4dea-97cf-1580b47aa697/hda_disk.qcow2,if=virtio,index=0,media=disk,id=drive0 -drive file=/home/cioby/GNS3/projects/untitled/project-files/qemu/d1719fff-2727-4dea-97cf-1580b47aa697/hdb_disk.qcow2,if=virtio,index=1,media=disk,id=drive1 -uuid d1719fff-2727-4dea-97cf-1580b47aa697 -serial telnet:127.0.0.1:5023,server,nowait -monitor tcp:127.0.0.1:34691,server,nowait -net none -device e1000,mac=0c:88:98:a6:97:00,netdev=gns3-0 -netdev socket,id=gns3-0,udp=127.0.0.1:10079,localaddr=127.0.0.1:10078 -device e1000,mac=0c:88:98:a6:97:01,netdev=gns3-1 -netdev socket,id=gns3-1,udp=127.0.0.1:10081,localaddr=127.0.0.1:10080 -display none, compute_id: local, console: 5019, console_host: 0.0.0.0, console_type: telnet, first_port_name: , height: 60, label: Cisco-IOSvL2-1, name: Cisco-IOSvL2-1, node_directory: /home/cioby/GNS3/projects/untitled/project-files/qemu/d1719fff-2727-4dea-97cf-1580b47aa697, node_id: d1719fff-2727-4dea-97cf-1580b47aa697, node_type: qemu, port_name_format: Gi{1}/{0}, port_segment_size: 4, ports: adapter_number: 0, link_type: ethernet, name: Gi0/0, port_number: 0, short_name: Gi0/0, adapter_number: 1, link_type: ethernet, name: Gi0/1, port_number: 0, short_name: Gi0/1, project_id: 15f3e414-f608-4e51-b6e3-5711cdce8898, **status: started,** symbol: :/symbols/affinity/square/red/switch_multilayer.svg, symbol_url: undefined, width: 60, x: -760, y: -110, z: 1.
Event received: node.updated - command_line: /usr/bin/qemu-system-x86_64 -name Cisco-IOSvL2-1 -m 512M -smp cpus=1 -enable-kvm -machine smm=off -boot order=c -drive file=/home/cioby/GNS3/projects/untitled/project-files/qemu/d1719fff-2727-4dea-97cf-1580b47aa697/hda_disk.qcow2,if=virtio,index=0,media=disk,id=drive0 -drive file=/home/cioby/GNS3/projects/untitled/project-files/qemu/d1719fff-2727-4dea-97cf-1580b47aa697/hdb_disk.qcow2,if=virtio,index=1,media=disk,id=drive1 -uuid d1719fff-2727-4dea-97cf-1580b47aa697 -serial telnet:127.0.0.1:5023,server,nowait -monitor tcp:127.0.0.1:34691,server,nowait -net none -device e1000,mac=0c:88:98:a6:97:00,netdev=gns3-0 -netdev socket,id=gns3-0,udp=127.0.0.1:10079,localaddr=127.0.0.1:10078 -device e1000,mac=0c:88:98:a6:97:01,netdev=gns3-1 -netdev socket,id=gns3-1,udp=127.0.0.1:10081,localaddr=127.0.0.1:10080 -display none, compute_id: local, console: 5019, console_host: 0.0.0.0, console_type: telnet, first_port_name: , height: 60, label: Cisco-IOSvL2-1, name: Cisco-IOSvL2-1, node_directory: /home/cioby/GNS3/projects/untitled/project-files/qemu/d1719fff-2727-4dea-97cf-1580b47aa697, node_id: d1719fff-2727-4dea-97cf-1580b47aa697, node_type: qemu, port_name_format: Gi{1}/{0}, port_segment_size: 4, ports: adapter_number: 0, link_type: ethernet, name: Gi0/0, port_number: 0, short_name: Gi0/0, adapter_number: 1, link_type: ethernet, name: Gi0/1, port_number: 0, short_name: Gi0/1, project_id: 15f3e414-f608-4e51-b6e3-5711cdce8898, **status: stopped,** symbol: :/symbols/affinity/square/red/switch_multilayer.svg, symbol_url: undefined, width: 60, x: -760, y: -110, z: 1.
[object Object]
```

**Comment by grossmj** [comment]
@cioby23 thanks! @piotrpekala7 it looks like the web-ui doesn't receive `log.error` events from project's websocket stream.

**Comment by piotrpekala7** [comment]
fixed in https://github.com/GNS3/gns3-web-ui/commit/1b059240701661a05d3a59f7b54727c48b5baa9b

**Comment by piotrpekala7** [comment]
![messageError](https://user-images.githubusercontent.com/31202938/86905203-083cdd00-c112-11ea-9100-91129e5cf5c2.PNG)

error message visible in console & in notification
