### ISSUE TITLE
login/password in url

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-web-ui#893]
Hi

When i go on the url http://192.168.0.41:3080, my browser asks me the login/password and after, goes to the url : http://192.168.0.41:3080/static/web-ui/server/1/projects
It is ok.

But, if i set my good login/password on the url (for example : http://LOGIN:PASSWORD@192.168.0.41:3080), my browser goes to the url http://192.168.0.41:3080/static/web-ui/bundled and shows me  a empty grey page.
I must reload the page to have the url http://192.168.0.41:3080/static/web-ui/server/1/projects

**Comment by piotrpekala7** [comment]
I can confirm this problem, unfortunately we haven't found the solution yet.

**Comment by piotrpekala7** [comment]
Could you provide the browser you are using and its versions? Is the problem still present in the latest version of the browser?

**Comment by Raizo62** [comment]
I use Firefox 78.0.2 (64 bits)

**Comment by piotrpekala7** [comment]
Does this problem also occur when you open the web UI link from the old GUI?

**Comment by Raizo62** [comment]
Sorry, i don't understand : which link ? which old GUI ? (gns3 is on the Distribution LiveRaizo, and Firefox is on Windows 10)

**Comment by piotrpekala7** [comment]
When you use desktop UI in tools menu you have option to navigate to web UI

**Comment by Raizo62** [comment]
if i use the link in tools menu of gns3, Firefox 68.10.0esr(64 bits) stops on "http://127.0.0.1:3080/static/web-ui/bundled"

**Comment by piotrpekala7** [comment]
Unfortunately we are unable to solve it right now. It's known issue https://github.com/angular-ui/ui-router/issues/3753 in firefox

we can apply changes in BundledServerFinderComponent (similar to recommended here: https://stackoverflow.com/questions/2130241/pass-correct-this-context-to-settimeout-callback)
```
        this.progressService.deactivate();
        var that = this;
        setTimeout(function () {
          that.router.navigate(['/server', server.id, 'projects']);
        }, 300);
```
but we can't estimate value for timeout so it cause another problems while rendering projects page
In Chrome all should work properly

**Comment by Raizo62** [comment]
Sorry, but i am not agree to close this issue : 
We don't know how to solve it, ok....but the problem is not solved.
Others can have the same problem and find these infos (and perhaps they know how to patch...)

**Comment by piotrpekala7** [comment]
At the moment, in this repository, open tasks are solved sequentially by developers. In case the problem exists but the development team is unable to solve it, the task is not closed, but marked as blocked. In the case of tasks where we are not able to provide a solution and it does not depend on us, e.g. when something is not working properly in one of the browsers, the entries are marked as won't fix. We also create submissions to the repositories of browsers and packages that we use and this sometimes leads to a solution to the problem.

**Comment by piotrpekala7** [comment]
I understand that you expect a change in the way we manage this backlog from developer management to user management. In some packages it works, then users answer each other's questions. This is a kind of duplication of the forum, but it has its advantages. Then developers could define the scope of tasks to release in a completely different place.

**Comment by piotrpekala7** [comment]
Thanks for your suggestions.

**Comment by Raizo62** [comment]
I am not the only one which uses Firefox (fortunately).
Then if you want that other peoples open the same issue because they don't see this (because it is closed), as you wish
Or only gns3's developers can post here ?
