### ISSUE TITLE
Unreachable server should not prevent to see system status

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#896]
I configured a remote server with the desktop Ui.

![Screenshot from 2020-06-24 12-17-41](https://user-images.githubusercontent.com/4752614/85492793-e709c600-b614-11ea-8129-1823f7c325bd.png)

I cannot see the system status in the web-ui when this remote serve is unreachable.

![Screenshot from 2020-06-24 12-16-03](https://user-images.githubusercontent.com/4752614/85492615-9d20e000-b614-11ea-956e-7fbff8eeacbb.png)

It works again if I remove the server in the deskop Ui. I think the page should skip that server or display that it is unreachable but still allow to see the status for remaining servers.

**Comment by piotrpekala7** [comment]
I added message when statistics are not loaded, unfortunately I'm not able to fix it in web UI cause I receive error from statistics endpoint after adding remote server:

```
{
    "message": "Cannot connect to compute 'T5' with request GET /statistics",
    "status": 409
}
```
