### ISSUE TITLE
Spacing issues on system status page

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#897]
@piotrpekala7 I remember you mentioned this during our last call.

![Screenshot from 2020-06-24 12-21-15](https://user-images.githubusercontent.com/4752614/85493150-8464fa00-b615-11ea-944c-53e438184e22.png)

**Comment by piotrpekala7** [comment]
Fixed in https://github.com/GNS3/gns3-web-ui/commit/1658845022d1503508c499e96c11317d695fd365

**Comment by piotrpekala7** [comment]
![systemStatus](https://user-images.githubusercontent.com/31202938/85522624-30064e00-b606-11ea-80f9-87d13fc614ea.PNG)
