### ISSUE TITLE
Integrate link labels to links

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#933]
See https://github.com/GNS3/gns3-gui/issues/2953

This should be an option activated by default. If activated then the labels are attached the links (ignoring their x,y,z properties).

**Comment by piotrpekala7** [comment]
Will be fixed in https://github.com/GNS3/gns3-web-ui/pull/940

**Comment by piotrpekala7** [comment]
![linkLabels](https://user-images.githubusercontent.com/31202938/87407181-1c755400-c5c2-11ea-9caf-21238b1a493d.PNG)

**Comment by grossmj** [comment]
Good job. Can the labels be closer to the nodes?


The label wrappers should adapt to the interface name length:

![Screenshot from 2020-07-14 21-14-26](https://user-images.githubusercontent.com/4752614/87422051-1a89b000-c617-11ea-9a07-0562cf8c026f.png)

There should be no collision of labels too:

![Screenshot from 2020-07-14 21-16-16](https://user-images.githubusercontent.com/4752614/87422185-591f6a80-c617-11ea-8b58-6f5d8d4fa118.png)

Thanks!

**Comment by piotrpekala7** [comment]
no, labels cannot adopt to interface length: https://stackoverflow.com/questions/6725288/svg-text-inside-rect, it's not possible to add text inside svg element so we have 2 different elements

**Comment by piotrpekala7** [comment]
I can change the size of a box

**Comment by piotrpekala7** [comment]
current is 40px

**Comment by piotrpekala7** [comment]
what size do you suggest?

**Comment by grossmj** [comment]
Let's try 60px maybe?

**Comment by piotrpekala7** [comment]
ok

**Comment by piotrpekala7** [comment]
should be fixed in https://github.com/GNS3/gns3-web-ui/commit/801c10feffd73f30f8a8726dfa4614257c307a93 & https://github.com/GNS3/gns3-web-ui/commit/4125c98e82e7d6d40509502d83e6a841d0f6ce09

**Comment by piotrpekala7** [comment]
please check

**Comment by grossmj** [comment]
The fact that the boxes doesn't adapt to the interface name length is honestly kinda ugly. I wonder if we should find another solution or just scrap the idea altogether.

![Screenshot from 2020-07-17 18-55-37](https://user-images.githubusercontent.com/4752614/87771195-32537500-c85f-11ea-9c53-6a5a615b0709.png)

**Comment by piotrpekala7** [comment]
![capture_links](https://user-images.githubusercontent.com/31202938/88090068-4ebc1e00-cb8d-11ea-9b64-7cc3e6875358.PNG)

I commited modified version: the width of the box is calculated based on the length of the interface name, but I don't know how accurate it is because of the different character widths

**Comment by piotrpekala7** [comment]
on my topology it looks pretty good, I didn't think of anything else

**Comment by grossmj** [comment]
> on my topology it looks pretty good, I didn't think of anything else

Thanks, I will re-test and decide what we should do.

**Comment by grossmj** [comment]
Looks good excepting when there are multiple links between 2 nodes. I think we shouldn't display the labels in that case.

![Screenshot from 2020-07-30 16-33-37](https://user-images.githubusercontent.com/4752614/88891477-72b0eb00-d282-11ea-8847-00d59159228b.png)

Finally, I think we should have a local option to be back to the previous behavior, i.e. users can freely move labels like it used to be. It should be added there I guess:

![Screenshot from 2020-07-30 16-36-13](https://user-images.githubusercontent.com/4752614/88891751-d76c4580-d282-11ea-9a81-b60447024a7d.png)

**Comment by piotrpekala7** [comment]
we have this option in menu -> map settings, should I move it to 'local settings'?

**Comment by grossmj** [comment]
> we have this option in menu -> map settings, should I move it to 'local settings'?

I haven't seen. This is fine like this then. Thanks 👍

**Comment by piotrpekala7** [comment]
I fixed this bug with multiple labels https://github.com/GNS3/gns3-web-ui/commit/01ea42e930b4c901424ce92814af319d69314820
![3107](https://user-images.githubusercontent.com/31202938/89037177-53779380-d33e-11ea-8014-1e28b9a201a0.PNG)

**Comment by grossmj** [comment]
Just found 2 issues:

I activated the "show interface label separately" option and I got this error when I randomly move labels around:

![Screenshot from 2020-08-03 18-03-41](https://user-images.githubusercontent.com/4752614/89162915-ecfbab00-d5b3-11ea-97f8-4b6c6a2cf568.png)

I think you should make sure label positions (x, y) are integer numbers.

Deactivating the "show interface label separately" option after that doesn't show the labels anymore:

![Screenshot from 2020-08-03 18-05-07](https://user-images.githubusercontent.com/4752614/89162924-f38a2280-d5b3-11ea-8d7c-4aaa41e590ed.png)

**Comment by grossmj** [comment]
> Deactivating the "show interface label separately" option after that doesn't show the labels anymore

It works if I refresh the page.

**Comment by piotrpekala7** [comment]
to be honest, what I did seems unintuitive, I mean I wonder if there should be these two options here named like this, maybe it would be better to put only the hide / show interface labels options here and 'Integrate link labels to links' in local settings as you mentioned before?

**Comment by grossmj** [comment]
> to be honest, what I did seems unintuitive, I mean I wonder if there should be these two options here named like this, maybe it would be better to put only the hide / show interface labels options here and 'Integrate link labels to links' in local settings as you mentioned before?

Let's do this, this is better 👍

**Comment by piotrpekala7** [comment]
Fixed in https://github.com/GNS3/gns3-web-ui/commit/75de6d2c388172a53312645855633b894ee56b7a

**Comment by piotrpekala7** [comment]
I tested on 2 topologies
