### ISSUE TITLE
Cannot select "install the appliance locally"

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#945]
I cannot select "install the appliance locally" when adding a new appliance.

![Screenshot from 2020-07-17 19-01-41](https://user-images.githubusercontent.com/4752614/87771807-01277480-c860-11ea-8ea5-fed1485cbed6.png)

The GNS3 VM is not configured:

![Screenshot from 2020-07-17 19-02-59](https://user-images.githubusercontent.com/4752614/87771924-2ddb8c00-c860-11ea-93bb-4db4e47e9323.png)

**Comment by piotrpekala7** [comment]
should be fixed in https://github.com/GNS3/gns3-web-ui/commit/2c9ea028d7dd2aee0304ee78636329c0d4e46bda

**Comment by piotrpekala7** [comment]
I checked how it works in GUI and:
-> Install appliance on the GNS3 VM is always set as default option
-> Option to install appliance locally is available when you choose appliance with Dynamips emulator

please correct me if I'm wrong or if we should change something

**Comment by grossmj** [comment]
> Install appliance on the GNS3 VM is always set as default option

The GNS3 VM is the default option if there is a compute with the "vm" compute_id.

> Option to install appliance locally is available when you choose appliance with Dynamips emulator.

This depends on the capabilities of the a compute. The option to install an appliance locally is always available for Linux (determined from the `platform` field of a compute). If it is macOS or WIndows, then installing locally is only possible when `emulator_type` is equal to `dynamips`.

You get all the compute information with a GET request to `http://localhost:3080/v2/computes`

```
[
    {
        "capabilities": {
            "node_types": [
                "cloud",
                "ethernet_hub",
                "ethernet_switch",
                "nat",
                "vpcs",
                "virtualbox",
                "dynamips",
                "frame_relay_switch",
                "atm_switch",
                "qemu",
                "vmware",
                "traceng",
                "docker",
                "iou"
            ],
            "platform": "linux",
            "version": "2.2.11"
        },
        "compute_id": "local",
        "connected": true,
        "cpu_usage_percent": 1.5,
        "host": "127.0.0.1",
        "last_error": null,
        "memory_usage_percent": 17.6,
        "name": "Main server",
        "port": 80,
        "protocol": "http",
        "user": null
    }
]
```

**Comment by piotrpekala7** [comment]
fixed in https://github.com/GNS3/gns3-web-ui/commit/ffb3646d084e82cdcd6ccde05073677160dc277c

**Comment by grossmj** [comment]
Seems fine now, thanks :+1:
