### ISSUE TITLE
Cannot clearly see tooltips when hovering elements

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#948]
I noticed we cannot clearly see tooltips when hovering elements of the web-ui. This may because we upgraded packages...

![Hover_1](https://user-images.githubusercontent.com/4752614/88887756-2e225100-d27c-11ea-9513-27a479e1a402.png)

![Hover_2](https://user-images.githubusercontent.com/4752614/88887767-37132280-d27c-11ea-8d79-a087aa1b4af3.png)

**Comment by piotrpekala7** [comment]
yes, this issues appeared after migrating to Angular 10

**Comment by piotrpekala7** [comment]
I found solution here https://stackoverflow.com/questions/49989070/mattooltipclass-not-applying-css

**Comment by piotrpekala7** [comment]
fixed in https://github.com/GNS3/gns3-web-ui/commit/af564d6cd7f302bebf2c93034445f1507bf9a8ff
