### ISSUE TITLE
"Usage" support for cloud templates and nodes

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#949]
Starting with GNS3 version 2.3, cloud templates and nodes now support the "usage" field, similar to Qemu VMs or Dynamips nodes.

![Screenshot from 2020-07-30 19-20-38](https://user-images.githubusercontent.com/4752614/88909069-d2ff5700-d299-11ea-9afc-d27292743bab.png)

**Comment by piotrpekala7** [comment]
added in https://github.com/GNS3/gns3-web-ui/commit/cb6cacc5578d8c05e946aec5eab120168376ba7c, branch master-2.3

**Comment by grossmj** [comment]
Verified, thanks :+1:
