### ISSUE TITLE
Reset link support

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#950]
Starting with GNS3 2.3, users can now reset links (just like they can delete, suspend etc.)

The API endpoint is `/v2/projects/{project_id}/links/{link_id}/reset`, for instance `/v2/projects/1186499b-132b-4c6b-9a56-84a3f00ec227/links/c0f73981-3fa3-483b-9bfc-a4678245a63f/reset`

**Comment by piotrpekala7** [comment]
added in https://github.com/GNS3/gns3-web-ui/commit/bf4f2dcdb71bb5db6de9a7016e70c348d6741c72, branch master-2.3
