### ISSUE TITLE
CPUs and memory limitation for Docker containers

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#951]
Starting with GNS3 2.3, users can limit the amount of memory and CPU resources a Docker container can use.

![Screenshot from 2020-07-31 14-22-55](https://user-images.githubusercontent.com/4752614/89001630-ea8e1c80-d339-11ea-837c-979f754e5da5.png)

The two new properties are:

* `memory`: maximum amount of memory the container can use in MB (integer), for instance 1024MB will limit the container to use a maximum 1GB of RAM.
* `cpus`: maximum amount of CPU resources the container can use (float), for instance 0.5 will limit the container to 50% of a CPU core.

**Comment by piotrpekala7** [comment]
added in https://github.com/GNS3/gns3-web-ui/commit/8d795ebf1011b66c1b084f1d28594fe07f28062f in node configurator, branch master-2.3

**Comment by piotrpekala7** [comment]
when I try to test it and drag docker node on topology I receive following error: Cannot connect to compute 'GNS3 VM with request POST', server branch 2.3, similar issue in GUI repo https://github.com/GNS3/gns3-gui/issues/2969

**Comment by piotrpekala7** [comment]
by the way, I don't know why, but the configurator for this type of nodes in the web UI does not cover all the functions from the old interface

**Comment by grossmj** [comment]
We shouldn't allow negative values and default value for CPUs should be 0.0 to show that float value is allowed. Also, MB should be added as a suffix for the memory field.

![Screenshot from 2020-09-05 17-33-41](https://user-images.githubusercontent.com/4752614/92300915-17b79580-ef9e-11ea-91c9-8f87f91ebd25.png)

**Comment by grossmj** [comment]
> by the way, I don't know why, but the configurator for this type of nodes in the web UI does not cover all the functions from the old interface

I will open an new issue for this.

**Comment by piotrpekala7** [comment]
ok added in https://github.com/GNS3/gns3-web-ui/commit/169a06fd3a63acf67a207713fbbe54652c61e1f7
