### ISSUE TITLE
Open web console in new tab seems broken

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#954]
Opening a console in a new tab result in a 404 error:

![Screenshot from 2020-08-04 22-24-58](https://user-images.githubusercontent.com/4752614/89296419-763cdb80-d6a1-11ea-9a74-7b766b19ad71.png)

Not an issue if not opening in a new tab.

![Screenshot from 2020-08-04 22-26-24](https://user-images.githubusercontent.com/4752614/89296548-a3898980-d6a1-11ea-813a-651a8e85faa5.png)

**Comment by piotrpekala7** [comment]
it appears only in development mode (static/web-ui in the url) but I added workaround for this https://github.com/GNS3/gns3-web-ui/commit/b78f3824fc7a0a9d92b11e052a1c5497cf9c646c
