### ISSUE TITLE
Error when loading the web-ui

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#956]
I always get this error when the web-ui is loaded and I refresh the servers page.

![Screenshot from 2020-08-05 18-29-06](https://user-images.githubusercontent.com/4752614/89393205-9f18ab80-d749-11ea-9ce5-9c0b0cc9685e.png)

**Comment by grossmj** [comment]
This may be due one of the last commits.

**Comment by piotrpekala7** [comment]
![errorAdbutler](https://user-images.githubusercontent.com/31202938/89395942-424bcf80-d70e-11ea-8654-233ec4aab816.PNG)
full error in browser console

**Comment by piotrpekala7** [comment]
the reason is an invalid adbutler campaign

**Comment by grossmj** [comment]
The adbutler campaign has been fixed now. Should we catch the error and display a more meaningful message if there is a problem again in the future?

**Comment by piotrpekala7** [comment]
catching errors was added https://github.com/GNS3/gns3-web-ui/commit/d1fb7e662432252ebe182e7fc5c9e93368c020db

**Comment by piotrpekala7** [comment]
but we should probably have some static advertising in case something happens to the adbutler

**Comment by piotrpekala7** [comment]
exactly, I think so

**Comment by grossmj** [comment]
I created an issue for this: https://github.com/GNS3/gns3-web-ui/issues/957

I think we can close this.
