### ISSUE TITLE
Issues with servers requiring authentication

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#958]
I configured authentication in a local GNS3 server and a server running inside GNS3 VM. Then I tried to control these servers using the development version of the Web-Ui (localhost:4200). Listing the projects works however I get errors if I try to open projects.

**Local server**

![Screenshot from 2020-08-06 18-52-58](https://user-images.githubusercontent.com/4752614/89515761-b6719a80-d816-11ea-9200-0f30a8b77bb5.png)

![Screenshot from 2020-08-06 18-52-31](https://user-images.githubusercontent.com/4752614/89515765-b70a3100-d816-11ea-8fd8-836e7e0946e9.png)

**GNS3 VM**

![Screenshot from 2020-08-06 18-55-49](https://user-images.githubusercontent.com/4752614/89515757-b5d90400-d816-11ea-9d18-11e6c14ed081.png)

![Screenshot from 2020-08-06 18-56-05](https://user-images.githubusercontent.com/4752614/89515753-b40f4080-d816-11ea-9509-f18fcc0cd57d.png)

I do not have issues with the bundled Web-Ui because the browser ask for the credentials once:

![Screenshot from 2020-08-06 19-02-42](https://user-images.githubusercontent.com/4752614/89516738-f84f1080-d817-11ea-838a-6508f4bce735.png)

**Comment by piotrpekala7** [comment]
I can confirm that the problem described by you exists. Unfortunately, at the moment I have not found a solution for it. We add credentials in headers https://github.com/GNS3/gns3-web-ui/blob/master/src/app/services/http-server.service.ts#L189 so request to the server should be correct. This request is the same for both the released version and the development version.

**Comment by piotrpekala7** [comment]
When the user enters credentials, the browser resubmits the same request to the same URL, plus it also adds this extra header:
`    Authorization: Basic username:password`
so as you see we do the same

**Comment by piotrpekala7** [comment]
I have not found any additional information on this subject. Due to possible change of authentication, this problem will not be solved temporarily

**Comment by piotrpekala7** [comment]
outdated as we implemented secured endpoints in 3.0
