### ISSUE TITLE
Add template improvements 

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#962]
The Qemu binary should be set to the first available by default.

Also the window is kind of small, especially with appliance with many options. Could we increase the size? 

![Screenshot from 2020-08-14 21-00-10](https://user-images.githubusercontent.com/4752614/90245154-4647c200-de71-11ea-99e9-463fd59e68cd.png)

**Comment by piotrpekala7** [comment]
I changed default height to 700px

**Comment by piotrpekala7** [comment]
I can't do it now cause third page is rendered dynamically (it depends on previous choices). If it's really important we can create separate menu for qemu devices... don't know if it's good idea

**Comment by piotrpekala7** [comment]
as I understand we can skip the functionality with qemu binary?

**Comment by grossmj** [comment]
I think the Qemu binary should be set based on the information we have in the appliance, for instance if we have `x86_64` https://github.com/GNS3/gns3-registry/blob/master/appliances/cisco-iosv.gns3a#L21 then `/usr/bin/qemu-system-x86_64` should be automatically set in the drop down list. Let the user select if the info is not available.

**Comment by grossmj** [comment]
David has reported a refresh issue with the appliance import feature.

![Screenshot from 2020-09-03 18-58-04](https://user-images.githubusercontent.com/4752614/92097924-c67d9980-ee17-11ea-8829-be6e67af815d.png)

I import the missing file for the appliance. There should be a progress bar here because I had to wait a few minutes not knowing if the file was being uploaded.

![Screenshot from 2020-09-03 19-07-16](https://user-images.githubusercontent.com/4752614/92098707-b9ad7580-ee18-11ea-98f3-d387d77935cd.png)

While the file was uploading, I tried the click import again and then pressed escape, I have seen this error message:

![Screenshot from 2020-09-03 19-06-15](https://user-images.githubusercontent.com/4752614/92099027-288ace80-ee19-11ea-89ad-784077a95a76.png)

I think having a progress bar would avoid this bug.

Finally, the appliance window should be refreshed after the file has been imported. Here I had to start it again from the beginning:

![Screenshot from 2020-09-03 18-59-30](https://user-images.githubusercontent.com/4752614/92097949-cbdae400-ee17-11ea-8339-13fa48e76ab9.png)

**Comment by grossmj** [comment]
I think we should also add a button to manually refresh.

**Comment by piotrpekala7** [comment]
most of the problems you mentioned fixed in https://github.com/GNS3/gns3-web-ui/commit/0ccae1dde731d655c87fa776e3fd341656c285e6

**Comment by grossmj** [comment]
Thanks, the progress bar and refresh work :+1:

**Comment by piotrpekala7** [comment]
I added refresh button after 'Install required files...' https://github.com/GNS3/gns3-web-ui/commit/bbb344557b33f16694551fb76ab982544fd6f302

**Comment by grossmj** [comment]
> I added refresh button after 'Install required files

Excellent :+1:

**Comment by piotrpekala7** [comment]
> I think the Qemu binary should be set based on the information we have in the appliance, for instance if we have `x86_64` https://github.com/GNS3/gns3-registry/blob/master/appliances/cisco-iosv.gns3a#L21 then `/usr/bin/qemu-system-x86_64` should be automatically set in the drop down list. Let the user select if the info is not available.

should I cover any other cases?

**Comment by grossmj** [comment]
> should I cover any other cases?

Yes, 2 more cases:

* i386 shoud select `qemu-system-i386`
* arm should select `qemu-system-arm` (if available of course).

**Comment by piotrpekala7** [comment]
added in https://github.com/GNS3/gns3-web-ui/commit/00d4a5ff920233a6e10591f38d3ec99948f3de3e

**Comment by grossmj** [comment]
All good :+1:
