### ISSUE TITLE
ui - diagram

### ISSUE THREAD

**Issue by softov** [GNS3/gns3-web-ui#963]
Hi, sorry to disturb, I was unable to found another place to post.

I finally started testing gns3 and was amazed.
I saw that you are very active and I thought that maybe I could help in some way.
I recently started doing a project at brbyte and saw some information related to connection modeling.

Have you ever seen anything like this for the project?
https://github.com/projectstorm/react-diagrams

https://github.com/projectstorm/react-diagrams/blob/master/.gitbook/assets/example1.jpg

You can create a element, and have PORTS (multiple connections related to it).

**Comment by piotrpekala7** [comment]
Hi, thank you for the information. We're basically using Angular, but can use React components. Do you suggest using this component in the topology map or do you have any other idea?

**Comment by softov** [comment]
Hi, its in the topology map.

Were I work we use C to do the backend and REST HTTP api.
In the interface we use extjs in the baseui, reactjs in the responsive ui and angularjs 1.5 to do some interfaces that require templates (customer personal site, customer panel).

In all of then I get more flexibility and felt more 'ui fluid' with reactjs, not talking using modules, only about way the reactjs update the interface and the control over the component.

**Comment by softov** [comment]
I was thinking about the part 
`but can use React components` 
You are talking about migrate the entire UI to reactjs or merging reactjs with angular?

ps. I'm using angularjs, and I tried angular.io before reactjs, din't like

**Comment by piotrpekala7** [comment]
as I know it's possible to use react components in angular application

**Comment by piotrpekala7** [comment]
We are not planning to rewrite the web interface to another technology for the moment.

**Comment by piotrpekala7** [comment]
Thank you for your suggestions. If you want to create your interface, documentation can be found here: https://docs.gns3.com/
