### ISSUE TITLE
veOS images doesn't work - 'multilayer_switch' is not of type 'integer' 

### ISSUE THREAD

**Issue by nosy** [GNS3/gns3-web-ui#967]
Acer Aspire based on i7-6500 cpu, 32gb ram

vmware pro 15+
https://www.vmware.com/go/getworkstation-win

gns3 vm
https://github.com/GNS3/gns3-gui/releases/download/v2.2.12/GNS3.VM.VMware.Workstation.2.2.12.zip

arista images
https://www.arista.com/en/support/software-download

![arista_bad](https://user-images.githubusercontent.com/49394518/91331883-10410100-e7d4-11ea-9a87-aa101a6fd514.png)

**Comment by nosy** [comment]
Also combined images doesn't work too.
![arista_combined](https://user-images.githubusercontent.com/49394518/91333363-3071bf80-e7d6-11ea-9bd7-679a59aa922f.png)

**Comment by piotrpekala7** [comment]
@grossmj there are appliances with multi_layer switch category but I cannot create templates from them, should I change template category in that case?

**Comment by grossmj** [comment]
I need to investigate this. Most likely a problem on back-end side by the look of it.

**Comment by b-ehlers** [comment]
The template in the gns3-server uses the categories "router", "switch", "guest" and "firewall", see <https://github.com/GNS3/gns3-server/blob/master/gns3server/schemas/template.py#L52>.

The appliances use the category "router", "multilayer_switch", "guest" and "firewall", see <https://github.com/GNS3/gns3-registry/blob/master/schemas/appliance_v6.json#L21>.

The GUI maps the "multilayer_switch" from the appliance to "switch" for use in a template, see <https://github.com/GNS3/gns3-gui/blob/master/gns3/registry/appliance_to_template.py#L53>.

**Comment by grossmj** [comment]
@piotrpekala7 thanks to @b-ehlers for investigating this before I did, the solution is simply to map "multilayer_switch" to "switch" category in the web-ui just like we do in the desktop Ui:

```
if appliance_config["category"] == "multilayer_switch":
    new_template["category"] = "switch"
```

**Comment by piotrpekala7** [comment]
fixed in https://github.com/GNS3/gns3-web-ui/commit/36b610eafa4f2b66b806c8cbe4864989facba930
