### ISSUE TITLE
Suspend issues

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#972]
I noticed issues when suspending a node.

The node is running.

![Screenshot from 2020-09-04 02-49-46](https://user-images.githubusercontent.com/4752614/92146947-99ea7180-ee59-11ea-873d-84b0dc0ac3bf.png)

Right click and select suspend. A yellow square should be shown in the node summary and there is no way to resume the node using the contextual menu (start is not available).

![Screenshot from 2020-09-04 02-50-30](https://user-images.githubusercontent.com/4752614/92146940-9951db00-ee59-11ea-8282-0dfc8c3f79d2.png)

![Screenshot from 2020-09-04 02-51-01](https://user-images.githubusercontent.com/4752614/92146933-97881780-ee59-11ea-849c-caec6ea10995.png)

**Comment by piotrpekala7** [comment]
fixed in https://github.com/GNS3/gns3-web-ui/commit/61bb6e45bfac4bdd47f8f3046bdd59c0a6dcd183
