### ISSUE TITLE
web console doesn't close properly serial access ?

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-web-ui#973]
Hi

On my VMs, i have a program to calculate the size of the serial console.
If I open simultaneously several consoles on the same VM, i know that i have glyph on the prompt of the VM.

On the web-ui, if i use on this VM the web console, i have no glyph
I close the web console with the cross.
I open again the web console of this VM, then, i have glyph.

I must close the VM to make the problem disappear

I suppose that close the web console doesn't close properly the access to the serial console

**Comment by piotrpekala7** [comment]
Hi,
Thanks for reporting.
We use xtermjs for console support. That component is responsible for handling connections. Did you find a similar problem in their repository?

**Comment by piotrpekala7** [comment]
https://github.com/xtermjs/xterm.js/issues

**Comment by piotrpekala7** [comment]
If you find any problems, we can create a task on the xterm side and as soon as they fix it, we will update the version to the latest one

**Comment by Raizo62** [comment]
I will have difficulty to find similar issue in xterm.js because i don't know how you use this code with gns3 server.
And perhaps that i was the first to see it or to speak of it.

But, i have a little proof of the bug. With netstat on gns3server, i displays the number of connections of "Firefox" to gns3server.

- Only the lab with 1 running VM, i have 1 connexion
- I open a web console, i have 2 connections (include the first)
- I close the VM with the little cross (I have always the console "GNS console"), i have always 2 connections (ESTABLISHED)
- I open again the web console, i have 3 connections

**Comment by piotrpekala7** [comment]
Ok, thank you for explanation. We're unable to fix it by our side but I will open task in xterm js repository. We're updating packages regular so after they release new version we'll switch to it
