### ISSUE TITLE
Missing settings for Docker nodes

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#975]
I don't know since when but we are missing some configuration settings for Docker nodes (max memory and max CPUs are already on master-2.3 branch). Where they present in a previous version of the web-ui? This needs to be investigated.

![Screenshot from 2020-09-05 17-40-07](https://user-images.githubusercontent.com/4752614/92301040-3b2f1000-ef9f-11ea-808c-c933565f6a18.png)

![Screenshot from 2020-09-05 17-40-17](https://user-images.githubusercontent.com/4752614/92301042-3ff3c400-ef9f-11ea-8b6c-cfcaca1c0806.png)

![Screenshot from 2020-09-05 17-37-12](https://user-images.githubusercontent.com/4752614/92301033-2bafc700-ef9f-11ea-9fac-0c0d21cf84f4.png)

![Screenshot from 2020-09-05 17-37-34](https://user-images.githubusercontent.com/4752614/92301037-31a5a800-ef9f-11ea-8547-edbda5c3cd6a.png)

**Comment by piotrpekala7** [comment]
I added some missing features in https://github.com/GNS3/gns3-web-ui/commit/c7db04ce3b1f76a6e1a872abcb56ad026ecf7e25

**Comment by piotrpekala7** [comment]
Could you please give me more information (acceptance criteria) about following dialogs:
1) Network configuration
2) Configure custom adapters

**Comment by grossmj** [comment]
> Network configuration

This should open a dialog to edit a config file for the Docker node, the file is `/etc/network/interfaces` and content can be retrieved with GET request on `/v2/projects/{project_id}/nodes/{node_id}/files/etc/network/interfaces`

Example:

```
curl "http://127.0.0.1:3080/v2/projects/26e3abab-79f4-4035-9025-6eed03a04f58/nodes/84a91f68-5960-422c-8e56-2445c4faa511/files/etc/network/interfaces"
#
# This is a sample network config uncomment lines to configure the network
#


# Static config for eth0
#auto eth0
#iface eth0 inet static
#	address 192.168.0.2
#	netmask 255.255.255.0
#	gateway 192.168.0.1
#	up echo nameserver 192.168.0.1 > /etc/resolv.conf

# DHCP config for eth0
# auto eth0
# iface eth0 inet dhcp
```

![Screenshot from 2020-09-14 06-28-51](https://user-images.githubusercontent.com/4752614/93028636-41cf1e80-f654-11ea-8ab2-3ea9da65d07f.png)

The content has changed, it can be uploaded with a POST request to `/v2/projects/{project_id}/nodes/{node_id}/files/etc/network/interfaces`

> Configure custom adapters.

I think we should have something similar to what is done with Qemu nodes.

![Screenshot from 2020-09-14 06-21-49](https://user-images.githubusercontent.com/4752614/93028365-ac7f5a80-f652-11ea-9b49-74b4dcf23a32.png)

The only difference is there are no adapter types for Docker nodes. Users should be able to only change port names.

![Screenshot from 2020-09-14 06-21-28](https://user-images.githubusercontent.com/4752614/93028367-b30dd200-f652-11ea-8232-5ad8393e8831.png)

**Comment by piotrpekala7** [comment]
added in https://github.com/GNS3/gns3-web-ui/commits/master
