### ISSUE TITLE
Add update from online registry

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#976]
It would be good to add a button to update the appliances from our online registry. The request is a GET on `/v2/appliances?update=yes`

![Selection_004](https://user-images.githubusercontent.com/4752614/92301212-c8269900-efa0-11ea-8289-b9f2a8775461.png)

**Comment by piotrpekala7** [comment]
@grossmj this button should be located on second page in web UI dialog?

**Comment by grossmj** [comment]
Yes, should be located on this page:

![Screenshot from 2020-09-07 17-29-28](https://user-images.githubusercontent.com/4752614/92362852-c3441f80-f12f-11ea-93fc-e87bf731e272.png)

**Comment by piotrpekala7** [comment]
https://github.com/GNS3/gns3-web-ui/commit/b32fdf4fc2c9f4c766d7b67696f858905ced7fb3

**Comment by grossmj** [comment]
We need to have a progress bar and wait for the request to be finished since this could take a few minutes depending if the appliance files are up-to-date. A message box should be displayed to inform users that the files have been updated (if the request is successful).

![Screenshot from 2020-09-08 06-41-24](https://user-images.githubusercontent.com/4752614/92416796-603da180-f19e-11ea-8353-905cfbd2ca90.png)

**Comment by piotrpekala7** [comment]
ok, added https://github.com/GNS3/gns3-web-ui/commit/93532d3274705a749976025a0bc675a0eb68bbe1
