### ISSUE TITLE
Avoid to create multiple templates with the same name

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#977]
When adding a new template using the wizard, the web-ui should check if other templates use the same name and propose to the user to change it.

![Screenshot from 2020-09-05 17-59-31](https://user-images.githubusercontent.com/4752614/92301295-b7c2ee00-efa1-11ea-8bf9-d94ddb1e7eb8.png)

![Screenshot from 2020-09-05 17-59-42](https://user-images.githubusercontent.com/4752614/92301298-bd203880-efa1-11ea-9934-5f96d1691660.png)

**Comment by piotrpekala7** [comment]
should be fixed in https://github.com/GNS3/gns3-web-ui/commit/87aa6c4b59495538664c50dc49d8821898764f0d and in https://github.com/GNS3/gns3-web-ui/commit/81bc3cb3bd339e75aa4ff767d4a40b5a2adb09a5

**Comment by grossmj** [comment]
Working well however let's have the box displayed every time with the default name filled in, for instance with the IOSvL2 instance:

![Screenshot from 2020-09-09 06-17-20](https://user-images.githubusercontent.com/4752614/92526167-2a62f080-f264-11ea-9b8d-a41c130f023c.png)

This will be more explicit and give users a chance to choose the template name even if it is not already used.

**Comment by piotrpekala7** [comment]
fixed in https://github.com/GNS3/gns3-web-ui/commit/dd7dcf4dabcd90c096413b872f46c51d66ba1ec8

**Comment by piotrpekala7** [comment]
verified with 3 scenarios:
-> template with the same name exists
-> template with name from appliance does not exist
-> user enters incorrect name
