### ISSUE TITLE
Cannot install appliance that has only one disk image

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#978]
Example with Cumulus:

![Screenshot from 2020-09-06 18-50-16](https://user-images.githubusercontent.com/4752614/92322695-fa53fb80-f071-11ea-85c7-8f537eb7a211.png)

Example with IOSv-L2:

![Screenshot from 2020-09-06 18-51-00](https://user-images.githubusercontent.com/4752614/92322698-fde78280-f071-11ea-830e-7dcda464dd6c.png)

There is no problem with appliances that have multiple disk images:

![Screenshot from 2020-09-06 18-53-06](https://user-images.githubusercontent.com/4752614/92322740-456e0e80-f072-11ea-983a-0d01229ad770.png)

**Comment by piotrpekala7** [comment]
improvements in https://github.com/GNS3/gns3-web-ui/commit/6f991e488594c6d6ef5b48140f8f2d6186d282f2

**Comment by piotrpekala7** [comment]
@grossmj I checked with 3 examples (single and multiple images) but please verify again

**Comment by grossmj** [comment]
All good. Thanks.
