### ISSUE TITLE
HTTP 409 errors reported on Sentry

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#979]
We are still getting HTTP 409 (conflict) errors on Sentry. These should be reported.

![Screenshot from 2020-09-06 18-56-30](https://user-images.githubusercontent.com/4752614/92323167-a21ef880-f075-11ea-8fd4-620a2545b435.png)

**Comment by piotrpekala7** [comment]
fixed in https://github.com/GNS3/gns3-web-ui/commit/fe02a4cb79fcfd49a8e02299ade622dbde67e614
