### ISSUE TITLE
Servers page with bundled web-ui

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#980]
I get an error when going to the servers page for the bundled web-ui (inside the GNS3 VM v2.2.13).

![Screenshot from 2020-09-07 07-25-11](https://user-images.githubusercontent.com/4752614/92336009-733b6d80-f0db-11ea-928e-1509bf1f0ff0.png)

**Comment by piotrpekala7** [comment]
Please give me more information:
- does this occur all the time
- browser 
- context: after refreshing page or in other case

**Comment by grossmj** [comment]
* This happens every time.
* Google Chrome and Firefox on Linux.
 
**Context**

1. Enter the IP address of the GNS3 VM in a browser, e.g. http://172.16.9.129
2. The GNS3 server redirects to the bundled web ui, http://172.16.9.129/static/web-ui/server/1/projects
3. The projects page is shown.
4. Click on `Servers` on the top left.
5. The error is displayed.

I have tried with Firefox and I get a different error message.

![Screenshot from 2020-09-08 06-09-16](https://user-images.githubusercontent.com/4752614/92415965-62056600-f19a-11ea-8556-c140e50f7d03.png)

**Comment by piotrpekala7** [comment]
I tried to analyze this bug:
1) I have no idea what could be the reason of second error (screen from Firefox)

**Comment by piotrpekala7** [comment]
when it comes to error 'Cannot read property from Promise of undefined' we use Observable.fromPromise in SeverDiscoveryComponent and we pass findAll() as Promise from ServerService, I'm not sure why we decided to use IndexedDb (while we use local storage in incognito mode and this works fine), but I'm not able to debug this area

**Comment by piotrpekala7** [comment]
at the moment I don't know how to solve this problem

**Comment by piotrpekala7** [comment]
I removed deprecated methods in https://github.com/GNS3/gns3-web-ui/commit/e16152edafb69fab36293b3f15c9a342ff8ece5e

**Comment by piotrpekala7** [comment]
I didn't reproduce the error after removing deprecated methods
