### ISSUE TITLE
Verify MD5 checksum before uploading

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#983]
I am not sure this is possible in a browser but could we check for the MD5 checksum before uploading a disk image when adding a new template?

For instance in the desktop interface, a warning is shown if an user tries to upload a file with a MD5 checksum that doesn't match what is indicated in the appliance info:

![Screenshot from 2020-09-08 17-26-22](https://user-images.githubusercontent.com/4752614/92449203-dcfd6980-f1f8-11ea-83f7-283ed19761e3.png)

Users can override this by checking `Allow custom files`.

![Screenshot from 2020-09-08 17-26-56](https://user-images.githubusercontent.com/4752614/92449216-e090f080-f1f8-11ea-887b-37e855803639.png)

https://github.com/GNS3/gns3-gui/blob/master/gns3/registry/registry.py#L85L87

Not sure we should include this override feature though but the MD5 check could be great.

**Comment by piotrpekala7** [comment]
As I understand you want to check MD5 checksum before importing appliance image?

**Comment by grossmj** [comment]
> As I understand you want to check MD5 checksum before importing appliance image?

Correct, before the image is uploaded to the server.

**Comment by piotrpekala7** [comment]
ok, I find information about one package that can work https://dev.to/qortex/compute-md5-checksum-for-a-file-in-typescript-59a4, not sure if it's not blocked by browser

**Comment by piotrpekala7** [comment]
I tried to use this solution, check here https://github.com/GNS3/gns3-web-ui/compare/Verify-MD5-checksum-before-uploading?expand=1 but the md5sum is different

![md5](https://user-images.githubusercontent.com/31202938/92944238-06fe9800-f454-11ea-855d-61bf09cf7d52.PNG)

**Comment by piotrpekala7** [comment]
I didn't find any other packages for angular 2+

**Comment by piotrpekala7** [comment]
at the moment, I have not found any new information on how to implement this task

**Comment by grossmj** [comment]
This may help you: https://levelup.gitconnected.com/how-to-upload-a-file-from-an-angular-app-using-a-json-post-rather-than-form-data-d713a5966b96 => "Task 1.3: Get MD5 Hash of File Data".

**Comment by piotrpekala7** [comment]
Thanks, I will check it

**Comment by piotrpekala7** [comment]
should be fixed in https://github.com/GNS3/gns3-web-ui/commit/5668016ef55f31225fa14d191c0b40761cd0dbff

**Comment by piotrpekala7** [comment]
@grossmj 
Could you check please before next release?

**Comment by grossmj** [comment]
The is something wrong.

I want to import `IOSv_startup_config.img` but chose a random file. I get the expected error message that the MD5 checksum isn't valid and then click no.

![Screenshot from 2020-12-02 15-00-48](https://user-images.githubusercontent.com/4752614/100828580-5c749f00-34af-11eb-8295-cb1c74648afc.png)

I click on import again and this time I select the right file and I get the message that the image has been successfully imported.

![Screenshot from 2020-12-02 15-01-08](https://user-images.githubusercontent.com/4752614/100828587-626a8000-34af-11eb-8ed3-f574ab12e56f.png)

However, `IOSv_startup_config.img` isn't marked as imported. Checking `http://<GNS3_SERVER_IP>/v2/computes/local/qemu/images` API endpoint, I can see that the invalid file has been uploaded instead (same MD5 checksum as in the first error message).

```
[
    {
        "filename": "IOSv_startup_config.img",
        "filesize": 3070529,
        "md5sum": "bb54324c09dc197f1ffd2af63cee3217",
        "path": "IOSv_startup_config.img"
    }
]
```

Tried to import`IOSv_startup_config.img` again and this time nothing happens.

**Comment by piotrpekala7** [comment]
@grossmj 
Sorry, I didn't clear file queue after closing dialog https://github.com/GNS3/gns3-web-ui/commit/c956bc84c8afdd8b1d689d0fc23e8a24b82e76f1. Now everything should be fine

**Comment by grossmj** [comment]
Perfect, working as expected now. One last thing is I noticed there is a slight delay when importing a large image, I guess this is the time spent to compute the MD5 checksum for the file. Would it be possible to have a progress bar at this time?

**Comment by piotrpekala7** [comment]
Yes, added https://github.com/GNS3/gns3-web-ui/commit/60aa98e721b8e402c17eb88033cad7fd3e9da8f6

**Comment by grossmj** [comment]
Works well, thanks.
