### ISSUE TITLE
GNS3 WEB Client Pack not launching 

### ISSUE THREAD

**Issue by 25139581** [GNS3/gns3-web-ui#984]
After upgrading to Linux Mint 20 from 19.3 (a fresh clean install) I am unable to launch the GNS3 Web Client Pack - it says its successfully installed however no shortcut is created to launch the application and configure application preferences etc.

I have tried installing from the PPA as per follows:

sudo add-apt-repository ppa:gns3/unstable
sudo apt-get update
sudo apt-get install gns3-webclient-pack

I have also tried I downloading the debian package and tried re-installing but with the same outcome.

I have tried this on multiple PCs (all with Linux Mint 20 installed) all with the same outcome.

Unfortunately this means I can't launch any vnc console connections / pcap etc from the webui and have to revert back to gns3 client

Any assistance would be greatly received and thanks for the great work on the GNS3 WebUI so far!

**Comment by grossmj** [comment]
I would uninstall the Debian package and try to install using pip:

```
sudo python3 -m pip install gns3-webclient-pack
```

**Comment by piotrpekala7** [comment]
@25139581 Did it help you?

**Comment by 25139581** [comment]
Thanks guys,

I was able to uninstall the Debian package (sudo apt-get remove gns3-webclient-pack*)

Then reinstall with:

wget -qO- https://raw.githubusercontent.com/GNS3/gns3-webclient-pack/master/install.sh | sh

I had to log off then log back on for the application to show 

I did try install using pip but it gave an error message even though

Thanks again and keep up the fantastic work!
