### ISSUE TITLE
Feature request: Better sorting for node type listing

### ISSUE THREAD

**Issue by CapnCheapo** [GNS3/gns3-web-ui#985]
Hi friends,

It would be helpful for installations with a large number of different node types to support at minimum, alphabetical sorting by name (I think they are in random order currently) or even better if they could be sorted like the GUI where there are categories like switch, router, firewall, etc (and then alphabetically sorted by name under those categories).  

![Capture](https://user-images.githubusercontent.com/22641788/92511030-5a61b380-f1d2-11ea-80c4-2755962dfeba.PNG)

**Comment by piotrpekala7** [comment]
Hi,
thanks for feature request. I added better sorting https://github.com/GNS3/gns3-web-ui/commit/cf725931f9131baa4ea5e90c2be420db46a867c1. 
We have no plans to introduce additional grouping by category. At the moment you can do it by selecting a group of devices from the list of categories and this solution is better in our opinion. Thank you for your suggestions!
