### ISSUE TITLE
Error when open console with Firefox without gnome

### ISSUE THREAD

**Issue by Raizo62** [GNS3/gns3-web-ui#989]
Hi

I use Firefox/Linux without gnome. The web-client pack is installed.

If i open "console", Firefox shows the error page : "The address was understood".
Firefox doesn't ask me which program to start.
(if i install chromium and use it, it asks me).

If i want to teach to Firefox to use xdg-open, i must write in the url bar : 
`data:text/html,%3Ca href="gns3+telnet%3Atest.com"%3E%26lt;gns3+telnet:test.com%26gt;%3C/a%3E`
and click on the link

**Comment by grossmj** [comment]
What Linux distribution to you use?

**Comment by Raizo62** [comment]
Always LiveRaizo ;-) : Debian backport

**Comment by Raizo62** [comment]
For info : before, i need also to add in "about:config" : 
`network.protocol-handler.expose.gns3+telnet = false`

**Comment by piotrpekala7** [comment]
Please provide also version of Firefox and if it's possible screenshot from error page, thanks in advance

**Comment by Raizo62** [comment]
Firefox : 68.12.0esr (64-bit)

![Capture1](https://user-images.githubusercontent.com/7449584/93092473-bf6c4c00-f69f-11ea-9e26-74259b226926.PNG)

![Capture2](https://user-images.githubusercontent.com/7449584/93092497-c98e4a80-f69f-11ea-9f48-e53d137dfc21.PNG)

**Comment by Raizo62** [comment]
![Capture3](https://user-images.githubusercontent.com/7449584/93092738-1d992f00-f6a0-11ea-9f3c-6b60bbb1d9bf.PNG)

**Comment by piotrpekala7** [comment]
Thanks for screenshots
The problem you presented is not directly related to the web interface, but with gns3-webclient-pack support for a specific Linux distribution.

**Comment by Raizo62** [comment]
> for a specific Linux distribution

Which ? Debian ?
