### ISSUE TITLE
Double click nodes to open the console

### ISSUE THREAD

**Issue by grossmj** [GNS3/gns3-web-ui#991]
I don't know if this is possible, it was suggested by one of our users.

Users could set a default/preferred supported console type (External console or Web console or Web console in tab), what ever the default is set to the double click action would launch.

**Comment by piotrpekala7** [comment]
added in https://github.com/GNS3/gns3-web-ui/commit/8ffbf1be301e2b65838c698dded1426a4d58e421

**Comment by piotrpekala7** [comment]
unit tests added in https://github.com/GNS3/gns3-web-ui/commit/e4d1ef7cf7306368a26b3c7e662f8477398da22c

**Comment by piotrpekala7** [comment]
verified, dialog to choose default behavior for the first time appears
