### ISSUE TITLE
Support for Hyper-V as virtualization engine in GNS3 VM preferences

### ISSUE THREAD

**Issue by Olaw2jr** [GNS3/gns3-web-ui#993]
Is there any expected date for this feature to be added to the web UI, it will be of much help for us running our environment on Hyper-V.

**Comment by piotrpekala7** [comment]
![hyperv](https://user-images.githubusercontent.com/31202938/94542998-cc656f80-0249-11eb-9370-6218942d693d.PNG)

Hi, you can select HyperV as virtualization engine in GNS3 VM preferences, check for 2020.2.14 version
