### ISSUE TITLE
No way to send CTRL-C in web console?

### ISSUE THREAD

**Issue by CapnCheapo** [GNS3/gns3-web-ui#996]
GNS3 Serverr 2.2.14 on Ubuntu
WebUI only on MacOS + Chrome

Is anybody else having problems sending CTRL-C from the web console?  I'm not talking about IOS and other images that require CTRL-SHIFT-6, but rather docker images and others that expect a CTRL-C to break out of certain commands., such as continuous ping.  It's possible CTRL-BREAK works but I'm on a mac keyboard...

**Comment by piotrpekala7** [comment]
@CapnCheapo 
Hi, thanks for reporting.

We use xtermjs in web UI interface so unfortunately we have some limitations. CTRL-C should work in most of cases.
Generally xterm give us option to copy paste by clicking insert xtermjs/xterm.js#2478
Moreover in some cases only ctrl+shift+v will work xtermjs/xterm.js#292, it's like in web documents
More limitations are included in this post: xtermjs/xterm.js#1411

**Comment by candlerb** [comment]
Fixed in #1125
